import type { KategoriIcerigi } from "./tipler";

/**
 * Haber kategorisi — 100+ liste.
 *
 * Bu kategorideki listeler güncel olaylardan çok, haberciliğin kendisine
 * ve gündemin kalıcı başlıklarına odaklanıyor: kaynaklar, sunucular,
 * programlar, tartışma konuları. Günlük haber akışını gündem taraması
 * (lib/gundem.ts) besliyor.
 *
 * Alt kategoriler: kaynak, yayincilik, gundem-konu, ekonomi-gundem,
 * teknoloji-gundem, spor-gundem, kultur-gundem, dunya, cevre, saglik-gundem
 */
export const haber: KategoriIcerigi = {
  kategori: "haber",
  listeler: [
    // ---- Kaynak ----
    { t: "En Güvenilir Haber Kaynakları", a: "kaynak",
      d: "Doğrulama ve tarafsızlık açısından öne çıkanlar.",
      m: ["Anadolu Ajansı", "BBC News Türkçe", "Reuters", "Associated Press", "T24", "Deutsche Welle Türkçe", "Bianet", "Medyascope", "AFP", "Euronews Türkçe"] },
    { t: "En İyi Haber Uygulamaları", a: "kaynak",
      d: "Mobilde gündem takibi.",
      m: ["Aposto", "NTV Haber", "Habertürk", "BBC News", "Google Haberler", "Apple News", "Feedly", "Flipboard", "Sözcü Mobil", "Anadolu Ajansı Mobil"] },
    { t: "En İyi Haber Bültenleri (Newsletter)", a: "kaynak",
      d: "E-postayla gelen özet bültenler.",
      m: ["Aposto", "Serbest Kürsü", "Fikir Turu Bülten", "Morning Brew", "The Hustle", "TLDR", "Webrazzi Bülten", "Substack Türkiye", "Axios AM", "The Daily Skimm"] },
    { t: "En İyi Yerel Haber Kaynakları", a: "kaynak",
      d: "Şehir ve bölge haberleri.",
      m: ["İstanbul Gazetesi", "Ege Telgraf", "Ankara Haber", "Bursa Hakimiyet", "Yeni Asır", "Antalya Körfez", "Trabzon Haber", "Adana Medya", "Konya Yenigün", "Gaziantep Pusula"] },
    { t: "En İyi Haber Ajansları", a: "kaynak",
      d: "Kaynak haber üreten ajanslar.",
      m: ["Anadolu Ajansı", "Demirören Haber Ajansı", "İhlas Haber Ajansı", "Reuters", "Associated Press", "AFP", "Bloomberg", "TASS", "Xinhua", "EFE"] },
    { t: "En İyi Veri Gazeteciliği Projeleri", a: "kaynak",
      d: "Veriyle habercilik yapan yayınlar.",
      m: ["Doğruluk Payı", "Teyit Veri", "The Pudding", "FiveThirtyEight", "Our World in Data", "Reuters Graphics", "NYT The Upshot", "Financial Times Visual", "Bloomberg Graphics", "Veri Kaynağı"] },

    // ---- Yayıncılık ----
    { t: "En Sevilen Haber Sunucuları", a: "yayincilik",
      d: "Ekranda güven veren isimler.",
      m: ["Fatih Portakal", "Uğur Dündar", "Ece Üner", "Cüneyt Özdemir", "İsmail Küçükkaya", "Nevşin Mengü", "Ahmet Hakan", "Selçuk Tepeli", "Ruşen Çakır", "Banu Güven"] },
    { t: "En İyi Haber Programları", a: "yayincilik",
      d: "Analiz ve tartışma programları.",
      m: ["40 Dakika", "Ne Oluyor", "Medya Mahallesi", "Özel Rapor", "Gündem Özel", "Eğrisi Doğrusu", "Serbest Bölge", "Karar Verme Zamanı", "Söz Sende", "Türkiye'nin Nabzı"] },
    { t: "En İyi Belgesel Kanalları", a: "yayincilik",
      d: "Belgesel içerikleriyle öne çıkan kanallar.",
      m: ["TRT Belgesel", "National Geographic", "Discovery Channel", "BBC Earth", "History Channel", "DMAX", "Animal Planet", "NatGeo Wild", "Arte", "PBS"] },
    { t: "En İyi Radyo Kanalları", a: "yayincilik",
      d: "Müzik ve haber radyoları.",
      m: ["Açık Radyo", "TRT Radyo 3", "Radyo Eksen", "Power FM", "Metro FM", "Radyo Voyage", "NTV Radyo", "TRT FM", "Kral FM", "Number One FM"] },
    { t: "En Etkili Gazeteciler", a: "yayincilik",
      d: "Habercilikte iz bırakan isimler.",
      m: ["Uğur Mumcu", "Abdi İpekçi", "Metin Toker", "Çetin Emeç", "Hrant Dink", "Nazlı Ilıcak", "Ruşen Çakır", "Can Dündar", "Ahmet Şık", "Yavuz Baydar"] },
    { t: "Medya Okuryazarlığı İçin Bilinmesi Gerekenler", a: "yayincilik",
      d: "Haberi doğru okumak için temel kavramlar.",
      m: ["Kaynak doğrulama", "Manipülatif başlık (clickbait)", "Yankı odası etkisi", "Doğrulama platformları", "Görsel manipülasyon", "Bağlam kopukluğu", "Anonim kaynak kullanımı", "Reklam-içerik ayrımı", "İstatistik okuma", "Derin sahte içerik"] },

    // ---- Gündem konuları ----
    { t: "Türkiye'nin En Çok Konuşulan Gündem Başlıkları", a: "gundem-konu",
      d: "Kamuoyunu meşgul eden kalıcı konular.",
      m: ["Enflasyon ve geçim", "Konut ve kira fiyatları", "Deprem hazırlığı", "Eğitim sistemi", "Sağlıkta erişim", "Ulaşım ve trafik", "İstihdam ve genç işsizlik", "Kentsel dönüşüm", "Enerji fiyatları", "Beyin göçü"] },
    { t: "Deprem Hazırlığı İçin Bilinmesi Gerekenler", a: "gundem-konu",
      d: "Bireysel ve toplumsal hazırlık başlıkları.",
      m: ["Bina dayanıklılık testi", "Deprem çantası", "Toplanma alanları", "Aile afet planı", "Zorunlu deprem sigortası (DASK)", "Eşya sabitleme", "Çök-kapan-tutun", "Yapı denetimi", "İlk yardım eğitimi", "Kentsel dönüşüm"] },
    { t: "Kentsel Dönüşümde En Çok Tartışılan Konular", a: "gundem-konu",
      d: "Süreçteki tartışma başlıkları.",
      m: ["Hak sahipliği", "Rezerv alan ilanı", "Kira yardımı", "Müteahhit seçimi", "Yapı denetimi", "Sosyal doku kaybı", "Değer artışı paylaşımı", "Riskli yapı tespiti", "Geçici konut", "İtiraz süreçleri"] },
    { t: "Trafik Sorununa Önerilen Çözümler", a: "gundem-konu",
      d: "Şehir içi ulaşım tartışmaları.",
      m: ["Raylı sistem yatırımı", "Bisiklet yolu ağı", "Yaya öncelikli tasarım", "Esnek mesai", "Araç paylaşımı", "Otopark yönetimi", "Toplu taşıma entegrasyonu", "Sıkışıklık ücreti", "Uzaktan çalışma", "Akıllı trafik sistemleri"] },
    { t: "Eğitim Sisteminde En Çok Tartışılan Başlıklar", a: "gundem-konu",
      d: "Öğrenci, veli ve öğretmenlerin gündemi.",
      m: ["Sınav sistemi", "Öğretmen atamaları", "Kalabalık sınıflar", "Özel ders ve kurs yükü", "Müfredat değişiklikleri", "Okul öncesi erişim", "Meslek liseleri", "Yabancı dil eğitimi", "Dijital eğitim altyapısı", "Öğretmen özlük hakları"] },
    { t: "Sağlık Sisteminde En Çok Konuşulan Konular", a: "gundem-konu",
      d: "Erişim ve hizmet kalitesi tartışmaları.",
      m: ["Randevu bulma", "Şehir hastaneleri", "Doktor göçü", "Aile hekimliği", "İlaç temini", "Tamamlayıcı sigorta", "Acil servis yoğunluğu", "Sağlıkta şiddet", "Koruyucu hekimlik", "Sağlık turizmi"] },
    { t: "Konut Krizine Önerilen Çözümler", a: "gundem-konu",
      d: "Kira ve satış fiyatları tartışması.",
      m: ["Sosyal konut üretimi", "Kira artış sınırı", "Boş konut vergisi", "Kentsel dönüşüm hızlandırma", "Arsa üretimi", "Konut kredisi düzenlemesi", "Kısa dönem kiralama denetimi", "İmar planı şeffaflığı", "Kooperatifçilik", "Toplu konut projeleri"] },

    // ---- Ekonomi gündemi ----
    { t: "Ekonomide En Çok Takip Edilen Göstergeler", a: "ekonomi-gundem",
      d: "Herkesin izlediği veri başlıkları.",
      m: ["Enflasyon (TÜFE)", "Politika faizi", "Dolar/TL kuru", "İşsizlik oranı", "Cari açık", "Asgari ücret", "Büyüme oranı (GSYH)", "Altın fiyatı", "Borsa İstanbul endeksi", "Konut fiyat endeksi"] },
    { t: "Enflasyonla Mücadelede Tartışılan Politikalar", a: "ekonomi-gundem",
      d: "Ekonomi tartışmalarının başlıkları.",
      m: ["Faiz politikası", "Kur istikrarı", "Gıda arz zinciri", "Rekabet denetimi", "Fiyat izleme", "Maliye politikası", "Ücret politikası", "Kamu harcamaları", "İthalat düzenlemeleri", "Beklenti yönetimi"] },
    { t: "Türkiye'nin En Büyük Şirketleri", a: "ekonomi-gundem",
      d: "Ciro ve istihdam büyüklüğüne göre.",
      m: ["Tüpraş", "Koç Holding", "Sabancı Holding", "Ford Otosan", "Türk Hava Yolları", "Aselsan", "BİM", "Arçelik", "Turkcell", "Şişecam"] },
    { t: "En Değerli Türk Markaları", a: "ekonomi-gundem",
      d: "Marka değeri araştırmalarına göre.",
      m: ["Turkcell", "Türk Hava Yolları", "Arçelik", "Ziraat Bankası", "BİM", "Beko", "Garanti BBVA", "İş Bankası", "Vestel", "LC Waikiki"] },
    { t: "Türkiye'nin En Başarılı Girişimleri", a: "ekonomi-gundem",
      d: "Yatırım alan ve büyüyen teknoloji girişimleri.",
      m: ["Getir", "Trendyol", "Peak Games", "Dream Games", "Insider", "Hepsiburada", "iyzico", "Papara", "Yemeksepeti", "Param"] },
    { t: "Yeni Nesil İş Modelleri", a: "ekonomi-gundem",
      d: "Son yıllarda öne çıkan modeller.",
      m: ["Abonelik ekonomisi", "Pazar yeri modeli", "Freemium", "Hızlı ticaret (q-commerce)", "Yaratıcı ekonomi", "Uzaktan çalışma", "Doğrudan tüketiciye satış", "Platform ekonomisi", "Döngüsel ekonomi", "Yapay zekâ destekli hizmetler"] },
    { t: "Girişimciler İçin En Önemli Konular", a: "ekonomi-gundem",
      d: "Kuruluş aşamasında dikkat edilecekler.",
      m: ["Ürün-pazar uyumu", "Nakit akışı yönetimi", "Kurucu ortaklık anlaşması", "Yatırımcı ilişkileri", "İlk 10 müşteri", "Hukuki yapı seçimi", "Fikri mülkiyet koruması", "Ekip kurma", "Fiyatlandırma", "Ölçeklenme zamanlaması"] },

    // ---- Teknoloji gündemi ----
    { t: "Teknolojide En Çok Konuşulan Konular", a: "teknoloji-gundem",
      d: "Sektörün gündemini belirleyen başlıklar.",
      m: ["Üretken yapay zekâ", "Veri gizliliği", "Yapay zekâ düzenlemesi", "Kripto düzenlemeleri", "Yarı iletken tedariki", "Uzay yarışı", "Elektrikli araçlar", "Siber güvenlik", "Sosyal medya bağımlılığı", "Dijital telif"] },
    { t: "Yapay Zekânın En Çok Etkilediği Meslekler", a: "teknoloji-gundem",
      d: "Dönüşümün en hızlı yaşandığı alanlar.",
      m: ["İçerik yazarlığı", "Müşteri hizmetleri", "Grafik tasarım", "Yazılım geliştirme", "Çevirmenlik", "Veri girişi", "Pazarlama analizi", "Hukuk asistanlığı", "Muhasebe", "Seslendirme"] },
    { t: "Veri Gizliliğinde Bilinmesi Gerekenler", a: "teknoloji-gundem",
      d: "Kişisel verinin korunması başlıkları.",
      m: ["KVKK hakları", "GDPR", "Çerez izinleri", "Veri sızıntısı bildirimi", "Uygulama izinleri", "Uçtan uca şifreleme", "Reklam takibi", "Konum verisi", "Biyometrik veri", "Veri silme hakkı"] },
    { t: "Uzay Alanındaki En Önemli Gelişmeler", a: "teknoloji-gundem",
      d: "Uzay araştırmalarında öne çıkan başlıklar.",
      m: ["Artemis programı", "SpaceX Starship", "James Webb Uzay Teleskobu", "Türksat uydu programı", "Mars görevleri", "Uydu internet ağları", "Uzay çöpü sorunu", "Ay madenciliği", "Uzay turizmi", "Türkiye Uzay Ajansı"] },
    { t: "Elektrikli Araç Dönüşümünde Tartışılan Konular", a: "teknoloji-gundem",
      d: "Geçiş sürecinin başlıkları.",
      m: ["Şarj altyapısı", "Batarya ömrü", "Menzil kaygısı", "Batarya geri dönüşümü", "Elektrik şebekesi kapasitesi", "Vergilendirme", "İkinci el değeri", "Yerli üretim", "Hammadde tedariki", "Hibrit alternatifi"] },
    { t: "Sosyal Medyanın En Çok Eleştirilen Yanları", a: "teknoloji-gundem",
      d: "Kullanıcı ve uzmanların ortak eleştirileri.",
      m: ["Algoritma bağımlılığı", "Yanlış bilgi yayılımı", "Mahremiyet ihlali", "Çocuk güvenliği", "Nefret söylemi", "Beden algısı etkisi", "Dikkat süresi", "Reklam yoğunluğu", "Yankı odası etkisi", "Veri madenciliği"] },

    // ---- Spor gündemi ----
    { t: "Türk Futbolunda En Çok Tartışılan Konular", a: "spor-gundem",
      d: "Sezon boyunca gündemden düşmeyen başlıklar.",
      m: ["Hakem kararları", "VAR uygulaması", "Yabancı sınırı", "Altyapı yatırımları", "Kulüp borçları", "Taraftar şiddeti", "Yayın gelirleri", "Teknik direktör değişiklikleri", "Transfer politikaları", "Milli takım performansı"] },
    { t: "En Büyük Spor Organizasyonları", a: "spor-gundem",
      d: "Dünyanın en çok izlenen turnuvaları.",
      m: ["FIFA Dünya Kupası", "Olimpiyat Oyunları", "UEFA Şampiyonlar Ligi", "EURO", "Super Bowl", "Formula 1 Dünya Şampiyonası", "Wimbledon", "Tour de France", "NBA Finalleri", "Dünya Atletizm Şampiyonası"] },
    { t: "Türkiye'nin En Büyük Spor Kulüpleri", a: "spor-gundem",
      d: "Taraftar sayısı ve başarı geçmişiyle.",
      m: ["Galatasaray", "Fenerbahçe", "Beşiktaş", "Trabzonspor", "Anadolu Efes", "Başakşehir", "Göztepe", "Bursaspor", "Sivasspor", "Konyaspor"] },
    { t: "E-Sporda En Popüler Oyunlar", a: "spor-gundem",
      d: "Turnuva ödülleri ve izlenmeyle.",
      m: ["League of Legends", "Counter-Strike 2", "Dota 2", "Valorant", "PUBG Mobile", "Rocket League", "Fortnite", "Overwatch 2", "Rainbow Six Siege", "EA FC"] },
    { t: "Sporda Sürdürülebilirlik Tartışmaları", a: "spor-gundem",
      d: "Büyük organizasyonların çevresel etkisi.",
      m: ["Stadyum enerji tüketimi", "Taraftar seyahat emisyonu", "Yeşil stadyum sertifikaları", "Kış olimpiyatları ve iklim", "Tek kullanımlık plastik", "Forma üretiminde geri dönüşüm", "Sponsorluk etiği", "Su tüketimi", "Atık yönetimi", "Karbon dengeleme"] },

    // ---- Kültür gündemi ----
    { t: "Kültür Sanatta En Çok Tartışılan Konular", a: "kultur-gundem",
      d: "Sanat dünyasının gündem başlıkları.",
      m: ["Sansür tartışmaları", "Sanata kamu desteği", "Telif hakları", "Yapay zekâ ve sanat", "Bienal ve festival bütçeleri", "Müze ziyaretçi sayıları", "Sanatçı hakları", "Kültürel miras koruma", "Dijital sanat", "Erişilebilir sanat"] },
    { t: "Türkiye'nin En Önemli Kültür Festivalleri", a: "kultur-gundem",
      d: "Yıllık düzenlenen büyük etkinlikler.",
      m: ["İstanbul Film Festivali", "İstanbul Bienali", "Antalya Altın Portakal", "İstanbul Caz Festivali", "Ankara Film Festivali", "Adana Altın Koza", "İstanbul Tiyatro Festivali", "Contemporary Istanbul", "Zeytinli Rock Festivali", "Uluslararası Ankara Müzik Festivali"] },
    { t: "En Çok Konuşulan Sinema Ödülleri", a: "kultur-gundem",
      d: "Takip edilen ödül törenleri.",
      m: ["Oscar", "Altın Küre", "Cannes Altın Palmiye", "Berlinale Altın Ayı", "Venedik Altın Aslan", "BAFTA", "Altın Portakal", "Altın Koza", "SAG Ödülleri", "Emmy"] },
    { t: "Kitap Dünyasının En Çok Tartışılan Konuları", a: "kultur-gundem",
      d: "Yayıncılık ve okuma kültürü.",
      m: ["Kitap fiyatları", "Korsan yayıncılık", "Çeviri kalitesi", "Sesli kitap yükselişi", "Yapay zekâ ile yazarlık", "Kütüphane bütçeleri", "Okuma alışkanlığı", "Bağımsız yayınevleri", "Kitap fuarları", "Telif sözleşmeleri"] },

    // ---- Dünya ----
    { t: "Dünya Gündeminin En Kalıcı Başlıkları", a: "dunya",
      d: "Uluslararası siyasette süregelen konular.",
      m: ["İklim müzakereleri", "Enerji güvenliği", "Göç ve mültecilik", "Ticaret savaşları", "Yapay zekâ düzenlemesi", "Gıda güvenliği", "Salgın hazırlığı", "Nükleer silahsızlanma", "Su kaynakları", "Küresel borç krizi"] },
    { t: "En Etkili Uluslararası Kuruluşlar", a: "dunya",
      d: "Küresel kararlarda söz sahibi kurumlar.",
      m: ["Birleşmiş Milletler", "NATO", "Avrupa Birliği", "Dünya Sağlık Örgütü", "IMF", "Dünya Bankası", "Dünya Ticaret Örgütü", "UNESCO", "UNICEF", "G20"] },
    { t: "Dünyanın En Yaşanabilir Şehirleri", a: "dunya",
      d: "Yaşam kalitesi endekslerine göre.",
      m: ["Viyana", "Kopenhag", "Zürih", "Melbourne", "Vancouver", "Cenevre", "Sydney", "Osaka", "Auckland", "Helsinki"] },
    { t: "En Çok Turist Çeken Ülkeler", a: "dunya",
      d: "Yıllık ziyaretçi sayısına göre.",
      m: ["Fransa", "İspanya", "ABD", "İtalya", "Türkiye", "Meksika", "Birleşik Krallık", "Almanya", "Yunanistan", "Tayland"] },
    { t: "Göç Konusunda En Çok Tartışılan Başlıklar", a: "dunya",
      d: "Küresel göç tartışmalarının eksenleri.",
      m: ["Sınır güvenliği", "Uyum politikaları", "İşgücü ihtiyacı", "Mülteci hakları", "Beyin göçü", "Vatandaşlık düzenlemeleri", "Yasa dışı geçişler", "Eğitim erişimi", "Barınma", "Kamuoyu algısı"] },

    // ---- Çevre ----
    { t: "İklim Krizinde En Kritik Başlıklar", a: "cevre",
      d: "Bilim insanlarının en çok uyardığı konular.",
      m: ["Küresel ısınma", "Deniz seviyesi yükselmesi", "Aşırı hava olayları", "Buzul erimesi", "Karbon emisyonu", "Ormansızlaşma", "Okyanus asitlenmesi", "Türlerin yok oluşu", "Kuraklık", "Karbon nötr hedefleri"] },
    { t: "Türkiye'nin En Önemli Çevre Sorunları", a: "cevre",
      d: "Ülke ölçeğinde öne çıkan başlıklar.",
      m: ["Su kıtlığı", "Orman yangınları", "Müsilaj", "Hava kirliliği", "Plastik atık", "Maden faaliyetleri", "Erozyon", "Deniz kirliliği", "Kentleşme baskısı", "Tarım alanı kaybı"] },
    { t: "En Etkili Yenilenebilir Enerji Kaynakları", a: "cevre",
      d: "Kurulu güç ve potansiyel açısından.",
      m: ["Güneş enerjisi", "Rüzgâr enerjisi", "Hidroelektrik", "Jeotermal", "Biyokütle", "Deniz dalga enerjisi", "Gelgit enerjisi", "Yeşil hidrojen", "Güneş termal", "Atıktan enerji"] },
    { t: "Sıfır Atık İçin Yapılabilecekler", a: "cevre",
      d: "Bireysel ve kurumsal adımlar.",
      m: ["Ayrıştırma yapmak", "Kompost", "Tek kullanımlık plastiği bırakmak", "Bez çanta kullanmak", "İkinci el tercih etmek", "Onarım kültürü", "Toplu alım", "Depozito sistemi", "Gıda israfını azaltmak", "Elektronik atık toplama"] },
    { t: "Su Kaynaklarının Korunması İçin Öneriler", a: "cevre",
      d: "Kuraklıkla mücadele başlıkları.",
      m: ["Damla sulama", "Şebeke kayıplarının azaltılması", "Gri su kullanımı", "Yağmur suyu hasadı", "Su tasarruflu armatürler", "Tarımda ürün deseni değişimi", "Sanayide su geri kazanımı", "Havza yönetimi", "Su fiyatlandırması", "Bilinçlendirme kampanyaları"] },

    // ---- Sağlık gündemi ----
    { t: "Halk Sağlığında En Kritik Konular", a: "saglik-gundem",
      d: "Toplum sağlığını en çok etkileyen başlıklar.",
      m: ["Obezite", "Sigara kullanımı", "Antibiyotik direnci", "Aşı tereddüdü", "Ruh sağlığı", "Hareketsizlik", "Hava kirliliği etkileri", "Gıda güvenliği", "Trafik kazaları", "Yaşlanan nüfus"] },
    { t: "En Çok Yanlış Bilinen Sağlık Bilgileri", a: "saglik-gundem",
      d: "Yaygın ama hatalı inanışlar.",
      m: ["Soğuk hava hastalık yapar", "Antibiyotik gribe iyi gelir", "Detoks kürleri gerekli", "Yağ tüketmek her zaman kötü", "Aşı otizm yapar", "Şeker hiperaktiflik yapar", "Kas yağa dönüşür", "Günde 8 bardak su şart", "Yumurta kolesterolü yükseltir", "Doğal olan her zaman güvenlidir"] },
    { t: "Sağlıklı Yaşlanma İçin En Önemli Faktörler", a: "saglik-gundem",
      d: "Uzun ömür araştırmalarının ortak bulguları.",
      m: ["Düzenli fiziksel aktivite", "Sosyal bağlar", "Dengeli beslenme", "Uyku düzeni", "Zihinsel aktivite", "Sigara kullanmamak", "Stres yönetimi", "Düzenli sağlık taraması", "Alkolü sınırlamak", "Amaç duygusu"] },
    { t: "Pandemiden Çıkarılan Dersler", a: "saglik-gundem",
      d: "Salgın sürecinin kalıcı etkileri.",
      m: ["Uzaktan çalışma dönüşümü", "Sağlık sistemi kapasitesi", "Aşı geliştirme hızı", "Tedarik zinciri kırılganlığı", "Dijital sağlık hizmetleri", "Bilgi kirliliğiyle mücadele", "Ruh sağlığı desteği", "Eğitimde dijitalleşme", "Küresel iş birliği", "Hazırlık planları"] },
    { t: "Ruh Sağlığında En Çok Konuşulan Başlıklar", a: "saglik-gundem",
      d: "Toplumda görünürlüğü artan konular.",
      m: ["Kaygı bozukluğu", "Tükenmişlik sendromu", "Depresyon", "Sosyal medya etkisi", "Terapiye erişim", "Damgalanma", "Çocuk ve ergen ruh sağlığı", "İş yerinde ruh sağlığı", "Uyku bozuklukları", "Dijital detoks"] },

    // ---- Kaynak (devam) ----
    { t: "En İyi Uluslararası Gazeteler", a: "kaynak",
      d: "Dünya basınının referans yayınları.",
      m: ["The New York Times", "The Guardian", "Financial Times", "Le Monde", "Der Spiegel", "The Washington Post", "El País", "The Economist", "Corriere della Sera", "Asahi Shimbun"] },
    { t: "En İyi Dergi ve Süreli Yayınlar", a: "kaynak",
      d: "Derinlemesine yazı ve dosya haberleri.",
      m: ["The Atlantic", "The New Yorker", "Wired", "National Geographic", "Bilim ve Teknik", "Atlas", "Cumhuriyet Bilim Teknoloji", "Foreign Affairs", "MIT Technology Review", "Harvard Business Review"] },
    { t: "En İyi Haber Arşivi ve Kütüphane Kaynakları", a: "kaynak",
      d: "Geçmiş haberlere erişim.",
      m: ["Milli Kütüphane Süreli Yayınlar", "Gazete Arşivi", "Internet Archive", "Hürriyet Arşiv", "Cumhuriyet Arşiv", "Wayback Machine", "TRT Arşiv", "Anadolu Ajansı Arşiv", "British Newspaper Archive", "ProQuest"] },
    { t: "En İyi Yorum ve Analiz Siteleri", a: "kaynak",
      d: "Haberin arkasındaki analizi verenler.",
      m: ["Fikir Turu", "Perspektif", "Serbestiyet", "Medyascope", "Daktilo1984", "T24 Yazarlar", "Karar Analiz", "Al Monitor", "Foreign Policy", "Project Syndicate"] },
    { t: "En İyi Şehircilik ve Kent Yayınları", a: "kaynak",
      d: "Kent, mimarlık ve planlama üzerine.",
      m: ["Arkitera", "XXI Mimarlık", "Mimarlık Dergisi", "Herkes İçin Mimarlık", "Kent Düşleri", "ArchDaily", "Dezeen", "CityLab", "Domus", "Betonart"] },

    // ---- Gündem konuları (devam) ----
    { t: "Tüketici Haklarında Bilinmesi Gerekenler", a: "tuketici",
      d: "Alışverişte hak arama başlıkları.",
      m: ["Cayma hakkı", "Ayıplı mal iadesi", "Garanti süresi", "Tüketici hakem heyeti", "Mesafeli satış sözleşmesi", "Fiyat etiketi uyuşmazlığı", "Kargo hasarı", "Abonelik iptali", "Kredi kartı itirazı", "Şikâyet süreçleri"] },
    { t: "En Çok Şikâyet Edilen Sektörler", a: "tuketici",
      d: "Tüketici şikâyetlerinin yoğunlaştığı alanlar.",
      m: ["E-ticaret", "Telekomünikasyon", "Bankacılık", "Kargo", "Beyaz eşya servisi", "Sigortacılık", "Turizm", "Otomotiv servisi", "Enerji faturaları", "Sağlık hizmetleri"] },
    { t: "Dolandırıcılıktan Korunmak İçin Bilinmesi Gerekenler", a: "tuketici",
      d: "Yaygın dolandırıcılık yöntemleri ve önlemler.",
      m: ["Oltalama (phishing) mesajları", "Sahte e-ticaret siteleri", "Yatırım vaatleri", "Kargo SMS'i dolandırıcılığı", "Sahte banka araması", "SIM kart kopyalama", "Kripto ponzi düzenleri", "Sahte iş ilanları", "Sosyal medya hesap ele geçirme", "Sahte fatura e-postaları"] },
    { t: "Dijital Haklar Konusunda Tartışılan Başlıklar", a: "gundem-konu",
      d: "İnternet kullanıcılarını ilgilendiren konular.",
      m: ["İfade özgürlüğü", "Erişim engelleri", "Veri yerelleştirme", "Unutulma hakkı", "Net tarafsızlığı", "Platform sorumluluğu", "Dijital telif", "Çevrimiçi anonimlik", "Algoritma şeffaflığı", "Çocukların çevrimiçi güvenliği"] },
    { t: "Gençlerin En Çok Konuştuğu Konular", a: "gundem-konu",
      d: "Genç kuşağın gündem başlıkları.",
      m: ["İş bulma", "Barınma", "Yurt dışına gitme", "Eğitim maliyetleri", "Sosyal medya baskısı", "İklim kaygısı", "Ruh sağlığı", "Ehliyet ve araç sahipliği", "Kariyer belirsizliği", "Yapay zekâ ve gelecek"] },
    { t: "Kadın Hakları Alanında Tartışılan Başlıklar", a: "gundem-konu",
      d: "Toplumsal cinsiyet eşitliği gündemi.",
      m: ["Ücret eşitsizliği", "İş gücüne katılım", "Şiddetle mücadele", "Bakım emeği", "Siyasi temsil", "Ebeveyn izni", "Cam tavan", "Güvenli ulaşım", "Eğitimde eşitlik", "Yönetim kurullarında temsil"] },
    { t: "Engelli Erişilebilirliğinde Öncelikli Konular", a: "gundem-konu",
      d: "Kamusal alanda erişim başlıkları.",
      m: ["Kaldırım ve rampa düzenlemesi", "Toplu taşıma erişimi", "İşaret dili hizmeti", "Web erişilebilirliği", "İstihdam kotası", "Eğitimde kaynaştırma", "Sesli betimleme", "Braille yayın", "Asansör ve yönlendirme", "Sağlık hizmetine erişim"] },
    { t: "Hayvan Hakları Alanında Tartışılan Konular", a: "gundem-konu",
      d: "Kamuoyunun gündemindeki başlıklar.",
      m: ["Sokak hayvanları politikası", "Kısırlaştırma programları", "Barınak koşulları", "Hayvan deneyleri", "Petshop satışları", "Hayvana şiddet cezaları", "Sahiplendirme", "Yaban hayatı koruma", "Endüstriyel hayvancılık", "Veteriner erişimi"] },

    // ---- Ekonomi gündemi (devam) ----
    { t: "Emeklilikte En Çok Merak Edilen Konular", a: "ekonomi-gundem",
      d: "Emeklilik sistemi başlıkları.",
      m: ["Prim gün sayısı", "EYT düzenlemesi", "Bireysel emeklilik (BES)", "Yaşlılık aylığı hesabı", "Yurt dışı borçlanması", "Askerlik borçlanması", "Kısmi emeklilik", "Emekli maaş zammı", "Toptan ödeme", "Sağlık hakları"] },
    { t: "Vergi Sisteminde Tartışılan Başlıklar", a: "ekonomi-gundem",
      d: "Vergi politikası tartışmaları.",
      m: ["Dolaylı vergi ağırlığı", "ÖTV oranları", "KDV indirimleri", "Kayıt dışı ekonomi", "Servet vergisi", "Vergi affı", "Kurumlar vergisi", "Asgari geçim indirimi", "Dijital hizmet vergisi", "Vergi adaleti"] },
    { t: "Türkiye'nin En Çok İhracat Yaptığı Sektörler", a: "ekonomi-gundem",
      d: "İhracat hacmine göre sektörler.",
      m: ["Otomotiv", "Hazır giyim ve konfeksiyon", "Kimyevi maddeler", "Çelik", "Elektrik-elektronik", "Makine", "Tarım ve gıda", "Mücevher", "Savunma sanayii", "Mobilya"] },
    { t: "Küçük İşletmelerin En Büyük Sorunları", a: "ekonomi-gundem",
      d: "KOBİ'lerin ortak zorlukları.",
      m: ["Nakit akışı", "Finansmana erişim", "Nitelikli personel bulma", "Kira maliyetleri", "Enerji giderleri", "Dijitalleşme", "Bürokrasi", "Tahsilat sorunları", "Rekabet baskısı", "Tedarik zinciri"] },

    // ---- Teknoloji gündemi (devam) ----
    { t: "Yapay Zekâ Düzenlemesinde Tartışılan Başlıklar", a: "teknoloji-gundem",
      d: "Yasal çerçeve arayışının konuları.",
      m: ["AB Yapay Zekâ Yasası", "Şeffaflık zorunluluğu", "Eğitim verisi telifi", "Yüksek riskli sistemler", "Yapay zekâ etiketlemesi", "Sorumluluk rejimi", "Biyometrik tanıma yasağı", "Açık kaynak modeller", "Ulusal yapay zekâ stratejisi", "Denetim mekanizmaları"] },
    { t: "Yarı İletken Sektöründe Öne Çıkan Konular", a: "teknoloji-gundem",
      d: "Çip üretimi ve tedarik başlıkları.",
      m: ["Çip tedarik krizi", "TSMC üretim kapasitesi", "ABD-Çin kısıtlamaları", "Avrupa Çip Yasası", "Yapay zekâ çipleri", "Litografi teknolojisi", "Nadir toprak elementleri", "Yerli çip üretimi", "Bellek fiyatları", "Enerji verimliliği"] },
    { t: "Siber Güvenlikte En Çok Konuşulan Olaylar", a: "teknoloji-gundem",
      d: "Sektörü şekillendiren saldırı türleri.",
      m: ["Fidye yazılımı saldırıları", "Tedarik zinciri açıkları", "Veri sızıntıları", "Devlet destekli saldırılar", "Kritik altyapı hedefleri", "Sıfırıncı gün açıkları", "Kimlik avı kampanyaları", "Bulut yapılandırma hataları", "IoT güvenliği", "Yapay zekâ destekli saldırılar"] },
    { t: "Oyun Sektöründe Tartışılan Konular", a: "teknoloji-gundem",
      d: "Oyuncuların ve sektörün gündemi.",
      m: ["Mikro ödemeler", "Ganimet sandığı düzenlemesi", "Erken erişim modeli", "Stüdyo kapanmaları", "Abonelik servisleri", "Oyun fiyatları", "Crunch kültürü", "Yapay zekâ ile içerik üretimi", "Oyun koruma ve DRM", "Bulut oyun servisleri"] },

    // ---- Kültür / spor / dünya (devam) ----
    { t: "Dizi ve Film Sektöründe Tartışılan Konular", a: "kultur-gundem",
      d: "Yapım dünyasının gündemi.",
      m: ["Platform yatırımları", "Dizi süreleri", "Set çalışma koşulları", "Yapay zekâ ve senaryo", "Telif ödemeleri", "Yurt dışı satışlar", "Sansür", "Reyting sistemi", "Sinema salonu doluluğu", "Bağımsız yapımlara destek"] },
    { t: "Müzik Sektöründe Tartışılan Konular", a: "kultur-gundem",
      d: "Sanatçı ve dinleyici gündemi.",
      m: ["Streaming telif gelirleri", "Konser bilet fiyatları", "Yapay zekâ ile üretilen müzik", "Bağımsız sanatçı dağıtımı", "Festival ekonomisi", "Telif takibi", "Fiziksel plak dönüşü", "Sosyal medya keşfi", "Sahne güvenliği", "Müzik eğitimi"] },
    { t: "Türkiye'nin Uluslararası Spor Başarıları", a: "spor-gundem",
      d: "Ülkeye madalya ve kupa getiren başarılar.",
      m: ["2002 Dünya Kupası üçüncülüğü", "EuroBasket 2001 ikinciliği", "Galatasaray UEFA Kupası 2000", "Naim Süleymanoğlu altınları", "Mete Gazoz okçuluk altını", "Milli Voleybol Filenin Sultanları", "2010 Dünya Basketbol ikinciliği", "Güreşte olimpiyat altınları", "Buse Naz Çakıroğlu boks", "Anadolu Efes EuroLeague şampiyonlukları"] },
    { t: "Kadın Sporunda Öne Çıkan Konular", a: "spor-gundem",
      d: "Görünürlük ve destek tartışmaları.",
      m: ["Yayın hakları", "Sponsorluk desteği", "Ücret eşitliği", "Altyapı yatırımı", "Medya görünürlüğü", "Filenin Sultanları başarısı", "Kadın futbol ligi", "Antrenör temsili", "Tesis erişimi", "Taraftar ilgisi"] },
    { t: "Dünyada En Çok Konuşulan Seçimler", a: "dunya",
      d: "Küresel etkisi olan seçim süreçleri.",
      m: ["ABD başkanlık seçimleri", "Avrupa Parlamentosu seçimleri", "Almanya federal seçimleri", "Fransa cumhurbaşkanlığı seçimi", "Birleşik Krallık genel seçimleri", "Hindistan genel seçimleri", "Brezilya genel seçimleri", "Japonya genel seçimleri", "Türkiye genel seçimleri", "Rusya başkanlık seçimi"] },
    { t: "Enerji Politikalarında Tartışılan Başlıklar", a: "dunya",
      d: "Küresel enerji gündemi.",
      m: ["Doğal gaz tedariki", "Nükleer enerji tartışması", "Yenilenebilir yatırımlar", "Petrol fiyatları", "Enerji verimliliği", "Elektrik şebekesi yatırımı", "Karbon vergisi", "Enerji yoksulluğu", "Depolama teknolojileri", "Yeşil hidrojen"] },

    // ---- Çevre / sağlık (devam) ----
    { t: "Orman Yangınlarıyla Mücadelede Öncelikler", a: "cevre",
      d: "Yangın sezonu hazırlığı başlıkları.",
      m: ["Erken uyarı sistemleri", "Hava aracı filosu", "Gönüllü itfaiye", "Yangın gözetleme kuleleri", "Yol ve su altyapısı", "Orman köylüsü desteği", "Cezai yaptırımlar", "Yeniden ağaçlandırma", "Anız yakma denetimi", "Halk bilinçlendirme"] },
    { t: "Gıda Güvenliğinde Tartışılan Konular", a: "cevre",
      d: "Tarladan sofraya süreç başlıkları.",
      m: ["Pestisit kalıntısı", "Etiket denetimi", "Taklit ve tağşiş", "Soğuk zincir", "GDO tartışması", "Yerel tohum", "Gıda israfı", "Tarım destekleri", "İthalat denetimi", "Sertifikasyon"] },
    { t: "Aşılamada En Çok Konuşulan Başlıklar", a: "saglik-gundem",
      d: "Aşı politikaları ve toplum sağlığı.",
      m: ["Çocukluk aşı takvimi", "Aşı tereddüdü", "Grip aşısı", "HPV aşısı", "Erişkin aşıları", "Aşı üretiminde yerlilik", "Soğuk zincir", "Sürü bağışıklığı", "Yan etki bildirimi", "Aşı bilgi kirliliği"] },
    { t: "Beslenmede En Çok Tartışılan Diyetler", a: "saglik-gundem",
      d: "Popüler beslenme yaklaşımları.",
      m: ["Akdeniz diyeti", "Aralıklı oruç", "Ketojenik diyet", "Vegan beslenme", "Düşük karbonhidrat", "DASH diyeti", "Bitki ağırlıklı beslenme", "Paleo diyet", "Karnivor diyet", "Sezgisel yeme"] },

    // ---- Hukuk ve şehir gündemi ----
    { t: "Vatandaşın En Çok Karşılaştığı Hukuki Konular", a: "hukuk-gundem",
      d: "Günlük hayatta en sık gündeme gelen başlıklar.",
      m: ["Kira sözleşmesi uyuşmazlıkları", "İş sözleşmesi feshi", "Kıdem ve ihbar tazminatı", "Trafik kazası tazminatı", "Miras paylaşımı", "Tüketici hakem heyeti", "Boşanma süreçleri", "Komşuluk hukuku", "İcra takibi", "Kişisel verilerin korunması"] },
    { t: "İş Hukukunda En Çok Merak Edilenler", a: "hukuk-gundem",
      d: "Çalışanların hak ve yükümlülükleri.",
      m: ["Fazla mesai ücreti", "Yıllık izin hakkı", "Kıdem tazminatı şartları", "İhbar süresi", "Mobbing", "İş kazası bildirimi", "Deneme süresi", "Uzaktan çalışma sözleşmesi", "Rekabet yasağı", "İşe iade davası"] },
    { t: "Şehirlerin En Büyük Sorunları", a: "sehir-gundem",
      d: "Büyükşehirlerde ortak yaşam sorunları.",
      m: ["Trafik sıkışıklığı", "Konut maliyeti", "Hava kirliliği", "Yeşil alan azlığı", "Otopark yetersizliği", "Gürültü kirliliği", "Altyapı yetersizliği", "Kaldırım işgali", "Toplu taşıma kalabalığı", "Su baskınları"] },
    { t: "Yaşanabilir Şehir İçin Öncelikli Adımlar", a: "sehir-gundem",
      d: "Şehir planlamasında öne çıkan öneriler.",
      m: ["15 dakikalık şehir yaklaşımı", "Yaya öncelikli sokaklar", "Bisiklet altyapısı", "Yeşil koridorlar", "Karma kullanımlı yapılaşma", "Erişilebilir toplu taşıma", "Kamusal alan yatırımı", "Yağmur suyu yönetimi", "Gürültü haritalaması", "Katılımcı bütçe"] },
    { t: "Türkiye'nin En Kalabalık Şehirleri", a: "sehir-gundem",
      d: "Nüfus büyüklüğüne göre sıralama.",
      m: ["İstanbul", "Ankara", "İzmir", "Bursa", "Antalya", "Konya", "Adana", "Şanlıurfa", "Gaziantep", "Kocaeli"] },
    { t: "En Hızlı Büyüyen Türkiye Şehirleri", a: "sehir-gundem",
      d: "Göç ve yatırımla büyüyen iller.",
      m: ["Antalya", "Tekirdağ", "Kocaeli", "Şanlıurfa", "Muğla", "Gaziantep", "Mersin", "Sakarya", "Balıkesir", "Aydın"] },

    // ---- Eğitim gündemi ----
    { t: "Üniversite Sınavında En Çok Tercih Edilen Bölümler", a: "egitim-gundem",
      d: "YKS tercih dönemi verilerine göre.",
      m: ["Tıp", "Hukuk", "Bilgisayar Mühendisliği", "Psikoloji", "İşletme", "Elektrik-Elektronik Mühendisliği", "Diş Hekimliği", "Endüstri Mühendisliği", "Hemşirelik", "Öğretmenlik"] },
    { t: "Geleceğin Meslekleri", a: "egitim-gundem",
      d: "Talebin artması beklenen alanlar.",
      m: ["Yapay zekâ mühendisi", "Veri bilimci", "Siber güvenlik uzmanı", "Yenilenebilir enerji mühendisi", "Biyoteknoloji uzmanı", "Robotik mühendisi", "İklim analisti", "Sağlık teknolojileri uzmanı", "Ürün yöneticisi", "İnsan-yapay zekâ etkileşim tasarımcısı"] },
    { t: "Öğretmenlerin En Çok Dile Getirdiği Sorunlar", a: "egitim-gundem",
      d: "Eğitimcilerin gündemi.",
      m: ["Kalabalık sınıflar", "Özlük hakları", "Atama bekleyen öğretmenler", "Evrak yükü", "Şiddet olayları", "Müfredat yoğunluğu", "Teknoloji altyapısı", "Zorunlu hizmet", "Mesleki gelişim imkânları", "Veli iletişimi"] },
    { t: "Ailelerin Eğitimde En Çok Merak Ettikleri", a: "egitim-gundem",
      d: "Veli gündeminin başlıkları.",
      m: ["Okul seçimi", "Ekran süresi", "Ödev takibi", "Sınav kaygısı", "Özel ders gereği", "Yabancı dil eğitimi", "Akran zorbalığı", "Beslenme çantası", "Servis güvenliği", "Meslek yönlendirmesi"] },

    // ---- Kaynak ve yayıncılık (son) ----
    { t: "En İyi Türkçe Bilim İletişimi Kanalları", a: "yayincilik",
      d: "Bilimi anlaşılır anlatan yayınlar.",
      m: ["Evrim Ağacı", "Ruhi Çenet", "Barış Özcan", "Sarkaç", "Herkese Bilim Teknoloji", "Açık Bilim", "Bilim Fili", "Bilim Sanal", "Popsci Türkiye", "Bilimsel Gerçekler"] },
    { t: "En İyi Belgesel Filmler", a: "yayincilik",
      d: "Konusu ve anlatımıyla öne çıkan belgeseller.",
      m: ["My Octopus Teacher", "Free Solo", "The Social Dilemma", "Icarus", "13th", "Seaspiracy", "Won't You Be My Neighbor?", "Man on Wire", "Amy", "Kedi"] },
    { t: "Habercilikte Etik Tartışmaları", a: "yayincilik",
      d: "Meslek etiğinin gündem başlıkları.",
      m: ["Mahremiyet ihlali", "Mağdur haberciliği", "Tıklama tuzağı başlıklar", "Kaynak gizliliği", "Reklam-haber ayrımı", "Nefret söylemi", "İntihar haberciliği", "Çocuk haberleri", "Yapay zekâ ile içerik üretimi", "Düzeltme ve tekzip"] },
  ],
};
