import type { KategoriIcerigi } from "./tipler";

/**
 * Hizmet kategorisi — 100+ liste.
 * Alt kategoriler: banka, odeme, kargo, operator, internet, sigorta,
 * saglik-hizmet, egitim-hizmet, ulasim, yemek-teslimat, konaklama-hizmet,
 * ev-hizmet, kurumsal, hukuk-finans, kamu, abonelik
 */
export const hizmet: KategoriIcerigi = {
  kategori: "hizmet",
  listeler: [
    // ---- Banka ----
    { t: "Türkiye'nin En İyi Bankaları", a: "banka",
      d: "Şube ağı, dijital deneyim ve müşteri memnuniyeti.",
      m: ["Garanti BBVA", "İş Bankası", "Yapı Kredi", "Akbank", "Ziraat Bankası", "QNB Finansbank", "Halkbank", "VakıfBank", "DenizBank", "TEB"] },
    { t: "En İyi Mobil Bankacılık Uygulamaları", a: "banka",
      d: "Kullanım kolaylığı ve özellik zenginliği.",
      m: ["Garanti BBVA Mobil", "İşCep", "Yapı Kredi Mobil", "Akbank Mobil", "Enpara Mobil", "QNB Mobil", "DenizBank MobilDeniz", "ON Dijital Bankacılık", "Ziraat Mobil", "TEB CEPTETEB"] },
    { t: "En İyi Dijital Bankalar", a: "banka",
      d: "Şubesiz bankacılık deneyimi.",
      m: ["Enpara.com", "ON Dijital Bankacılık", "CEPTETEB", "Papara", "İninal", "Tosla", "Colendi Bank", "Getir Finans", "Fups", "Moka"] },
    { t: "En İyi Kredi Kartları", a: "banka",
      d: "Puan, taksit ve avantaj programları.",
      m: ["Bonus Card", "World Card", "Maximum Card", "Axess", "Paraf", "CardFinans", "Miles&Smiles Card", "Bankkart Combo", "Advantage Card", "Wings Card"] },
    { t: "En İyi Konut Kredisi Veren Bankalar", a: "banka",
      d: "Faiz oranı ve süreç hızı.",
      m: ["Ziraat Bankası", "Halkbank", "VakıfBank", "Garanti BBVA", "İş Bankası", "Yapı Kredi", "Akbank", "QNB Finansbank", "DenizBank", "TEB"] },
    { t: "En İyi Katılım Bankaları", a: "banka",
      d: "Faizsiz bankacılık hizmeti verenler.",
      m: ["Kuveyt Türk", "Albaraka Türk", "Türkiye Finans", "Ziraat Katılım", "Vakıf Katılım", "Emlak Katılım", "Hayat Finans", "Dünya Katılım", "Golden Global", "Türk Katılım"] },

    // ---- Ödeme ----
    { t: "En İyi Ödeme ve Cüzdan Uygulamaları", a: "odeme",
      d: "Para transferi ve dijital cüzdan hizmetleri.",
      m: ["Papara", "Tosla", "İninal", "Paycell", "BiP Pay", "Ozan", "Wise", "PayPal", "Param", "Getir Finans"] },
    { t: "En İyi Sanal POS ve Ödeme Altyapıları", a: "odeme",
      d: "E-ticaret siteleri için ödeme çözümleri.",
      m: ["iyzico", "PayTR", "Param", "Stripe", "Sipay", "Moka United", "Craftgate", "PayU Türkiye", "Vallet", "Shopier"] },
    { t: "En İyi Yurt Dışı Para Transferi Servisleri", a: "odeme",
      d: "Düşük komisyon ve hızlı transfer.",
      m: ["Wise", "Revolut", "Western Union", "MoneyGram", "PayPal", "Remitly", "Ria Money Transfer", "Payoneer", "Skrill", "Xoom"] },
    { t: "En İyi Kripto Para Borsaları", a: "odeme",
      d: "Türkiye'den erişilebilen borsalar.",
      m: ["Binance TR", "BtcTurk", "Paribu", "Bitexen", "OKX", "Coinbase", "Bybit", "ICRYPEX", "Bitci", "KuCoin"] },

    // ---- Kargo ----
    { t: "Türkiye'nin En İyi Kargo Firmaları", a: "kargo",
      d: "Teslimat süresi ve hasarsız ulaştırma.",
      m: ["Yurtiçi Kargo", "Aras Kargo", "MNG Kargo", "PTT Kargo", "Sürat Kargo", "UPS Türkiye", "DHL Türkiye", "Trendyol Express", "Hepsijet", "Sendeo"] },
    { t: "En İyi Uluslararası Kargo Firmaları", a: "kargo",
      d: "Yurt dışı gönderim ve gümrük süreçleri.",
      m: ["DHL Express", "UPS", "FedEx", "TNT", "PTT Uluslararası", "Aramex", "GLS", "DPD", "Kargom Sende", "ShipEntegra"] },
    { t: "En İyi Hızlı Teslimat Servisleri", a: "kargo",
      d: "Aynı gün ve saatlik teslimat.",
      m: ["Getir", "Yemeksepeti Mahalle", "Migros Yemek", "Trendyol Hızlı Market", "Hepsiburada Ekspres", "İstegelsin", "A101 Kapında", "ŞOK Hızlı", "Getir Büyük", "Banabi"] },
    { t: "En İyi Kargo Takip Uygulamaları", a: "kargo",
      d: "Tüm kargolarını tek yerden takip et.",
      m: ["Kargom Nerede", "Kolay Kargo Takip", "Parcels", "AfterShip", "17TRACK", "Yurtiçi Kargo Mobil", "Aras Kargo Mobil", "MNG Mobil", "PTT Mobil", "Trendyol Kargo Takip"] },

    // ---- Operatör / internet ----
    { t: "Türkiye'nin En İyi GSM Operatörleri", a: "operator",
      d: "Kapsama alanı, hız ve müşteri hizmetleri.",
      m: ["Turkcell", "Vodafone Türkiye", "Türk Telekom", "Pttcell", "BiP Mobil", "Vodafone Kolay Paket", "Turkcell Prepaid", "Türk Telekom Prime", "Netgsm", "Mobilus"] },
    { t: "En İyi İnternet Servis Sağlayıcıları", a: "internet",
      d: "Fiber hız, kesinti ve destek dengesi.",
      m: ["Türk Telekom", "Superonline", "Vodafone Net", "TurkNet", "Millenicom", "D-Smart Net", "Netspeed", "Kablonet", "Doping", "Netmax"] },
    { t: "En İyi Mobil İnternet Paketleri", a: "operator",
      d: "GB başına maliyet ve ek avantajlar.",
      m: ["Turkcell Platinum", "Vodafone Red", "Türk Telekom Selfy", "Turkcell GNÇ", "Vodafone FreeZone", "Türk Telekom Prime", "Turkcell Hepsi Bir Arada", "Vodafone Uyumlu", "Pttcell Paket", "Türk Telekom Sınırsız"] },
    { t: "En İyi VPN Servisleri", a: "internet",
      d: "Gizlilik, hız ve sunucu ağı.",
      m: ["NordVPN", "ExpressVPN", "Surfshark", "ProtonVPN", "Mullvad", "CyberGhost", "Private Internet Access", "Windscribe", "IPVanish", "Hide.me"] },
    { t: "En İyi Bulut Depolama Hizmetleri", a: "internet",
      d: "Ücretsiz alan ve senkronizasyon kalitesi.",
      m: ["Google Drive", "iCloud", "Dropbox", "OneDrive", "pCloud", "Proton Drive", "Mega", "Sync.com", "Box", "Yandex Disk"] },

    // ---- Sigorta ----
    { t: "En İyi Sigorta Şirketleri", a: "sigorta",
      d: "Hasar ödeme hızı ve poliçe çeşitliliği.",
      m: ["Anadolu Sigorta", "Allianz Türkiye", "Axa Sigorta", "Sompo Sigorta", "HDI Sigorta", "Mapfre Sigorta", "Ak Sigorta", "Zurich Sigorta", "Türkiye Sigorta", "Groupama"] },
    { t: "En İyi Sağlık Sigortası Sunanlar", a: "sigorta",
      d: "Anlaşmalı kurum ağı ve kapsam.",
      m: ["Allianz Sağlık", "Anadolu Sigorta Sağlık", "Axa Sağlık", "Acıbadem Sigorta", "Mapfre Sağlık", "Türkiye Sigorta Sağlık", "Groupama Sağlık", "Ak Sigorta Sağlık", "Sompo Sağlık", "HDI Sağlık"] },
    { t: "En İyi Kasko Sunan Şirketler", a: "sigorta",
      d: "Prim, muafiyet ve servis ağı.",
      m: ["Anadolu Sigorta Kasko", "Allianz Kasko", "Axa Kasko", "Sompo Kasko", "Ak Sigorta Kasko", "HDI Kasko", "Mapfre Kasko", "Türkiye Sigorta Kasko", "Zurich Kasko", "Doga Sigorta"] },
    { t: "En İyi Sigorta Karşılaştırma Siteleri", a: "sigorta",
      d: "Poliçe fiyatlarını tek yerden görme.",
      m: ["Sigortam.net", "Koalay", "HesapKurdu", "Sigortadenizi", "Tamamlayıcı.com", "PoliçeBul", "Sigortacım", "Neosigorta", "Sigorta Bul", "Anında Sigorta"] },
    { t: "En İyi Bireysel Emeklilik (BES) Şirketleri", a: "sigorta",
      d: "Fon getirisi ve kesinti oranları.",
      m: ["Anadolu Hayat Emeklilik", "Allianz Yaşam ve Emeklilik", "Garanti BBVA Emeklilik", "Ak Emeklilik", "Aegon Emeklilik", "Fiba Emeklilik", "NN Hayat Emeklilik", "Metlife Emeklilik", "Vakıf Emeklilik", "Ziraat Hayat Emeklilik"] },

    // ---- Sağlık hizmeti ----
    { t: "Türkiye'nin En İyi Özel Hastaneleri", a: "saglik-hizmet",
      d: "Uzman kadro ve teknoloji altyapısı.",
      m: ["Acıbadem Hastanesi", "Memorial Hastanesi", "Medical Park", "Amerikan Hastanesi", "Florence Nightingale", "Liv Hospital", "Medicana", "Anadolu Sağlık Merkezi", "Bayındır Hastanesi", "Koç Üniversitesi Hastanesi"] },
    { t: "En İyi Online Doktor ve Sağlık Uygulamaları", a: "saglik-hizmet",
      d: "Uzaktan görüşme ve randevu.",
      m: ["e-Nabız", "MHRS", "Doktorsitesi", "Doktortakvimi", "Medicana Online", "Acıbadem Mobil", "Memorial Online", "Vitalis", "Doktorum Yanımda", "Hekimce"] },
    { t: "En İyi Diş Kliniği Zincirleri", a: "saglik-hizmet",
      d: "Ağız ve diş sağlığı hizmeti verenler.",
      m: ["Dentakay", "Dentgroup", "Estetik International Diş", "Dentapark", "Medicadent", "Dentalpark", "Dentram", "Dent Bahar", "Vera Diş", "Diş Doktorum"] },
    { t: "En İyi Eczane Zincirleri ve Uygulamaları", a: "saglik-hizmet",
      d: "İlaç bulunabilirliği ve teslimat.",
      m: ["Nöbetçi Eczane", "e-Nabız İlaç", "Eczane Bul", "Rossmann", "Watsons", "Gratis Sağlık", "İlaçlarım", "Eczanem Nerede", "Tıpta Eczane", "Farmasi Sağlık"] },
    { t: "En İyi Psikolojik Destek Platformları", a: "saglik-hizmet",
      d: "Online terapi ve danışmanlık.",
      m: ["Hiwell", "Terappin", "Psikolojik Danışman", "Wellbees", "Meditopia", "BetterHelp", "MindDoc", "Psikolog.com", "Terapi Yanımda", "Zihin Sağlığı Platformu"] },

    // ---- Eğitim hizmeti ----
    { t: "En İyi Özel Üniversiteler", a: "egitim-hizmet",
      d: "Akademik kadro ve mezun istihdamı.",
      m: ["Koç Üniversitesi", "Sabancı Üniversitesi", "Bilkent Üniversitesi", "Özyeğin Üniversitesi", "TOBB ETÜ", "Bahçeşehir Üniversitesi", "Yeditepe Üniversitesi", "Kadir Has Üniversitesi", "İstanbul Bilgi Üniversitesi", "Işık Üniversitesi"] },
    { t: "En İyi Devlet Üniversiteleri", a: "egitim-hizmet",
      d: "Araştırma ve tercih sıralamasıyla.",
      m: ["Boğaziçi Üniversitesi", "ODTÜ", "İstanbul Teknik Üniversitesi", "Hacettepe Üniversitesi", "Ankara Üniversitesi", "İstanbul Üniversitesi", "Ege Üniversitesi", "Gazi Üniversitesi", "Yıldız Teknik Üniversitesi", "Dokuz Eylül Üniversitesi"] },
    { t: "En İyi Yazılım Bootcamp'leri", a: "egitim-hizmet",
      d: "Kariyer değişimi için yoğun programlar.",
      m: ["Patika.dev", "Techcareer.net Bootcamp", "Kodluyoruz", "Wissen Akademi", "Istanbul Coding School", "Bilge Adam", "Techpro Education", "Akbank Bootcamp", "Turkcell Geleceği Yazanlar", "Google Developer Bootcamp"] },
    { t: "En İyi Dil Kursları ve Uygulamaları", a: "egitim-hizmet",
      d: "Yabancı dil öğrenmek için.",
      m: ["Duolingo", "Cambly", "italki", "Busuu", "Preply", "Babbel", "Rosetta Stone", "American Life", "Wall Street English", "British Council"] },
    { t: "En İyi Sınav Hazırlık Kurumları", a: "egitim-hizmet",
      d: "YKS, LGS ve KPSS hazırlığı.",
      m: ["Bilfen", "Final Dergisi Dershaneleri", "Doğa Koleji", "FEM Dershaneleri", "Sınav Koleji", "Uğur Okulları", "Tonguç Akademi", "Hız ve Renk", "3D Yayınları", "Karekök Eğitim"] },
    { t: "En İyi Anaokulu ve Kreş Zincirleri", a: "egitim-hizmet",
      d: "Erken çocukluk eğitimi kurumları.",
      m: ["Bahçeşehir Koleji Anaokulu", "Doğa Koleji Anaokulu", "Uğur Okulları Anaokulu", "Little Star", "Mutlu Çocuk", "Bilfen Anaokulu", "Yıldız Kreş", "Çocuk Bahçesi", "Montessori Türkiye", "Kanguru Kreş"] },

    // ---- Ulaşım ----
    { t: "En İyi Havayolu Şirketleri", a: "ulasim",
      d: "Türkiye'den uçan havayollarının karşılaştırması.",
      m: ["Türk Hava Yolları", "Pegasus", "AnadoluJet", "SunExpress", "Emirates", "Lufthansa", "Qatar Airways", "Corendon Airlines", "Freebird Airlines", "Onur Air"] },
    { t: "En İyi Otobüs Firmaları", a: "ulasim",
      d: "Şehirler arası yolculukta konfor ve dakiklik.",
      m: ["Metro Turizm", "Kamil Koç", "Pamukkale Turizm", "Ulusoy", "Varan Turizm", "Nilüfer Turizm", "Süha Turizm", "Lüks Karadeniz", "Efe Tur", "Ben Turizm"] },
    { t: "En İyi Araç Kiralama Şirketleri", a: "ulasim",
      d: "Filo çeşitliliği ve fiyat şeffaflığı.",
      m: ["Garenta", "Avis Türkiye", "Enterprise", "Budget", "Sixt", "Hertz", "Europcar", "Yolcu360", "Circular", "DRD Araç Kiralama"] },
    { t: "En İyi Taksi ve Ulaşım Uygulamaları", a: "ulasim",
      d: "Şehir içi ulaşımda kullanılan uygulamalar.",
      m: ["BiTaksi", "iTaksi", "Uber Türkiye", "Martı", "Marti TAG", "Moovit", "Trafi", "İBB CepTrafik", "Mobiett", "Taksim Taksi"] },
    { t: "En İyi Bilet Alma Platformları", a: "ulasim",
      d: "Uçak, otobüs ve tren bileti.",
      m: ["Enuygun", "obilet", "Biletall", "Turna.com", "Skyscanner", "Trip.com", "TCDD Taşımacılık", "Neredennereye", "Ucuzabilet", "Kayak"] },
    { t: "En İyi Elektrikli Scooter Paylaşım Servisleri", a: "ulasim",
      d: "Kısa mesafe şehir içi ulaşım.",
      m: ["Martı", "BinBin", "Hop", "Palm Mobility", "Scooby", "Tık Tık", "Mobo", "Zubby", "Voi", "Bolt Scooter"] },

    // ---- Yemek teslimat ----
    { t: "En İyi Yemek Sipariş Platformları", a: "yemek-teslimat",
      d: "Restoran çeşitliliği ve teslimat süresi.",
      m: ["Yemeksepeti", "Getir Yemek", "Trendyol Yemek", "Migros Yemek", "Tıkla Gelsin", "Fuudy", "Vigo", "Yemek.com Sipariş", "Bitaksi Yemek", "Sepette"] },
    { t: "En İyi Online Market Servisleri", a: "yemek-teslimat",
      d: "Hızlı market alışverişi.",
      m: ["Getir", "Migros Sanal Market", "Trendyol Hızlı Market", "İstegelsin", "A101 Kapıda", "CarrefourSA Online", "ŞOK Market Online", "Banabi", "Hepsiburada Market", "Macrocenter Online"] },
    { t: "En İyi Yemek Kartı ve Yemek Çeki Firmaları", a: "yemek-teslimat",
      d: "Çalışanlara sunulan yemek kartları.",
      m: ["Multinet", "Sodexo", "SetCard", "Ticket Restaurant", "Metropol Card", "Paye Kart", "Winwin Card", "İş Yemek", "Vale Kart", "Smart Card"] },
    { t: "En İyi Hazır Yemek ve Diyet Paketi Servisleri", a: "yemek-teslimat",
      d: "Haftalık menü teslimatı yapan servisler.",
      m: ["Fit Kolay", "Diyet Mutfağı", "Yemek Kutusu", "Hazır Yemek Sepeti", "Fit Chef", "Balance Kitchen", "Diyetkolik Mutfak", "Meal Box", "Sağlıklı Mutfak", "Nutrition Box"] },

    // ---- Konaklama hizmeti ----
    { t: "En İyi Otel Rezervasyon Siteleri", a: "konaklama-hizmet",
      d: "Fiyat karşılaştırma ve iptal koşulları.",
      m: ["Booking.com", "Otelz", "Tatilbudur", "Jolly Tur", "Setur", "ETS Tur", "Airbnb", "Expedia", "Hotels.com", "Trivago"] },
    { t: "En İyi Tatil ve Tur Şirketleri", a: "konaklama-hizmet",
      d: "Paket tur ve organizasyon.",
      m: ["Jolly Tur", "ETS Tur", "Setur", "Tatilbudur", "Anex Tour", "Coral Travel", "TUI Türkiye", "Prontotour", "Mng Turizm", "Odeon Tours"] },
    { t: "En İyi Kısa Dönem Kiralama Platformları", a: "konaklama-hizmet",
      d: "Ev ve daire kiralama.",
      m: ["Airbnb", "Booking.com Apartman", "Tatil Sepeti", "Vrbo", "Evimiz Kiralık", "Hoteltus", "Tatilim Ev", "Yazlıkçım", "Villa Kirala", "Ev Kirala"] },
    { t: "En İyi Kamp ve Karavan Rezervasyon Servisleri", a: "konaklama-hizmet",
      d: "Kamp alanı ve karavan kiralama.",
      m: ["Kampvan", "Karavanistan", "Kampyeri", "Roadsurfer", "Kamp Rehberi", "Doğa Kamp", "Karavan Kirala", "CampSpot", "Kamp Yeri Bul", "Nomad Karavan"] },

    // ---- Ev hizmetleri ----
    { t: "En İyi Ev Temizlik Hizmetleri", a: "ev-hizmet",
      d: "Saatlik ve düzenli temizlik servisleri.",
      m: ["Armut", "Hizmetim Var", "Temizlikçim", "Temizlik Şirketim", "Evim Temiz", "Hizmetle", "İşin Ustası", "Kolay Temizlik", "Temizlik Bul", "Ev Hizmet"] },
    { t: "En İyi Usta ve Tadilat Platformları", a: "ev-hizmet",
      d: "Tesisatçı, elektrikçi ve boyacı bulma.",
      m: ["Armut", "Hizmetim Var", "İşin Ustası", "Usta Bul", "Tamirci Bul", "Boyacı Bul", "Tadilat Sepeti", "Ev Tadilat", "Ustam Yanımda", "Hizmet Al"] },
    { t: "En İyi Nakliyat ve Evden Eve Taşıma Firmaları", a: "ev-hizmet",
      d: "Sigortalı ve paketlemeli taşıma.",
      m: ["Evden Eve Nakliyat", "Taşıma.com", "Nakliyat.com", "Ekol Nakliyat", "Marmara Nakliyat", "Star Nakliyat", "Vira Nakliyat", "Anadolu Nakliyat", "Ege Nakliyat", "Cargo Nakliyat"] },
    { t: "En İyi Emlak Platformları", a: "ev-hizmet",
      d: "Konut alım, satım ve kiralama siteleri.",
      m: ["Sahibinden.com", "Hepsiemlak", "Emlakjet", "Zingat", "Remax Türkiye", "Coldwell Banker Türkiye", "Century 21 Türkiye", "Emlak Kulisi", "Turyap", "Emlak Katılım"] },
    { t: "En İyi Bahçe ve Peyzaj Hizmetleri", a: "ev-hizmet",
      d: "Bahçe bakımı ve düzenleme.",
      m: ["Armut Peyzaj", "Bahçıvan Bul", "Peyzaj Ustası", "Yeşil Bahçe", "Bahçem Bakımlı", "Landscape Türkiye", "Bahçe Tasarım", "Peyzaj Market", "Çim Bakım", "Bahçe Hizmet"] },

    // ---- Kurumsal ----
    { t: "En İyi Muhasebe ve Ön Muhasebe Programları", a: "kurumsal",
      d: "KOBİ'ler için finansal takip yazılımları.",
      m: ["Paraşüt", "Logo İşbaşı", "Mikro Yazılım", "Bizim Hesap", "Uyumsoft", "Nebim", "Netsis", "Zirve Yazılım", "e-Fatura Merkezi", "Odoo Türkiye"] },
    { t: "En İyi İnsan Kaynakları Yazılımları", a: "kurumsal",
      d: "İK süreçlerini dijitalleştiren araçlar.",
      m: ["Kolay İK", "BordroPlus", "Zenployee", "PeopleHR", "Logo İK", "Personio", "BambooHR", "HRWEB", "İK Bulut", "Workday"] },
    { t: "En İyi E-Fatura Entegratörleri", a: "kurumsal",
      d: "e-Fatura ve e-Arşiv hizmeti sağlayanlar.",
      m: ["Paraşüt", "Uyumsoft", "Logo e-Fatura", "Mikro e-Fatura", "İzibiz", "Foriba", "Digital Planet", "e-Finans", "Turkcell e-Şirket", "İdea e-Dönüşüm"] },
    { t: "En İyi Kurumsal Kaynak Planlama (ERP) Sistemleri", a: "kurumsal",
      d: "Orta ve büyük ölçekli işletmeler için.",
      m: ["SAP", "Logo Tiger", "Netsis", "Microsoft Dynamics 365", "Oracle NetSuite", "Odoo", "Nebim V3", "Mikro Fly", "IFS", "Sentez ERP"] },
    { t: "En İyi Danışmanlık Şirketleri", a: "kurumsal",
      d: "Strateji ve yönetim danışmanlığı.",
      m: ["McKinsey & Company", "Boston Consulting Group", "Bain & Company", "Deloitte Türkiye", "PwC Türkiye", "EY Türkiye", "KPMG Türkiye", "Accenture Türkiye", "Roland Berger", "Kearney"] },
    { t: "En İyi Dijital Ajanslar", a: "kurumsal",
      d: "Reklam, sosyal medya ve performans pazarlama.",
      m: ["Wanda Digital", "Reklamüstü", "TBWA İstanbul", "Rafineri", "C-Section", "Manajans", "Mediacom Türkiye", "Publicis Türkiye", "Ogilvy Türkiye", "Grey İstanbul"] },
    { t: "En İyi Freelance Platformları", a: "kurumsal",
      d: "Serbest çalışan ve işveren buluşturan siteler.",
      m: ["Upwork", "Fiverr", "Bionluk", "Armut", "Freelancer.com", "Toptal", "Guru", "PeoplePerHour", "Malt", "99designs"] },
    { t: "En İyi İş İlanı Siteleri", a: "kurumsal",
      d: "İş arayanlar ve işverenler için.",
      m: ["Kariyer.net", "LinkedIn", "Yenibiris.com", "Secretcv", "Eleman.net", "İşkur", "Techcareer.net", "Glassdoor", "Indeed Türkiye", "Toptalent"] },

    // ---- Hukuk / finans hizmeti ----
    { t: "En İyi Hukuk Danışmanlık Platformları", a: "hukuk-finans",
      d: "Avukat bulma ve online danışmanlık.",
      m: ["Avukatım Yanımda", "Hukuk Bul", "Adalet Bakanlığı UYAP", "Barobirlik Avukat Arama", "Hukuki Destek", "Avukat Ara", "Legal Bul", "Danışman Avukat", "Hukuk Rehberi", "Avukatlık Bürosu Bul"] },
    { t: "En İyi Kredi Karşılaştırma Siteleri", a: "hukuk-finans",
      d: "Faiz oranlarını tek yerden görmek için.",
      m: ["HesapKurdu", "Enpara Kredi", "Kredimi Al", "Hangikredi", "Kredi Bul", "Faizsiz Kredi", "Encazip Finans", "Bankalar.org", "Kredi Rehberi", "Kredi Notu"] },
    { t: "En İyi Yatırım ve Aracı Kurumlar", a: "hukuk-finans",
      d: "Borsa işlemleri için aracı kurumlar.",
      m: ["Midas", "İş Yatırım", "Garanti BBVA Yatırım", "Ak Yatırım", "Gedik Yatırım", "Ziraat Yatırım", "QNB Finans Yatırım", "Yapı Kredi Yatırım", "Deniz Yatırım", "Tera Yatırım"] },
    { t: "En İyi Finansal Takip Uygulamaları", a: "hukuk-finans",
      d: "Portföy ve piyasa takibi.",
      m: ["Fintables", "Midas", "Investing.com", "TradingView", "Bloomberg HT", "Foreks", "Matriks", "Paraşüt Finans", "Portföyüm", "BigPara"] },

    // ---- Kamu ----
    { t: "En Çok Kullanılan e-Devlet Hizmetleri", a: "kamu",
      d: "Vatandaşların en sık ihtiyaç duyduğu işlemler.",
      m: ["Adli sicil kaydı", "Nüfus kayıt örneği", "İkametgâh belgesi", "SGK hizmet dökümü", "Vergi borcu sorgulama", "Trafik cezası sorgulama", "Askerlik durum belgesi", "Öğrenci belgesi", "Tapu bilgileri", "e-İmza başvurusu"] },
    { t: "En İyi Kamu Mobil Uygulamaları", a: "kamu",
      d: "Devletin sunduğu mobil hizmetler.",
      m: ["e-Devlet Kapısı", "e-Nabız", "MHRS", "HGS Mobil", "İBB CepTrafik", "PTT Mobil", "Vergi Dairesi Mobil (GİB)", "AFAD Acil Çağrı", "Meteoroloji", "İçişleri Bakanlığı Mobil"] },
    { t: "En İyi Belediye Hizmet Uygulamaları", a: "kamu",
      d: "Şehir hizmetlerine mobil erişim.",
      m: ["İBB Mobil", "Ankara Büyükşehir Mobil", "İzmir Büyükşehir Mobil", "Bursa Kart", "Antalya Kart", "Konya Kart", "Kocaeli Mobil", "Kayseri Kart", "Adana Kart", "Eskişehir Kart"] },
    { t: "En İyi Vergi ve Beyanname Hizmetleri", a: "kamu",
      d: "Beyanname ve vergi işlemleri.",
      m: ["GİB İnteraktif Vergi Dairesi", "Dijital Vergi Dairesi", "e-Beyanname", "Defter Beyan Sistemi", "Paraşüt Vergi", "Muhasebe.com", "e-Fatura Portalı", "Vergi Hesaplama", "SGK e-Bildirge", "Gelir İdaresi Mobil"] },

    // ---- Abonelik ----
    { t: "En İyi Dizi ve Film Abonelikleri", a: "abonelik",
      d: "İçerik kütüphanesi ve fiyat dengesi.",
      m: ["Netflix", "BluTV", "Exxen", "Disney+", "Amazon Prime Video", "TOD", "Gain", "MUBI", "beIN CONNECT", "Apple TV+"] },
    { t: "En İyi Müzik Abonelik Servisleri", a: "abonelik",
      d: "Katalog genişliği ve ses kalitesi.",
      m: ["Spotify", "YouTube Music", "Apple Music", "Fizy", "Deezer", "Amazon Music", "Tidal", "SoundCloud Go+", "Muud", "Yandex Music"] },
    { t: "En İyi Bulut ve Yazılım Abonelikleri", a: "abonelik",
      d: "Bireysel kullanıcılar için değerli abonelikler.",
      m: ["Google One", "Microsoft 365", "iCloud+", "Adobe Creative Cloud", "Notion Plus", "Canva Pro", "ChatGPT Plus", "Dropbox Plus", "1Password", "Setapp"] },
    { t: "İptal Edilmesi En Zor Abonelikler", a: "abonelik",
      d: "Kullanıcıların en çok şikâyet ettiği süreçler.",
      m: ["Spor salonu üyelikleri", "Kablo TV paketleri", "Dergi abonelikleri", "Antivirüs yazılımları", "Oyun içi abonelikler", "Mobil operatör ek paketleri", "Bulut depolama planları", "Online kurs abonelikleri", "E-ticaret üyelik programları", "Kutu abonelikleri"] },
    { t: "En İyi Aile Paketi Sunan Servisler", a: "abonelik",
      d: "Birden fazla kişiyle paylaşılabilen abonelikler.",
      m: ["Spotify Family", "YouTube Premium Aile", "Netflix Standart", "Apple One Aile", "Google One Aile", "Microsoft 365 Family", "Disney+ Paylaşım", "Nintendo Switch Online Aile", "Xbox Game Pass Aile", "Amazon Prime Aile"] },

    // ---- Otomotiv hizmeti ----
    { t: "En İyi Yetkili Servis Ağları", a: "otomotiv-hizmet",
      d: "Marka servisleri ve bakım kalitesi.",
      m: ["Ford Otosan Servis", "Toyota Plaza", "Renault Servis", "Fiat Yetkili Servis", "Volkswagen Servis", "Hyundai Servis", "Peugeot Servis", "Mercedes-Benz Servis", "BMW Servis", "Togg Servis"] },
    { t: "En İyi Lastik ve Oto Bakım Zincirleri", a: "otomotiv-hizmet",
      d: "Lastik değişimi ve periyodik bakım.",
      m: ["Lastik.com.tr", "Bridgestone Türkiye", "Michelin Servis", "Petlas Bayileri", "Oto Bakım Merkezi", "Otoport", "Bosch Car Service", "Otomarket", "Speedy Oto Servis", "Doğuş Oto Servis"] },
    { t: "En İyi Araç Muayene ve Ekspertiz Hizmetleri", a: "otomotiv-hizmet",
      d: "İkinci el alımında güvenlik.",
      m: ["TÜVTÜRK", "Otoport Ekspertiz", "Dijital Ekspertiz", "Ekspertiz Merkezi", "Vavacars Ekspertiz", "Otokoç Ekspertiz", "Garenta Ekspertiz", "Autoking Ekspertiz", "Oto Ekspertiz Türkiye", "Aracım Ekspertiz"] },
    { t: "En İyi Otopark ve Vale Uygulamaları", a: "otomotiv-hizmet",
      d: "Şehir içinde park çözümü.",
      m: ["İSPARK", "Otopark.com", "Parkolay", "Vale Bul", "Parkme", "ParkKolay", "Otopark Bul", "EasyPark", "Vale Servis", "Park Yerim"] },

    // ---- Perakende hizmeti ----
    { t: "En İyi Market Zincirleri", a: "perakende",
      d: "Fiyat, ürün çeşitliliği ve yaygınlık.",
      m: ["BİM", "A101", "ŞOK", "Migros", "CarrefourSA", "Macrocenter", "Metro Market", "Happy Center", "Onur Market", "File Market"] },
    { t: "En İyi Yapı Market Zincirleri", a: "perakende",
      d: "Tadilat ve ev geliştirme alışverişi.",
      m: ["Koçtaş", "Bauhaus", "Tekzen", "Praktiker", "Yapı Market", "Doğtaş Yapı", "Milas Yapı", "Nakkaş Yapı Market", "Fixmarket", "Ege Yapı Market"] },
    { t: "En İyi Elektronik Mağaza Zincirleri", a: "perakende",
      d: "Teknoloji ürünleri perakendecileri.",
      m: ["Teknosa", "MediaMarkt", "Vatan Bilgisayar", "Bimeks", "Gold Bilgisayar", "İncehesap", "Vestel Mağazaları", "Arçelik Mağazaları", "Samsung Store", "Apple Premium Reseller"] },
    { t: "En İyi Kitap ve Kırtasiye Zincirleri", a: "perakende",
      d: "Kitap ve okul malzemesi.",
      m: ["D&R", "Kitapyurdu", "Nezih Kitabevi", "Remzi Kitabevi", "İdefix", "Pandora", "Homer Kitabevi", "Ofix", "Bimeks Kırtasiye", "Kitapsan"] },

    // ---- Kamu / güvenlik ----
    { t: "En Önemli Acil Durum Numaraları", a: "kamu",
      d: "Herkesin bilmesi gereken numaralar.",
      m: ["112 Acil Çağrı", "155 Polis", "156 Jandarma", "110 İtfaiye", "177 Orman Yangını", "158 Sahil Güvenlik", "184 SABİM", "183 Sosyal Destek", "175 Tüketici Hattı", "186 Elektrik Arıza"] },
    { t: "En İyi Güvenlik ve Alarm Hizmetleri", a: "kamu",
      d: "Ev ve işyeri güvenliği.",
      m: ["Pronet", "Securitas", "G4S Türkiye", "Prosegur", "Alarm Merkezi", "Cansel Güvenlik", "Netaş Güvenlik", "Kale Alarm", "SafeLife", "Smart Alarm"] },

    // ---- Etkinlik hizmeti ----
    { t: "En İyi Düğün ve Organizasyon Firmaları", a: "etkinlik",
      d: "Davet ve organizasyon planlama.",
      m: ["Düğün.com", "Evlilik Hazırlıkları", "Organizasyon Türkiye", "Wedding Planner İstanbul", "Davetiye Organizasyon", "Balo Organizasyon", "Beyaz Organizasyon", "Nişan Organizasyon", "Etkinlik Yönetimi", "Event Türkiye"] },
    { t: "En İyi Fotoğrafçılık Hizmetleri", a: "etkinlik",
      d: "Düğün, ürün ve portre çekimi.",
      m: ["Fotoğrafçı Bul", "Armut Fotoğrafçı", "Düğün Fotoğrafçısı", "Stüdyo Fotoğraf", "Ürün Çekimi Türkiye", "Portre Stüdyosu", "Drone Çekim", "Bebek Fotoğrafçısı", "Kurumsal Çekim", "Etkinlik Fotoğrafçısı"] },
    { t: "En İyi Catering ve İkram Firmaları", a: "etkinlik",
      d: "Toplu yemek ve etkinlik ikramı.",
      m: ["Sofra Group", "Sodexo Catering", "Compass Group Türkiye", "Aramark Türkiye", "Kervan Catering", "Divan Catering", "Nar Gourmet Catering", "Zade Catering", "Yemek Sepeti Kurumsal", "Mutfak Sanatları Catering"] },

    // ---- Çeviri / danışmanlık ----
    { t: "En İyi Çeviri ve Yeminli Tercüme Hizmetleri", a: "kurumsal",
      d: "Resmî belge ve teknik çeviri.",
      m: ["Protranslate", "Tercüme Bürosu", "Yeminli Tercüman", "Lingopia", "Çevirimvar", "Dijital Tercüme", "Mirora", "Ege Tercüme", "Netroloji Çeviri", "Alfabe Tercüme"] },
    { t: "En İyi Vize ve Göçmenlik Danışmanlıkları", a: "kurumsal",
      d: "Vize başvuru süreçleri.",
      m: ["VFS Global", "iDATA", "Gateway International", "Vize Merkezi", "Global Vize", "Kanada Göçmenlik Danışmanlığı", "Schengen Vize Merkezi", "Amerika Vize", "İngiltere Vize Merkezi", "Vize Danışmanı"] },
    { t: "En İyi Yurt Dışı Eğitim Danışmanlıkları", a: "egitim-hizmet",
      d: "Üniversite ve dil okulu yerleştirme.",
      m: ["IDP Education", "Kilroy Türkiye", "Global Vizyon", "Yurtdışı Eğitim Danışmanlığı", "IEC Türkiye", "Studyfy", "Interlink Eğitim", "Akademi Danışmanlık", "Study Abroad Türkiye", "Nova Eğitim"] },
    { t: "En İyi Sertifikasyon ve Mesleki Eğitim Kurumları", a: "egitim-hizmet",
      d: "Mesleki yeterlilik belgeleri.",
      m: ["Bilge Adam", "İSMEK", "Halk Eğitim Merkezleri", "Türk Standartları Enstitüsü", "MEB Mesleki Eğitim", "TÜBİTAK Eğitimleri", "PMI Türkiye", "Cisco Networking Academy", "Microsoft Learn", "AWS Eğitim"] },
    { t: "En İyi Kurumsal Eğitim ve Koçluk Firmaları", a: "egitim-hizmet",
      d: "Şirket içi gelişim programları.",
      m: ["Bilge Adam Kurumsal", "Kariyer.net Akademi", "İnvent Akademi", "Dale Carnegie Türkiye", "Franklin Covey Türkiye", "Bilgi Üniversitesi Kurumsal", "Koç Akademi", "Sabancı EDU", "Talent Akademi", "Gelişim Koçluğu"] },
    { t: "En İyi Bulut Altyapı Sağlayıcıları", a: "kurumsal",
      d: "Sunucu, depolama ve yönetilen servisler.",
      m: ["Amazon Web Services", "Microsoft Azure", "Google Cloud", "DigitalOcean", "Hetzner", "Cloudflare", "Vercel", "Oracle Cloud", "Turkcell Bulut", "Vodafone Bulut"] },
    { t: "En İyi Kurumsal Siber Güvenlik Firmaları", a: "kurumsal",
      d: "Güvenlik denetimi ve izleme hizmetleri.",
      m: ["STM", "Barikat Siber Güvenlik", "Havelsan", "Aselsan Siber", "Prodaft", "Picus Security", "Logsign", "Netsparker (Invicti)", "Komtera", "SOC Türkiye"] },
    { t: "En İyi Pazar Araştırma Şirketleri", a: "kurumsal",
      d: "Tüketici ve kamuoyu araştırmaları.",
      m: ["Ipsos Türkiye", "Nielsen Türkiye", "GfK Türkiye", "Konda", "Areda Survey", "Metropoll", "Optimar", "Yöneylem Araştırma", "Themis Araştırma", "Barem Research"] },
    { t: "En İyi Temizlik ve Tesis Yönetimi Firmaları", a: "kurumsal",
      d: "Kurumsal bina hizmetleri.",
      m: ["ISS Türkiye", "Sodexo Tesis Yönetimi", "Compass Group", "Serel Tesis Yönetimi", "Akfen Hizmet", "Anadolu Tesis Yönetimi", "Cushman & Wakefield", "Ata Tesis Yönetimi", "Vira Facility", "Turkuaz Tesis"] },
    { t: "En İyi Depolama ve Eşya Saklama Hizmetleri", a: "ev-hizmet",
      d: "Geçici eşya saklama çözümleri.",
      m: ["Boxie", "Depom", "Kutu Depo", "Self Storage İstanbul", "Eşya Deposu", "Depola", "Storage Türkiye", "Ambar Depo", "Güvenli Depo", "Mini Depo"] },
    { t: "En İyi Klima ve Kombi Servisleri", a: "ev-hizmet",
      d: "Bakım, montaj ve arıza giderme.",
      m: ["Baymak Servis", "Vaillant Servis", "Demirdöküm Servis", "Bosch Termoteknik Servis", "Daikin Servis", "Arçelik Klima Servis", "Buderus Servis", "ECA Servis", "Viessmann Servis", "Airfel Servis"] },
    { t: "En İyi Böcek İlaçlama Firmaları", a: "ev-hizmet",
      d: "Ev ve işyeri haşere kontrolü.",
      m: ["Rentokil Türkiye", "Boyner İlaçlama", "Anadolu İlaçlama", "Ekol İlaçlama", "Vira İlaçlama", "Türkiye Pest Control", "Hijyen İlaçlama", "Bio İlaçlama", "Ata İlaçlama", "Nova İlaçlama"] },
  ],
};
