import type { KategoriIcerigi } from "./tipler";

/**
 * Konu kategorisi — 100+ liste.
 * Alt kategoriler: dizi, film, animasyon, muzik, kitap, oyun, spor,
 * teknoloji-konu, yasam, kariyer, egitim, seyahat, finans, saglik, kultur
 */
export const konu: KategoriIcerigi = {
  kategori: "konu",
  listeler: [
    // ---- Dizi ----
    { t: "Şimdiye Kadarki En İyi Diziler", a: "dizi",
      d: "Türlerden bağımsız, en çok konuşulan yapımlar.",
      m: ["Breaking Bad", "The Sopranos", "The Wire", "Game of Thrones", "Chernobyl", "Better Call Saul", "The Office", "True Detective", "Mad Men", "Succession"] },
    { t: "En İyi Türk Dizileri", a: "dizi",
      d: "Yerli yapımlar arasında en çok izlenenler.",
      m: ["Çukur", "Behzat Ç.", "Leyla ile Mecnun", "Şahsiyet", "Muhteşem Yüzyıl", "Bir Başkadır", "Kurtlar Vadisi", "Ezel", "Yaprak Dökümü", "Masumlar Apartmanı"] },
    { t: "En İyi Netflix Dizileri", a: "dizi",
      d: "Platform yapımları arasında öne çıkanlar.",
      m: ["Stranger Things", "The Crown", "Dark", "Squid Game", "Ozark", "Narcos", "Money Heist", "Wednesday", "The Queen's Gambit", "Bridgerton"] },
    { t: "En İyi Bilim Kurgu Dizileri", a: "dizi",
      d: "Gelecek ve teknoloji temalı yapımlar.",
      m: ["Black Mirror", "Severance", "Westworld", "The Expanse", "Foundation", "Dark", "Devs", "Silo", "Fringe", "Battlestar Galactica"] },
    { t: "En İyi Suç ve Polisiye Dizileri", a: "dizi",
      d: "Cinayet, dedektif ve mafya hikâyeleri.",
      m: ["Breaking Bad", "True Detective", "Mindhunter", "The Wire", "Peaky Blinders", "Fargo", "Sherlock", "Better Call Saul", "Line of Duty", "Broadchurch"] },
    { t: "En İyi Komedi Dizileri", a: "dizi",
      d: "Tekrar tekrar izlenen komedi yapımları.",
      m: ["The Office", "Friends", "Brooklyn Nine-Nine", "Parks and Recreation", "Seinfeld", "It's Always Sunny in Philadelphia", "Ted Lasso", "Arrested Development", "Community", "Schitt's Creek"] },
    { t: "En İyi Fantastik Diziler", a: "dizi",
      d: "Büyülü dünyalar ve efsane anlatıları.",
      m: ["Game of Thrones", "House of the Dragon", "The Witcher", "The Sandman", "His Dark Materials", "Shadow and Bone", "The Lord of the Rings: The Rings of Power", "Good Omens", "American Gods", "Carnival Row"] },
    { t: "En İyi Belgesel Dizileri", a: "dizi",
      d: "Doğa, suç ve tarih belgeselleri.",
      m: ["Planet Earth II", "Our Planet", "Making a Murderer", "The Last Dance", "Cosmos", "Tiger King", "Chef's Table", "Wild Wild Country", "Formula 1: Drive to Survive", "Blue Planet II"] },
    { t: "En İyi Kore Dizileri", a: "dizi",
      d: "K-drama dünyasının en çok izlenenleri.",
      m: ["Squid Game", "Crash Landing on You", "Itaewon Class", "Goblin", "Kingdom", "Vincenzo", "Reply 1988", "My Mister", "Hospital Playlist", "Signal"] },
    { t: "En İyi Anime Dizileri", a: "dizi",
      d: "Japon animasyonunun klasikleri ve yeni yapımları.",
      m: ["Fullmetal Alchemist: Brotherhood", "Attack on Titan", "Death Note", "One Piece", "Steins;Gate", "Cowboy Bebop", "Demon Slayer", "Jujutsu Kaisen", "Hunter x Hunter", "Vinland Saga"] },
    { t: "En Sevilen Mini Diziler", a: "dizi",
      d: "Tek sezonda biten, kısa ve yoğun yapımlar.",
      m: ["Chernobyl", "The Queen's Gambit", "Band of Brothers", "When They See Us", "Unorthodox", "Mare of Easttown", "The Night Of", "Godless", "Maid", "Beef"] },

    // ---- Film ----
    { t: "Şimdiye Kadarki En İyi Filmler", a: "film",
      d: "Sinema tarihinin en çok anılan yapımları.",
      m: ["The Godfather", "The Shawshank Redemption", "Pulp Fiction", "Schindler's List", "12 Angry Men", "Fight Club", "Forrest Gump", "The Dark Knight", "Goodfellas", "Parasite"] },
    { t: "En İyi Türk Filmleri", a: "film",
      d: "Yerli sinemanın en çok konuşulan yapımları.",
      m: ["Eşkıya", "Bir Zamanlar Anadolu'da", "Kış Uykusu", "Ayla", "G.O.R.A.", "Babam ve Oğlum", "Muhsin Bey", "Vizontele", "Üç Maymun", "Yol"] },
    { t: "En İyi Bilim Kurgu Filmleri", a: "film",
      d: "Gelecek tasavvurları ve uzay hikâyeleri.",
      m: ["Blade Runner 2049", "Interstellar", "Arrival", "Inception", "2001: A Space Odyssey", "The Matrix", "Dune", "Ex Machina", "Children of Men", "Alien"] },
    { t: "En İyi Animasyon Filmleri", a: "film",
      d: "Her yaştan izleyiciye hitap eden animasyonlar.",
      m: ["Spirited Away", "Toy Story", "Spider-Man: Into the Spider-Verse", "WALL-E", "Up", "Coco", "Grave of the Fireflies", "The Lion King", "Princess Mononoke", "Inside Out"] },
    { t: "En İyi Korku Filmleri", a: "film",
      d: "Klasiklerden yeni nesil korkuya.",
      m: ["The Shining", "Hereditary", "The Exorcist", "Get Out", "The Thing", "Alien", "Psycho", "It Follows", "The Witch", "Sinister"] },
    { t: "En İyi Gerilim Filmleri", a: "film",
      d: "Nefes kesen kurgular.",
      m: ["Se7en", "Zodiac", "Prisoners", "Gone Girl", "No Country for Old Men", "Nightcrawler", "Oldboy", "The Silence of the Lambs", "Memento", "Sicario"] },
    { t: "En İyi Komedi Filmleri", a: "film",
      d: "Yeniden izlenen komediler.",
      m: ["The Grand Budapest Hotel", "Superbad", "Groundhog Day", "The Big Lebowski", "Airplane!", "Hot Fuzz", "Anchorman", "Monty Python and the Holy Grail", "Dumb and Dumber", "In Bruges"] },
    { t: "En İyi Savaş Filmleri", a: "film",
      d: "Cephe ve cephe gerisi hikâyeleri.",
      m: ["Saving Private Ryan", "Apocalypse Now", "1917", "Full Metal Jacket", "Dunkirk", "Come and See", "Platoon", "The Thin Red Line", "Black Hawk Down", "Letters from Iwo Jima"] },
    { t: "En İyi Marvel Filmleri", a: "film",
      d: "MCU ve diğer Marvel yapımları.",
      m: ["Avengers: Infinity War", "Avengers: Endgame", "Guardians of the Galaxy", "Iron Man", "Captain America: The Winter Soldier", "Black Panther", "Thor: Ragnarok", "Spider-Man: No Way Home", "Doctor Strange", "Logan"] },
    { t: "En İyi Yönetmenler", a: "film",
      d: "Sinema dilini değiştiren isimler.",
      m: ["Christopher Nolan", "Martin Scorsese", "Quentin Tarantino", "Stanley Kubrick", "Nuri Bilge Ceylan", "Denis Villeneuve", "Alfred Hitchcock", "Bong Joon-ho", "Steven Spielberg", "Wes Anderson"] },
    { t: "En İyi Film Müzikleri", a: "film",
      d: "Filmden bağımsız dinlenen soundtrack'ler.",
      m: ["Interstellar — Hans Zimmer", "The Godfather — Nino Rota", "Inception — Hans Zimmer", "Star Wars — John Williams", "Blade Runner 2049 — Zimmer & Wallfisch", "The Lord of the Rings — Howard Shore", "Dune — Hans Zimmer", "Schindler's List — John Williams", "Pulp Fiction Soundtrack", "Amélie — Yann Tiersen"] },

    // ---- Müzik ----
    { t: "En İyi Türkçe Rock Şarkıları", a: "muzik",
      d: "Türkçe rock'ın klasikleri.",
      m: ["Duman — Her Şeyi Yak", "Mor ve Ötesi — Bir Derdim Var", "Şebnem Ferah — Sigara", "Teoman — Paramparça", "maNga — Bir Kadın Çizeceksin", "Hayko Cepkin — Sen Gelmez Oldun", "Kurban — Uyan", "Ezginin Günlüğü — Sevda Değil", "Yüksek Sadakat — Belki Üstümüzden Bir Kuş Geçer", "Athena — Ses Etme"] },
    { t: "En İyi Türk Rock Grupları", a: "muzik",
      d: "Türkiye'de rock sahnesinin öncüleri.",
      m: ["Duman", "Mor ve Ötesi", "maNga", "Athena", "Kurban", "Şebnem Ferah", "Pentagram", "Yüksek Sadakat", "Replikas", "Gripin"] },
    { t: "En İyi Türkçe Rap Şarkıları", a: "muzik",
      d: "Türkçe rap sahnesinin öne çıkan parçaları.",
      m: ["Ceza — Suspus", "Sagopa Kajmer — Bir Sanatçının Ölümü", "Ezhel — Felaket", "Şanışer — Susamam", "Ceza — Holocaust", "Killa Hakan — Fight Kulüp", "Ben Fero — Tak Tak Tak", "Motive — Antidepresan", "Uzi — Kan", "Norm Ender — Mekanın Sahibi"] },
    { t: "En İyi Türk Sanat Müziği Sanatçıları", a: "muzik",
      d: "TSM geleneğinin büyük isimleri.",
      m: ["Zeki Müren", "Müzeyyen Senar", "Bülent Ersoy", "Muazzez Ersoy", "Emel Sayın", "Behiye Aksoy", "Safiye Ayla", "Münir Nurettin Selçuk", "Neşet Ertaş", "Hamiyet Yüceses"] },
    { t: "En İyi Türk Halk Müziği Sanatçıları", a: "muzik",
      d: "Anadolu'nun ozan ve yorumcuları.",
      m: ["Neşet Ertaş", "Aşık Veysel", "Muharrem Ertaş", "Arif Sağ", "Musa Eroğlu", "Belkıs Akkale", "Selda Bağcan", "Yavuz Bingöl", "Kubat", "Sabahat Akkiraz"] },
    { t: "En İyi Yabancı Müzik Grupları", a: "muzik",
      d: "Dünya müzik tarihine yön veren gruplar.",
      m: ["The Beatles", "Pink Floyd", "Queen", "Led Zeppelin", "Radiohead", "Nirvana", "The Rolling Stones", "Metallica", "U2", "Coldplay"] },
    { t: "En İyi Podcast'ler", a: "muzik",
      d: "Türkçe ve yabancı dinlenmeye değer podcast'ler.",
      m: ["Podpodcast", "Aposto Radyo", "Bir Yaşam Bir Hikâye", "Anlatılmamış Hikâyeler", "Lex Fridman Podcast", "Huberman Lab", "Darkness Radio", "The Daily", "Radiolab", "Kayıp Rıhtım Podcast"] },
    { t: "En İyi Konser Mekanları", a: "muzik",
      d: "Türkiye'de canlı müzik için sahneler.",
      m: ["Zorlu PSM", "Volkswagen Arena", "Küçükçiftlik Park", "Harbiye Açıkhava", "Babylon", "Jolly Joker", "Salon İKSV", "Bostancı Gösteri Merkezi", "İzmir Arena", "ODTÜ Vişnelik"] },
    { t: "En Sevilen Müzik Festivalleri", a: "muzik",
      d: "Türkiye ve dünyadan festivaller.",
      m: ["Zeytinli Rock Festivali", "Nilüfer Müzik Festivali", "One Love Festival", "Chill-Out Festival", "İstanbul Caz Festivali", "Glastonbury", "Tomorrowland", "Coachella", "Sziget Festival", "Primavera Sound"] },

    // ---- Kitap ----
    { t: "Herkesin Okuması Gereken Kitaplar", a: "kitap",
      d: "Klasikler ve modern başyapıtlar.",
      m: ["Suç ve Ceza", "1984", "Sefiller", "Yüzyıllık Yalnızlık", "Küçük Prens", "Simyacı", "Kürk Mantolu Madonna", "Tutunamayanlar", "Fahrenheit 451", "Yabancı"] },
    { t: "En İyi Türk Romanları", a: "kitap",
      d: "Türk edebiyatının köşe taşları.",
      m: ["Tutunamayanlar", "Kürk Mantolu Madonna", "Saatleri Ayarlama Enstitüsü", "İnce Memed", "Aşk-ı Memnu", "Huzur", "Sinekli Bakkal", "Yaban", "Puslu Kıtalar Atlası", "Kar"] },
    { t: "En İyi Bilim Kurgu Kitapları", a: "kitap",
      d: "Türün en çok okunan eserleri.",
      m: ["Dune", "Vakıf", "Neuromancer", "Solaris", "Otostopçunun Galaksi Rehberi", "Üç Cisim Problemi", "Ender'in Oyunu", "Snow Crash", "Hyperion", "Ubik"] },
    { t: "En İyi Kişisel Gelişim Kitapları", a: "kitap",
      d: "Alışkanlık, odak ve üretkenlik üzerine.",
      m: ["Atomik Alışkanlıklar", "Derin Çalışma", "Hızlı ve Yavaş Düşünme", "Sıfırdan Bire", "Zengin Baba Yoksul Baba", "Mindset", "Kalıcı Başarı", "Cesur Yeni Dünya Düzeni", "Bugünü Yaşama Sanatı", "Şimdinin Gücü"] },
    { t: "En İyi Tarih Kitapları", a: "kitap",
      d: "Popüler tarih ve derinlemesine incelemeler.",
      m: ["Sapiens", "Silah, Mikrop ve Çelik", "Homo Deus", "Osmanlı İmparatorluğu Tarihi", "İnsanlığın Kısa Tarihi", "Modern Türkiye'nin Doğuşu", "Roma İmparatorluğu'nun Gerileyiş ve Çöküş Tarihi", "Nutuk", "Bir Şehrin Hafızası", "İpek Yolları"] },
    { t: "En İyi Polisiye ve Gerilim Kitapları", a: "kitap",
      d: "Sürükleyici kurgular.",
      m: ["Ve Sonra Kimse Kalmadı", "Kayıp Kız", "Sessiz Hasta", "Da Vinci Şifresi", "Ejderha Dövmeli Kız", "Şeytanı Gördüm", "Cadı Ağacı", "Kuzuların Sessizliği", "Gölge Oyunu", "Kara Kitap"] },
    { t: "En İyi Fantastik Kitap Serileri", a: "kitap",
      d: "Uzun soluklu fantastik dünyalar.",
      m: ["Yüzüklerin Efendisi", "Harry Potter", "Buz ve Ateşin Şarkısı", "Kral Katili Güncesi", "Fırtına Işığı Arşivi", "Mistborn", "Witcher Serisi", "Karanlığın Sol Eli", "Malazan Ölülerin Kitabı", "Narnia Günlükleri"] },
    { t: "En İyi Çocuk Kitapları", a: "kitap",
      d: "Okuma alışkanlığı kazandıran kitaplar.",
      m: ["Küçük Prens", "Momo", "Charlie'nin Çikolata Fabrikası", "Pinokyo", "Matilda", "Şeker Portakalı", "Sihirli Kalem", "Uçan Sınıf", "Alice Harikalar Diyarında", "Küçük Kara Balık"] },
    { t: "En İyi Şiir Kitapları", a: "kitap",
      d: "Türk ve dünya şiirinden seçkiler.",
      m: ["Memleketimden İnsan Manzaraları", "Bütün Şiirleri — Cemal Süreya", "İkinci Yeni Antolojisi", "Kırmızı Kitap — Attila İlhan", "Bütün Şiirler — Turgut Uyar", "Yaprak Dökümü Şiirleri", "Gülün Adı Şiirleri", "Mesnevi", "Divan — Fuzuli", "Karadut — Bedri Rahmi"] },
    { t: "En İyi Ekonomi ve İş Kitapları", a: "kitap",
      d: "İş dünyası ve ekonomiye giriş.",
      m: ["Sıfırdan Bire", "Yalın Girişim", "İyi'den Mükemmel Şirkete", "Zengin Baba Yoksul Baba", "Siyah Kuğu", "Ekonomi Sarmalı", "Kapitalizm ve Özgürlük", "Yenilikçinin İkilemi", "Sürükleyici Fikirler", "Antikırılgan"] },

    // ---- Oyun ----
    { t: "Şimdiye Kadarki En İyi Video Oyunları", a: "oyun",
      d: "Tür fark etmeksizin en çok anılan oyunlar.",
      m: ["The Legend of Zelda: Breath of the Wild", "The Witcher 3", "Red Dead Redemption 2", "Elden Ring", "God of War", "Half-Life 2", "Grand Theft Auto V", "Portal 2", "The Last of Us", "Super Mario Odyssey"] },
    { t: "En İyi Açık Dünya Oyunları", a: "oyun",
      d: "Keşif odaklı geniş haritalar.",
      m: ["Elden Ring", "Red Dead Redemption 2", "The Witcher 3", "Breath of the Wild", "Grand Theft Auto V", "Cyberpunk 2077", "Assassin's Creed Odyssey", "Ghost of Tsushima", "Horizon Forbidden West", "Skyrim"] },
    { t: "En İyi Rekabetçi Çok Oyunculu Oyunlar", a: "oyun",
      d: "E-spor ve rekabetçi sahnede öne çıkanlar.",
      m: ["Counter-Strike 2", "League of Legends", "Valorant", "Dota 2", "Rocket League", "Apex Legends", "Fortnite", "Overwatch 2", "Rainbow Six Siege", "StarCraft II"] },
    { t: "En İyi Mobil Oyunlar", a: "oyun",
      d: "Telefonda oynanabilecek en iyi yapımlar.",
      m: ["Clash Royale", "PUBG Mobile", "Genshin Impact", "Candy Crush Saga", "Zen Match", "Toon Blast", "Brawl Stars", "Among Us", "Monument Valley", "Alto's Odyssey"] },
    { t: "En İyi Bağımsız (Indie) Oyunlar", a: "oyun",
      d: "Küçük stüdyoların büyük işleri.",
      m: ["Hollow Knight", "Hades", "Stardew Valley", "Celeste", "Undertale", "Disco Elysium", "Outer Wilds", "Cuphead", "Dead Cells", "Return of the Obra Dinn"] },
    { t: "En İyi Hikâye Odaklı Oyunlar", a: "oyun",
      d: "Anlatısıyla akılda kalan yapımlar.",
      m: ["The Last of Us Part II", "Red Dead Redemption 2", "Disco Elysium", "God of War Ragnarök", "Life is Strange", "Detroit: Become Human", "Mass Effect 2", "What Remains of Edith Finch", "Firewatch", "Bioshock Infinite"] },
    { t: "En Zor Oyunlar", a: "oyun",
      d: "Sabır ve refleks isteyen yapımlar.",
      m: ["Sekiro: Shadows Die Twice", "Dark Souls", "Elden Ring", "Bloodborne", "Celeste", "Cuphead", "Hollow Knight: Silksong", "Super Meat Boy", "Nioh 2", "Getting Over It"] },
    { t: "En İyi Türk Yapımı Oyunlar", a: "oyun",
      d: "Türkiye'den çıkan oyun stüdyolarının işleri.",
      m: ["Mount & Blade II: Bannerlord", "Zula", "Toon Blast", "Royal Match", "İstanbul Efsaneleri", "Darkness and Flame", "Wolfteam", "Metin2", "Zen Match", "Dream Games Royal Kingdom"] },

    // ---- Spor ----
    { t: "Tüm Zamanların En İyi Futbolcuları", a: "spor",
      d: "Futbol tarihinin en büyük isimleri.",
      m: ["Lionel Messi", "Cristiano Ronaldo", "Pelé", "Diego Maradona", "Johan Cruyff", "Zinedine Zidane", "Ronaldo Nazário", "Michel Platini", "Franz Beckenbauer", "Alfredo Di Stéfano"] },
    { t: "Türkiye'nin En İyi Futbolcuları", a: "spor",
      d: "Milli takım ve kulüp kariyerleriyle.",
      m: ["Hakan Şükür", "Rüştü Reçber", "Emre Belözoğlu", "Arda Turan", "Alpay Özalan", "Tugay Kerimoğlu", "Nihat Kahveci", "Metin Oktay", "Lefter Küçükandonyadis", "Arda Güler"] },
    { t: "En İyi Basketbolcular", a: "spor",
      d: "NBA ve Avrupa'nın en iyileri.",
      m: ["Michael Jordan", "LeBron James", "Kareem Abdul-Jabbar", "Magic Johnson", "Larry Bird", "Kobe Bryant", "Shaquille O'Neal", "Tim Duncan", "Nikola Jokić", "Hedo Türkoğlu"] },
    { t: "En Büyük Spor Rekabetleri", a: "spor",
      d: "Tarihe geçen derbiler ve rekabetler.",
      m: ["Fenerbahçe - Galatasaray", "Real Madrid - Barcelona", "Boca Juniors - River Plate", "Manchester United - Liverpool", "Beşiktaş - Fenerbahçe", "AC Milan - Inter", "Celtic - Rangers", "Lakers - Celtics", "Federer - Nadal", "Ali - Frazier"] },
    { t: "En İyi Formula 1 Pilotları", a: "spor",
      d: "Şampiyonluk ve yarış kazanma rekorlarıyla.",
      m: ["Lewis Hamilton", "Michael Schumacher", "Ayrton Senna", "Max Verstappen", "Alain Prost", "Sebastian Vettel", "Juan Manuel Fangio", "Fernando Alonso", "Niki Lauda", "Jim Clark"] },
    { t: "En Sevilen Olimpiyat Anları", a: "spor",
      d: "Olimpiyat tarihine geçen performanslar.",
      m: ["Usain Bolt 100m rekoru", "Michael Phelps 8 altın", "Naim Süleymanoğlu üçlemesi", "Simone Biles performansı", "Mo Farah çift altın", "Cathy Freeman 400m", "Jesse Owens 1936", "Nadia Comaneci 10 puan", "Mirac Meriç kürek", "Dream Team 1992"] },
    { t: "En İyi Antrenörler", a: "spor",
      d: "Futbol ve basketbolda dönem açan teknik adamlar.",
      m: ["Pep Guardiola", "Sir Alex Ferguson", "Jose Mourinho", "Fatih Terim", "Johan Cruyff", "Carlo Ancelotti", "Jürgen Klopp", "Zeljko Obradovic", "Phil Jackson", "Arsène Wenger"] },
    { t: "Türkiye'nin En Başarılı Sporcuları", a: "spor",
      d: "Olimpiyat ve dünya şampiyonluklarıyla.",
      m: ["Naim Süleymanoğlu", "Halil Mutlu", "Hamza Yerlikaya", "Süreyya Ayhan", "Ruhi Sarıalp", "Mete Gazoz", "Buse Naz Çakıroğlu", "Taha Akgül", "Yasemin Adar", "Rıza Kayaalp"] },

    // ---- Teknoloji konusu ----
    { t: "Hayatı Değiştiren Teknolojiler", a: "teknoloji-konu",
      d: "Gündelik hayatı en çok dönüştüren buluşlar.",
      m: ["İnternet", "Akıllı telefon", "Yapay zekâ", "GPS", "Elektrikli araçlar", "Bulut bilişim", "mRNA aşıları", "Güneş paneli", "Blokzincir", "3D yazıcı"] },
    { t: "En Çok Tartışılan Yapay Zekâ Konuları", a: "teknoloji-konu",
      d: "Yapay zekânın etik ve pratik tartışmaları.",
      m: ["Yapay zekâ ve istihdam", "Telif hakkı ve üretken yapay zekâ", "Derin sahte (deepfake) içerikler", "Otonom silahlar", "Yapay zekâ düzenlemesi", "Veri gizliliği", "Algoritmik önyargı", "Yapay genel zekâ", "Eğitimde yapay zekâ", "Sağlıkta yapay zekâ"] },
    { t: "Geleceği Şekillendirecek Teknolojiler", a: "teknoloji-konu",
      d: "Önümüzdeki on yılda etkisi büyüyecek alanlar.",
      m: ["Kuantum bilişim", "Füzyon enerjisi", "Beyin-bilgisayar arayüzü", "Otonom araçlar", "Uzay turizmi", "Sentetik biyoloji", "Katı hâl bataryalar", "6G", "Robotik cerrahi", "Dikey tarım"] },
    { t: "En Önemli Siber Güvenlik Konuları", a: "teknoloji-konu",
      d: "Kurumları ve bireyleri ilgilendiren riskler.",
      m: ["Fidye yazılımları", "Oltalama saldırıları", "İki adımlı doğrulama", "Parola yöneticileri", "Sıfır güven mimarisi", "Tedarik zinciri saldırıları", "Veri sızıntıları", "Sosyal mühendislik", "Sıfırıncı gün açıkları", "Kripto dolandırıcılıkları"] },
    { t: "En Popüler Programlama Dilleri", a: "teknoloji-konu",
      d: "Kullanım yaygınlığı ve iş ilanlarıyla.",
      m: ["Python", "JavaScript", "TypeScript", "Java", "C#", "Go", "Rust", "C++", "Kotlin", "Swift"] },
    { t: "Yazılımcıların En Çok Tartıştığı Konular", a: "teknoloji-konu",
      d: "Ekip içi bitmeyen tartışmalar.",
      m: ["Tab mı boşluk mu", "Mikroservis mi monolit mi", "SQL mi NoSQL mi", "Test yazmalı mı", "Kod yorumu gerekli mi", "Uzaktan çalışma", "Yapay zekâ ile kod yazma", "React mi Vue mu", "Tip güvenliği", "Erken optimizasyon"] },

    // ---- Yaşam ----
    { t: "Sabah Rutinine Eklenecek En İyi Alışkanlıklar", a: "yasam",
      d: "Güne iyi başlamak için pratik öneriler.",
      m: ["Erken kalkmak", "Su içmek", "Kısa yürüyüş", "Esneme hareketleri", "Telefonu geç açmak", "Kahvaltı etmek", "Günlük tutmak", "Meditasyon", "Yatağı toplamak", "Gün planı çıkarmak"] },
    { t: "Verimliliği Artıran En İyi Yöntemler", a: "yasam",
      d: "Odaklanma ve zaman yönetimi teknikleri.",
      m: ["Pomodoro tekniği", "Zaman bloklama", "Tek görev odaklılık", "İki dakika kuralı", "Eisenhower matrisi", "Derin çalışma blokları", "Bildirimleri kapatmak", "Haftalık gözden geçirme", "Getting Things Done", "Kanban tahtası"] },
    { t: "En İyi Uyku Alışkanlıkları", a: "yasam",
      d: "Uyku kalitesini artıran değişiklikler.",
      m: ["Sabit uyku saati", "Karanlık oda", "Ekranı erken bırakmak", "Kafeini öğleden sonra kesmek", "Serin oda sıcaklığı", "Akşam yürüyüşü", "Yatakta çalışmamak", "Nefes egzersizi", "Ağır yorgan", "Uyku günlüğü"] },
    { t: "Evde Yapılabilecek En İyi Hobiler", a: "yasam",
      d: "Ekran dışında zaman geçirmenin yolları.",
      m: ["Yemek yapmak", "Kitap okumak", "Enstrüman çalmak", "Resim yapmak", "Bitki yetiştirmek", "Örgü örmek", "Fotoğrafçılık", "Kutu oyunları", "Yazı yazmak", "Model yapmak"] },
    { t: "Minimalist Yaşam İçin En İyi Öneriler", a: "yasam",
      d: "Daha az eşyayla yaşamak isteyenler için.",
      m: ["Kapsül gardırop", "Bir gir bir çık kuralı", "Dijital temizlik", "Abonelik gözden geçirme", "Kâğıtsız arşiv", "Ortak eşya kullanımı", "İkinci el alışveriş", "Deneyime harcamak", "30 gün kuralı", "Yıllık envanter"] },
    { t: "Tasarruf İçin En İyi Yöntemler", a: "yasam",
      d: "Bütçe yönetimi ve harcama disiplini.",
      m: ["50/30/20 kuralı", "Otomatik birikim", "Harcama takibi", "Abonelik temizliği", "Toplu alışveriş", "Enerji tasarrufu", "Nakit zarf yöntemi", "Fiyat karşılaştırma", "Yemek planlama", "Borç kartopu yöntemi"] },
    { t: "Çevre İçin Yapılabilecek En Etkili Değişiklikler", a: "yasam",
      d: "Bireysel düzeyde en çok fark yaratanlar.",
      m: ["Toplu taşıma kullanmak", "Et tüketimini azaltmak", "Gıda israfını önlemek", "Tek kullanımlık plastikten kaçınmak", "Geri dönüşüm", "Enerji verimli cihazlar", "İkinci el alışveriş", "Su tasarrufu", "Yerel üretim tercih etmek", "Kompost yapmak"] },
    { t: "En İyi Ev Düzenleme İpuçları", a: "yasam",
      d: "Küçük evleri ferahlatan çözümler.",
      m: ["Dikey depolama", "Şeffaf kutular", "Etiketleme", "Kapı arkası askı", "Yatak altı çekmece", "Kablo düzenleyici", "Mevsimlik rotasyon", "Katlama yöntemi", "Duvar rafı", "Çok amaçlı mobilya"] },

    // ---- Kariyer / eğitim ----
    { t: "En Çok Aranan Meslekler", a: "kariyer",
      d: "İş ilanı sayısı ve büyüme hızıyla.",
      m: ["Yazılım geliştirici", "Veri analisti", "Siber güvenlik uzmanı", "Yapay zekâ mühendisi", "Dijital pazarlama uzmanı", "Bulut mimarı", "UX tasarımcısı", "Ürün yöneticisi", "Hemşire", "İş analisti"] },
    { t: "İş Görüşmesinde En Sık Sorulan Sorular", a: "kariyer",
      d: "Hazırlıklı gitmek isteyenler için.",
      m: ["Kendinizden bahseder misiniz", "Güçlü ve zayıf yönleriniz", "Neden bu şirket", "Beş yıl sonra kendinizi nerede görüyorsunuz", "Zor bir durumu nasıl çözdünüz", "Neden ayrıldınız", "Maaş beklentiniz", "Ekip içinde çatışma yönetimi", "En büyük başarınız", "Sorunuz var mı"] },
    { t: "Kariyer Değiştirenler İçin En İyi Alanlar", a: "kariyer",
      d: "Sıfırdan girilebilen ve talep gören alanlar.",
      m: ["Yazılım geliştirme", "Veri analizi", "Dijital pazarlama", "UX/UI tasarımı", "Proje yönetimi", "İçerik üretimi", "Siber güvenlik", "Satış", "İnsan kaynakları", "Bulut sistemleri"] },
    { t: "Uzaktan Çalışmanın En Büyük Zorlukları", a: "kariyer",
      d: "Evden çalışanların ortak sorunları.",
      m: ["İş-yaşam sınırı", "Yalnızlık hissi", "İletişim kopukluğu", "Toplantı yorgunluğu", "Ev ortamı dikkat dağıtıcıları", "Zaman dilimi farkları", "Kariyer görünürlüğü", "Ergonomi sorunları", "Motivasyon dalgalanması", "Ekip kültürü eksikliği"] },
    { t: "En İyi Online Eğitim Platformları", a: "egitim",
      d: "Sertifika ve beceri kazandıran platformlar.",
      m: ["Coursera", "Udemy", "edX", "BTK Akademi", "Khan Academy", "Pluralsight", "LinkedIn Learning", "Datacamp", "Codecademy", "Türkiye Açık Ders"] },
    { t: "Yeni Bir Dil Öğrenmek İçin En İyi Yöntemler", a: "egitim",
      d: "Kalıcı öğrenme için pratik yollar.",
      m: ["Günlük kısa tekrar", "Dizi ve film izlemek", "Aralıklı tekrar kartları", "Dil değişim partneri", "Podcast dinlemek", "Kitap okumak", "Günlük tutmak", "Uygulama kullanmak", "Ana dili konuşanla pratik", "Kelime defteri"] },
    { t: "Üniversite Seçerken Dikkat Edilmesi Gerekenler", a: "egitim",
      d: "Tercih dönemi için kriterler.",
      m: ["Bölümün müfredatı", "Akademik kadro", "Staj ve iş bağlantıları", "Şehir ve yaşam maliyeti", "Yurt imkânları", "Erasmus anlaşmaları", "Kütüphane ve laboratuvar", "Mezun ağı", "Çift anadal imkânı", "Kulüp ve sosyal hayat"] },
    { t: "Öğrenciler İçin En İyi Çalışma Teknikleri", a: "egitim",
      d: "Sınav dönemi için etkili yöntemler.",
      m: ["Aralıklı tekrar", "Aktif hatırlama", "Feynman tekniği", "Pomodoro", "Deneme sınavı çözmek", "Not özetleme", "Zihin haritası", "Grup çalışması", "Konu anlatma", "Uyku düzenine dikkat"] },

    // ---- Seyahat ----
    { t: "Türkiye'de Görülmesi Gereken Yerler", a: "seyahat",
      d: "Bir kez de olsa gidilmesi gereken noktalar.",
      m: ["Kapadokya", "Pamukkale", "Efes", "Nemrut Dağı", "Ölüdeniz", "Sümela Manastırı", "Safranbolu", "Göbeklitepe", "Mardin", "Salda Gölü"] },
    { t: "Vizesiz Gidilebilecek En İyi Ülkeler", a: "seyahat",
      d: "Türk pasaportuyla kolay ulaşılan destinasyonlar.",
      m: ["Gürcistan", "Sırbistan", "Karadağ", "Bosna-Hersek", "Arnavutluk", "Kuzey Makedonya", "Malezya", "Katar", "Kuzey Kıbrıs", "Tayland"] },
    { t: "Bütçe Dostu Seyahat İpuçları", a: "seyahat",
      d: "Az parayla çok gezmek için.",
      m: ["Erken bilet almak", "Sezon dışı gitmek", "Hostel konaklama", "Toplu taşıma kullanmak", "Yerel lokantalar", "Ücretsiz müze günleri", "Şehir kartı almak", "Yürüyüş turları", "Uçuş uyarısı kurmak", "Bagajsız seyahat"] },
    { t: "Avrupa'da Görülmesi Gereken Şehirler", a: "seyahat",
      d: "İlk kez Avrupa'ya gidenler için.",
      m: ["Roma", "Paris", "Barselona", "Prag", "Viyana", "Amsterdam", "Lizbon", "Budapeşte", "Floransa", "Berlin"] },
    { t: "En İyi Ada Tatilleri", a: "seyahat",
      d: "Türkiye ve dünyadan ada rotaları.",
      m: ["Gökçeada", "Bozcaada", "Santorini", "Rodos", "Kefalonya", "Malta", "Sicilya", "Bali", "Maldivler", "Marmara Adası"] },
    { t: "Kış Tatili İçin En İyi Destinasyonlar", a: "seyahat",
      d: "Kar ve termal odaklı rotalar.",
      m: ["Uludağ", "Palandöken", "Kartepe", "Sarıkamış", "Kapadokya", "Abant", "Zermatt", "Chamonix", "Bansko", "Bukovel"] },
    { t: "Tek Başına Seyahat İçin En Güvenli Yerler", a: "seyahat",
      d: "Solo gezginler için önerilen destinasyonlar.",
      m: ["Japonya", "Portekiz", "İzlanda", "Slovenya", "Yeni Zelanda", "Gürcistan", "Estonya", "Norveç", "Tayvan", "İrlanda"] },

    // ---- Finans ----
    { t: "Yatırıma Başlayanlar İçin En Önemli Kurallar", a: "finans",
      d: "Temel yatırım disiplini ilkeleri.",
      m: ["Acil durum fonu oluşturmak", "Çeşitlendirme yapmak", "Uzun vadeli düşünmek", "Riski anlamak", "Maliyetleri düşürmek", "Duygusal karar vermemek", "Düzenli yatırım yapmak", "Bilmediğine yatırım yapmamak", "Borçla yatırım yapmamak", "Portföyü gözden geçirmek"] },
    { t: "En Çok Tercih Edilen Yatırım Araçları", a: "finans",
      d: "Türkiye'de yaygın yatırım seçenekleri.",
      m: ["Mevduat", "Altın", "Döviz", "Borsa hisseleri", "Yatırım fonları", "Gayrimenkul", "Devlet tahvili", "Eurobond", "Kripto para", "Bireysel emeklilik"] },
    { t: "Kişisel Bütçe Yönetimi İçin En İyi Uygulamalar", a: "finans",
      d: "Harcama takibi ve planlama araçları.",
      m: ["Paramla", "Fintables", "Spendee", "Money Manager", "Wallet", "YNAB", "Mint", "Excel bütçe şablonu", "Banka uygulaması kategorileri", "Zenginlik defteri"] },
    { t: "En Sık Yapılan Finansal Hatalar", a: "finans",
      d: "Kaçınılması gereken davranışlar.",
      m: ["Bütçe yapmamak", "Kredi kartı asgari ödeme", "Acil durum fonu olmaması", "Ani heves alışverişleri", "Yatırımı ertelemek", "Tek varlığa yatırım", "Sigortasız kalmak", "Emeklilik planı yapmamak", "Borcu borçla kapatmak", "Getiriyi vaat edene inanmak"] },

    // ---- Sağlık ----
    { t: "Sağlıklı Beslenme İçin En İyi Alışkanlıklar", a: "saglik",
      d: "Sürdürülebilir beslenme değişiklikleri.",
      m: ["Bol su içmek", "Sebze ağırlıklı beslenmek", "İşlenmiş gıdayı azaltmak", "Şeker tüketimini düşürmek", "Porsiyon kontrolü", "Kahvaltıyı atlamamak", "Yavaş yemek", "Lif tüketimini artırmak", "Yemek planlamak", "Gece atıştırmasını azaltmak"] },
    { t: "Sırt ve Boyun Ağrısına Karşı En Etkili Öneriler", a: "saglik",
      d: "Masa başında çalışanlar için.",
      m: ["Ergonomik oturuş", "Saatlik mola vermek", "Ekran yüksekliğini ayarlamak", "Core egzersizleri", "Esneme hareketleri", "Yürüyüş", "Doğru yastık seçimi", "Telefonu göz hizasında tutmak", "Yüzme", "Fizyoterapi desteği"] },
    { t: "Bağışıklığı Güçlendiren En İyi Yöntemler", a: "saglik",
      d: "Bilimsel temeli olan öneriler.",
      m: ["Yeterli uyku", "Düzenli egzersiz", "Dengeli beslenme", "D vitamini takibi", "Stres yönetimi", "Sigara bırakmak", "Alkolü sınırlamak", "El hijyeni", "Aşı takvimi", "Sosyal bağ kurmak"] },
    { t: "Zihinsel Sağlık İçin En İyi Öneriler", a: "saglik",
      d: "Günlük hayatta uygulanabilir adımlar.",
      m: ["Düzenli uyku", "Fiziksel aktivite", "Sosyal bağlantı", "Sınır koymak", "Sosyal medyayı sınırlamak", "Doğada vakit geçirmek", "Nefes egzersizleri", "Profesyonel destek almak", "Günlük tutmak", "Yeni bir şey öğrenmek"] },
    { t: "En Sık Yapılan Egzersiz Hataları", a: "saglik",
      d: "Sakatlanmayı önlemek için dikkat edilecekler.",
      m: ["Isınmadan başlamak", "Aşırı ağırlık kaldırmak", "Yanlış form", "Dinlenme günü koymamak", "Su içmemek", "Tek bölgeye odaklanmak", "Esneme yapmamak", "Hedefsiz antrenman", "Uyku eksikliği", "Ağrıyı görmezden gelmek"] },

    // ---- Kültür ----
    { t: "Türkiye'nin En Önemli Kültürel Mirasları", a: "kultur",
      d: "Somut olmayan kültürel miras listesindekiler.",
      m: ["Meddahlık", "Karagöz ve Hacivat", "Aşıklık geleneği", "Mevlevi sema töreni", "Nevruz", "Kırkpınar yağlı güreşi", "Türk kahvesi kültürü", "Ebru sanatı", "Çini sanatı", "Hıdırellez"] },
    { t: "En Sevilen Türk Deyimleri ve Atasözleri", a: "kultur",
      d: "Gündelik dilde en çok kullanılanlar.",
      m: ["Damlaya damlaya göl olur", "Ayağını yorganına göre uzat", "Bir elin nesi var, iki elin sesi var", "Sakla samanı gelir zamanı", "Gülme komşuna gelir başına", "Ağaç yaşken eğilir", "Su testisi su yolunda kırılır", "Acele işe şeytan karışır", "İşleyen demir ışıldar", "Bugünün işini yarına bırakma"] },
    { t: "En İyi Türk Ressamlar", a: "kultur",
      d: "Türk resim sanatının öncü isimleri.",
      m: ["Osman Hamdi Bey", "Fikret Mualla", "Bedri Rahmi Eyüboğlu", "Abidin Dino", "Şeker Ahmet Paşa", "Nuri İyem", "Devrim Erbil", "Burhan Doğançay", "Neşet Günal", "İbrahim Çallı"] },
    { t: "En Önemli Türk Yazarlar", a: "kultur",
      d: "Türk edebiyatının kurucu isimleri.",
      m: ["Orhan Pamuk", "Yaşar Kemal", "Sabahattin Ali", "Ahmet Hamdi Tanpınar", "Oğuz Atay", "Nâzım Hikmet", "Halide Edib Adıvar", "Sait Faik Abasıyanık", "Peyami Safa", "Adalet Ağaoğlu"] },
    { t: "En İyi Tiyatro Oyunları", a: "kultur",
      d: "Sahnelenen klasik ve modern oyunlar.",
      m: ["Keşanlı Ali Destanı", "Bir Delinin Hatıra Defteri", "Hamlet", "Vişne Bahçesi", "Bekleyiş (Godot'yu Beklerken)", "Cimri", "Ayak Bacak Fabrikası", "Kanlı Nigar", "Şahları da Vururlar", "Sersem Kocanın Kurnaz Karısı"] },
    { t: "En Sevilen Türk Karikatüristleri", a: "kultur",
      d: "Mizah dergilerinin unutulmaz kalemleri.",
      m: ["Oğuz Aral", "Turhan Selçuk", "Semih Poroy", "Selçuk Erdem", "Bahadır Baruter", "Erdil Yaşaroğlu", "Yiğit Özgür", "Latif Demirci", "Behiç Ak", "Kemal Gökhan Gürses"] },
    { t: "En Önemli Türk Mimarlar", a: "kultur",
      d: "Türk mimarlığına yön veren isimler.",
      m: ["Mimar Sinan", "Sedad Hakkı Eldem", "Turgut Cansever", "Emin Onat", "Behruz Çinici", "Doğan Tekeli", "Han Tümertekin", "Nevzat Sayın", "Mimar Kemaleddin", "Vedat Tek"] },
    { t: "Dünyanın En Etkileyici Mimari Yapıları", a: "kultur",
      d: "Mutlaka görülmesi gereken yapılar.",
      m: ["Ayasofya", "Taç Mahal", "Sagrada Familia", "Kolezyum", "Machu Picchu", "Petra", "Angkor Wat", "Guggenheim Bilbao", "Sydney Opera Binası", "Alhambra"] },
  ],
};
