import type { KategoriIcerigi } from "./tipler";

/**
 * Mekan kategorisi — 100 liste.
 * Alt kategoriler: kafe, kahvalti, restoran, tatli, sokak-lezzeti, otel,
 * plaj, doga, tarih, muze, park, gece, alisveris, calisma, spor
 */
export const mekan: KategoriIcerigi = {
  kategori: "mekan",
  listeler: [
    // ---- Kafe ----
    { t: "İstanbul'un En İyi Üçüncü Dalga Kahvecileri", a: "kafe", c: "İstanbul",
      d: "Kendi çekirdeğini kavuran, filtre ve espresso işini ciddiye alan İstanbul mekanları.",
      m: ["Petra Roasting Co.", "Norm Coffee", "Kronotrop", "Coffee Sapiens", "MOC İstanbul", "Ministry of Coffee", "Cuppa Coffee", "Federal Coffee Company", "Walter's Coffee Roastery", "Montag Coffee Roasters"] },
    { t: "Ankara'nın En İyi Kahve Mekanları", a: "kafe", c: "Ankara",
      d: "Başkentte espresso ve filtre kahvenin adresleri.",
      m: ["Bikate Kahve", "Ada Kahve", "Kavun Kahve", "Cafe Nero Tunalı", "Simetri Kahve", "Kuppa Coffee", "Kahve Dünyası Armada", "Filtre Kahve Bahçelievler", "Gram Coffee", "Loci Kahve"] },
    { t: "İzmir'in En İyi Kahvecileri", a: "kafe", c: "İzmir",
      d: "Alsancak'tan Bostanlı'ya İzmir'in kahve durakları.",
      m: ["Grinder Coffee", "Vasco Coffee", "Bosca Coffee", "Roast House", "Casa Coffee Roasters", "Zerdali Kahve", "Nord Coffee", "La Cle Coffee", "Kırmızı Kahve", "Punto Alsancak"] },
    { t: "Kadıköy'ün En İyi Kahve Durakları", a: "kafe", c: "İstanbul",
      d: "Moda'dan Yeldeğirmeni'ne Kadıköy'ün kahve haritası.",
      m: ["Coffee Department", "Petra Moda", "Fazıl Bey Türk Kahvesi", "Cuppa Yeldeğirmeni", "Ops Coffee", "Barrel Coffee", "Beans Kadıköy", "Naive Coffee", "Kahve 6", "Riverside Coffee"] },
    { t: "Bursa'nın En İyi Kahvecileri", a: "kafe", c: "Bursa",
      d: "Bursa'da kahvesini iyi yapan mekanlar.",
      m: ["Yeşil Kahve", "Ottoman Coffee", "Kırık Kahve", "Marmara Kahve Evi", "Nişan Kahve", "Setbaşı Kahvecisi", "Coffee Lab Bursa", "Bosphorus Bursa", "Tahtakale Kahvecisi", "Uludağ Kahve Evi"] },
    { t: "Eskişehir'in Öğrenci Dostu Kafeleri", a: "kafe", c: "Eskişehir",
      d: "Ders çalışmaya ve uzun sohbetlere elverişli Eskişehir kafeleri.",
      m: ["Kırmızı Kafe", "Porsuk Kahve", "Odunpazarı Kahvecisi", "Barış Kafe", "Adam Kahve", "Sarnıç Kafe", "Espressolab Eskişehir", "Nuvo Kahve", "Alsancak Kafe", "İstasyon Kahve"] },
    { t: "Antalya'nın En İyi Kahve Mekanları", a: "kafe", c: "Antalya",
      d: "Kaleiçi'nden Lara'ya Antalya'nın kahve adresleri.",
      m: ["Kahve Dünyası Kaleiçi", "Big Chefs Antalya", "Simit Sarayı Konyaaltı", "Roka Coffee", "Marina Kahve", "Coffee Point Lara", "Sur Kahve", "Falez Kahve Evi", "Antik Kahve", "Tuz Kahve"] },
    { t: "Türkiye'nin En İyi Kahve Zincirleri", a: "kafe",
      d: "Ülke geneline yayılmış kahve zincirlerinin karşılaştırması.",
      m: ["Kahve Dünyası", "Espressolab", "Starbucks", "Caribou Coffee", "Coffy", "Gloria Jean's Coffees", "Tchibo", "Arabica Coffee House", "Coffee Department", "Kahveci Hacıbaba"] },
    { t: "Laptopla Çalışılabilecek En İyi Kafeler", a: "kafe", c: "İstanbul",
      d: "Priz, wifi ve gürültü dengesi iyi olan çalışma dostu mekanlar.",
      m: ["Coffee Department Karaköy", "Norm Coffee Şişhane", "Kronotrop Cihangir", "Ministry of Coffee", "Federal Karaköy", "Petra Bomonti", "MOC Bebek", "Cuppa Cihangir", "Beyoğlu Kahvecisi", "Faros Coffee"] },
    { t: "En İyi Türk Kahvesi Yapan Mekanlar", a: "kafe",
      d: "Köpüğü, sunumu ve kıvamıyla Türk kahvesinin ustaları.",
      m: ["Fazıl Bey Türk Kahvesi", "Mandabatmaz", "Kurukahveci Mehmet Efendi", "Ali Muhiddin Hacı Bekir", "Şark Kahvesi", "Pierre Loti Kahvesi", "Lâle Kahvesi", "Ethem Tezçakar Kahveci", "Kahve Mekteb-i", "Tophane Nargile Kahvesi"] },

    // ---- Kahvaltı ----
    { t: "İstanbul'un En İyi Kahvaltı Mekanları", a: "kahvalti", c: "İstanbul",
      d: "Serpmeden menemene, İstanbul'da kahvaltının en iyi adresleri.",
      m: ["Van Kahvaltı Evi", "Privato Cafe", "Beşiktaş Kahvaltıcısı", "Emirgan Sütiş", "Bebek Kahve", "Namlı Gurme", "Dai Pera", "Sütiş Üsküdar", "Kale Cafe Rumeli Hisarı", "Nar Gourmet Kahvaltı"] },
    { t: "Ankara'da Hafta Sonu Kahvaltısı İçin En İyi Mekanlar", a: "kahvalti", c: "Ankara",
      d: "Başkentte hafta sonu kahvaltı planı yapanlar için.",
      m: ["Kahvaltı Bahçesi Çayyolu", "Bulvar Palas Kahvaltı", "Köşk Kahvaltı Evi", "Ada Kahvaltı", "Beypazarı Konağı", "Gölbaşı Kahvaltı Evi", "Elmadağ Kahvaltı", "Tuna Kahvaltı Salonu", "Kuğulu Kahvaltı", "Mavi Köşe Kahvaltı"] },
    { t: "İzmir'in En İyi Kahvaltıcıları", a: "kahvalti", c: "İzmir",
      d: "Ege usulü kahvaltının İzmir'deki en iyi örnekleri.",
      m: ["Bostanlı Kahvaltıcısı", "Ali Usta Kahvaltı", "Reyhan Pastanesi", "Deniz Kahvaltı Evi", "Urla Köy Kahvaltısı", "Sığacık Kahvaltı Bahçesi", "Karşıyaka Kahvaltı Sokağı", "Kordon Kahvaltı", "Şirince Kahvaltı Evi", "Alaçatı Köy Kahvaltısı"] },
    { t: "Van Kahvaltısı İçin En İyi Adresler", a: "kahvalti",
      d: "Otlu peynir, kavut ve murtuğa: Van kahvaltısının en iyileri.",
      m: ["Sütçü Fevzi", "Sütçü Kenan", "Bak Hele Bak", "Kahvaltı Sokağı Van", "Van Kahvaltı Evi İstanbul", "Otlu Peynir Evi", "Beşkardeşler Kahvaltı", "Murtuğa Van", "Kervansaray Kahvaltı", "Anadolu Kahvaltı Salonu"] },
    { t: "Boğaz Manzaralı Kahvaltı Mekanları", a: "kahvalti", c: "İstanbul",
      d: "Kahvaltıya manzara eşlik etsin diyenler için.",
      m: ["Emirgan Sütiş", "Kale Cafe Rumeli Hisarı", "Lucca Bebek", "Beylerbeyi Sahil Kahvaltı", "Çengelköy Çınaraltı", "Anadolu Kavağı Kahvaltı", "Kanlıca Yoğurtçusu", "Sarıyer Sahil Kahvaltı", "Poyrazköy Kahvaltı", "Arnavutköy Balıkçısı Kahvaltı"] },
    { t: "Köy Kahvaltısı İçin En İyi Mekanlar", a: "kahvalti",
      d: "Şehirden kaçıp doğada serpme kahvaltı yapılacak yerler.",
      m: ["Polonezköy Kahvaltı Bahçeleri", "Ağva Köy Kahvaltısı", "Şile Kahvaltı Evi", "Cumalıkızık Kahvaltısı", "Beypazarı Köy Kahvaltısı", "Urla Bağ Kahvaltısı", "Sapanca Kahvaltı Bahçesi", "Abant Kahvaltı Evi", "Kartepe Köy Sofrası", "Yedigöller Kahvaltı"] },
    { t: "Gaziantep'in En İyi Kahvaltı Mekanları", a: "kahvalti", c: "Gaziantep",
      d: "Beyran ve katmerle başlayan Antep kahvaltısı.",
      m: ["Metanet Lokantası", "Zeynel Usta Katmer", "Orkide Pastanesi", "Beyran Salonu Antep", "Katmerci Zekeriya Usta", "Antep Kahvaltı Evi", "İmam Çağdaş", "Bayazhan Kahvaltı", "Elmacı Pazarı Kahvaltı", "Papirüs Kahvaltı"] },
    { t: "Bursa'nın En İyi Kahvaltı Mekanları", a: "kahvalti", c: "Bursa",
      d: "Uludağ eteklerinde ve şehir merkezinde kahvaltı.",
      m: ["Cumalıkızık Kahvaltı Evleri", "Setbaşı Kahvaltı", "Uludağ Kahvaltı Bahçesi", "Gölyazı Kahvaltı", "Misi Köyü Kahvaltıcısı", "Mudanya Sahil Kahvaltı", "Zeytinbağı Kahvaltı Evi", "Tophane Kahvaltı", "Karacabey Köy Kahvaltısı", "İnkaya Çınarı Kahvaltı"] },

    // ---- Restoran ----
    { t: "İstanbul'un En İyi Balık Restoranları", a: "restoran", c: "İstanbul",
      d: "Meze, rakı ve taze balık için İstanbul'un klasikleri.",
      m: ["Karaköy Lokantası", "Balıkçı Sabahattin", "Kıyı Restaurant", "Adem Baba", "Sardunya Balık", "Set Balık", "Poseidon Bebek", "Kalamar Restaurant", "Rumeli İskele", "Beyti Balık"] },
    { t: "Türkiye'nin En İyi Kebapçıları", a: "restoran",
      d: "Adana'dan Antep'e kebabın ustaları.",
      m: ["Çiya Sofrası", "İmam Çağdaş", "Beyti Restaurant", "Hamdi Restaurant", "Zübeyir Ocakbaşı", "Adana Yüzevler Kebap", "Halil Usta Adana", "Şehzade Erzurum Cağ Kebabı", "Kebapçı Halil Usta", "Develi Restaurant"] },
    { t: "İstanbul'un En İyi Ocakbaşıları", a: "restoran", c: "İstanbul",
      d: "Mangal başında akşam yemeği için en iyi adresler.",
      m: ["Zübeyir Ocakbaşı", "Kösebaşı", "Hacı Baba Ocakbaşı", "Bereket Ocakbaşı", "Nusr-Et Etiler", "Günaydın Kasap", "Sur Ocakbaşı", "Mesut Ocakbaşı", "Şazeli Ocakbaşı", "Cağaloğlu Ocakbaşı"] },
    { t: "En İyi Ev Yemeği Yapan Esnaf Lokantaları", a: "restoran", c: "İstanbul",
      d: "Öğle yemeğinde sıcak yemek arayanlar için.",
      m: ["Kanaat Lokantası", "Hacı Abdullah", "Çiya Sofrası", "Lades Lokantası", "Şehzade Cağ Kebabı", "Beyaz Fırın", "Karaköy Lokantası", "Fıccın", "Asmalı Cavit", "Bereket Lokantası"] },
    { t: "İstanbul'un En İyi Fine Dining Restoranları", a: "restoran", c: "İstanbul",
      d: "Özel akşamlar için tabak sunumunu ciddiye alan mekanlar.",
      m: ["Mikla", "Neolokal", "Turk Fatih Tutak", "Nicole", "Alancha", "Arkestra", "Yeni Lokanta", "Aheste", "Sunset Grill & Bar", "Lokanta Maya"] },
    { t: "En İyi Pideciler", a: "restoran",
      d: "Karadeniz usulünden Konya fırınına pide sıralaması.",
      m: ["Fatih Karadeniz Pidecisi", "Hatay Medeniyetler Sofrası", "Emek Pide", "Kastamonu Pidecisi", "Trabzon Pidecisi Vakfıkebir", "Konya Etli Ekmek", "Beyzade Pide", "Şahin Pide", "Ordu Pidecisi", "Samsun Pide Salonu"] },
    { t: "En İyi Lahmacun Yapan Mekanlar", a: "restoran",
      d: "İnce hamur, bol kıyma: lahmacunun en iyileri.",
      m: ["Halil Lahmacun", "Öz Kilis Lahmacun", "Borsam Taşfırın", "Antep Lahmacun Salonu", "Adana Lahmacun Evi", "Uzun Lahmacun", "Şanlıurfa Lahmacuncusu", "Katmerci Lahmacun", "Bayramoğlu Lahmacun", "Fıstık Lahmacun"] },
    { t: "İstanbul'un En İyi İtalyan Restoranları", a: "restoran", c: "İstanbul",
      d: "Makarna ve pizzanın İstanbul'daki en iyi örnekleri.",
      m: ["Da Mario", "Fiamma", "Osteria Astoria", "Pizzeria Napoli", "Il Piccolo", "Trattoria Enzo", "Marchigiana", "Bella Vista", "Pizza Locale", "Vinifera"] },
    { t: "En İyi Vegan ve Vejetaryen Restoranlar", a: "restoran", c: "İstanbul",
      d: "Etsiz beslenenler için İstanbul'un en iyi mutfakları.",
      m: ["Zencefil", "Community Kitchen", "Bi Nevi Deli", "Vegan İstanbul", "Parsley", "Roka Vegan", "Nature's Own", "Yeşil Mutfak", "Vegan Dükkan", "Sarnıç Vegan"] },
    { t: "En İyi Burgerciler", a: "restoran", c: "İstanbul",
      d: "Smash'ten klasik köfteye burgerin İstanbul haritası.",
      m: ["Nusr-Et Burger", "Kizilkayalar", "Bigudi Burger", "Craft Burger", "Ferah Burger", "Burger Lab", "Grand Burger", "Beef Brothers", "Smash Burger İstanbul", "Bull Burger"] },
    { t: "En İyi Mantı Yapan Mekanlar", a: "restoran",
      d: "Kayseri usulünden Çin mantısına en iyi mantıcılar.",
      m: ["Bodrum Mantı", "Kayseri Mantıcısı", "Fıccın", "Sultanahmet Mantıcısı", "Anadolu Mantı Evi", "Hüsrev Mantı", "Erciyes Mantı", "Mantı Dünyası", "Nur Mantı", "Baba Mantı"] },
    { t: "Türkiye'nin En İyi Çorbacıları", a: "restoran",
      d: "Sabahın ilk saatlerinde ya da gece yarısı çorba içilecek yerler.",
      m: ["Lale İşkembecisi", "Kadıköy Çorbacısı", "Şükran Çorba", "Beyran Salonu Antep", "Tarihi Sultanahmet Çorbacısı", "Gaziantep Beyran Evi", "Ankara İşkembecisi", "Konya Bamya Çorbası", "Kelle Paça Salonu", "Ezogelin Çorba Evi"] },
    { t: "En İyi Deniz Manzaralı Restoranlar", a: "restoran",
      d: "Yemekten çok manzara için gidilen mekanlar.",
      m: ["Rumeli İskele", "Poseidon Bebek", "Lacivert Restaurant", "Kıyı Tarabya", "Del Mare", "Feriye Lokantası", "Beach Club Bodrum", "Alaçatı Marina Restaurant", "Kaş Sahil Restaurant", "Çeşme Deniz Restoran"] },
    { t: "En İyi Kokoreççiler", a: "restoran",
      d: "Kokoreç sevenlerin bildiği adresler.",
      m: ["Şampiyon Kokoreç", "Bilice Kokoreç", "Kokoreççi Ahmet Usta", "Kral Kokoreç", "Bereket Kokoreç", "Balat Kokoreç", "Rumeli Kokoreç", "Yıldız Kokoreç", "Kadıköy Kokoreççisi", "Beşiktaş Kokoreç"] },
    { t: "En İyi Uzak Doğu Restoranları", a: "restoran", c: "İstanbul",
      d: "Suşi, ramen ve wok mutfağının İstanbul'daki en iyileri.",
      m: ["Sushico", "Zuma İstanbul", "Banyan", "Kirpi Sushi", "Miyako", "Wagamama İstanbul", "Ramen Ya", "Dragon Restaurant", "Sushi Ai", "Tokyo İstanbul"] },

    // ---- Tatlı ----
    { t: "Türkiye'nin En İyi Baklavacıları", a: "tatli",
      d: "Antep fıstığı ve tereyağının en iyi buluştuğu yerler.",
      m: ["Karaköy Güllüoğlu", "İmam Çağdaş", "Koçak Baklava", "Hafız Mustafa 1864", "Faruk Güllüoğlu", "Seyidoğlu", "Baklavacı Gaziantepli", "Bolulu Hasan Usta", "Zeynel Usta", "Nurcan Baklava"] },
    { t: "En İyi Dondurmacılar", a: "tatli",
      d: "Maraş usulünden İtalyan gelatoya en iyi dondurmacılar.",
      m: ["Mado", "Ali Usta Dondurma", "Yaşar Usta", "Dondurmacı Ali Usta Moda", "Mini Dondurma", "Edo Dondurma", "Cremeria Milano", "Gelateria Napoli", "Bilice Dondurma", "Maraş Dondurmacısı"] },
    { t: "İstanbul'un En İyi Pastaneleri", a: "tatli", c: "İstanbul",
      d: "Yaş pasta, kurabiye ve tatlı için köklü adresler.",
      m: ["Divan Pastanesi", "İnci Pastanesi", "Beyaz Fırın", "Baylan Pastanesi", "Özsüt", "Saray Muhallebicisi", "Hafız Mustafa 1864", "Cafe Nero Pastane", "Petek Pastanesi", "Nişantaşı Pastanesi"] },
    { t: "En İyi Künefeciler", a: "tatli",
      d: "Hatay usulü peynirli künefenin en iyi adresleri.",
      m: ["Hatay Medeniyetler Sofrası", "Antakya Künefecisi", "Künefeci Zeki Usta", "Şahin Künefe", "Hatay Sofrası", "Künefe Durağı", "Beyoğlu Künefecisi", "Adana Künefe Salonu", "Sarayaltı Künefe", "Öz Antakya Künefe"] },
    { t: "En İyi Muhallebiciler", a: "tatli",
      d: "Kazandibi, tavuk göğsü ve sütlaç için en iyi mekanlar.",
      m: ["Saray Muhallebicisi", "Özsüt", "Emirgan Sütiş", "Sütiş", "Kanaat Lokantası", "Bebek Muhallebicisi", "Beyoğlu Muhallebicisi", "Anadolu Muhallebicisi", "Kadıköy Sütçüsü", "Tarihi Muhallebici"] },
    { t: "En İyi Çikolata Markaları ve Butikleri", a: "tatli",
      d: "Hediyelik ve kendine ikram için çikolata adresleri.",
      m: ["Kahve Dünyası Çikolata", "Godiva Türkiye", "Bind Çikolata", "Elit Çikolata", "Melodi Çikolata", "Chocolab", "Vakko Chocolate", "Divan Çikolata", "Şölen", "Nestlé Damak"] },

    // ---- Sokak lezzeti ----
    { t: "İstanbul'un En İyi Sokak Lezzetleri", a: "sokak-lezzeti", c: "İstanbul",
      d: "Ayaküstü yenen ama unutulmayan lezzetler.",
      m: ["Balık ekmek Eminönü", "Kokoreç", "Midye dolma", "Kumpir Ortaköy", "Simit", "Tantuni", "Islak hamburger Taksim", "Nohutlu pilav", "Çiğ köfte", "Boyoz"] },
    { t: "En İyi Tantuniciler", a: "sokak-lezzeti",
      d: "Mersin usulü tantuninin en iyi adresleri.",
      m: ["Mersin Tantuni", "Bereket Tantuni", "Cumhuriyet Tantuni", "Ali Usta Tantuni", "Tarsus Tantunicisi", "Öz Mersin Tantuni", "Adana Tantuni Evi", "Tantuni Durağı", "Şanlıurfa Tantuni", "Meşhur Tantunici"] },
    { t: "En İyi Çiğ Köfteciler", a: "sokak-lezzeti",
      d: "Etsiz çiğ köftenin zincir ve butik adresleri.",
      m: ["Komagene", "Çiğköftem", "Oses Çiğ Köfte", "Kasap Osman Çiğ Köfte", "Adıyaman Çiğ Köftecisi", "Urfa Çiğ Köfte Evi", "Nurcan Çiğ Köfte", "Bereket Çiğ Köfte", "Antep Çiğ Köftecisi", "Köfteci Yusuf Çiğ Köfte"] },
    { t: "En İyi Midyeci ve Balık Ekmekçiler", a: "sokak-lezzeti", c: "İstanbul",
      d: "Sahil kenarında ayaküstü deniz lezzetleri.",
      m: ["Eminönü Balık Ekmek", "Karaköy Balıkçısı", "Midyeci Ahmet", "Bebek Midyecisi", "Kadıköy Midyecisi", "Ortaköy Balık Ekmek", "Sarıyer Balıkçısı", "Beşiktaş Midyecisi", "Çengelköy Balık Ekmek", "Kumkapı Midyecisi"] },

    // ---- Otel ----
    { t: "İstanbul'un En İyi Butik Otelleri", a: "otel", c: "İstanbul",
      d: "Büyük zincirler yerine karakterli konaklama arayanlar için.",
      m: ["Soho House İstanbul", "Georges Hotel Galata", "Vault Karakoy", "The House Hotel Bosphorus", "Witt Istanbul Suites", "Tomtom Suites", "Hotel Empress Zoe", "Sirkeci Mansion", "Karakoy Rooms", "Ajwa Hotel Sultanahmet"] },
    { t: "Kapadokya'nın En İyi Mağara Otelleri", a: "otel", c: "Nevşehir",
      d: "Peri bacaları manzaralı taş ve mağara otelleri.",
      m: ["Museum Hotel", "Argos in Cappadocia", "Sultan Cave Suites", "Kayakapi Premium Caves", "Mithra Cave Hotel", "Seraphim Cave Suites", "Carus Cappadocia", "Hezen Cave Hotel", "Ariana Sustainable Luxury Lodge", "Sacred House"] },
    { t: "Bodrum'un En İyi Otelleri", a: "otel", c: "Muğla",
      d: "Koy manzaralı ve butik Bodrum konaklamaları.",
      m: ["Maxx Royal Bodrum", "Mandarin Oriental Bodrum", "The Bodrum EDITION", "Lujo Hotel", "Caresse Bodrum", "Kempinski Barbaros Bay", "Swissôtel Resort Bodrum", "Casa Dell'Arte", "Bodrum Loft", "Voyage Torba"] },
    { t: "Antalya'nın En İyi Tatil Köyleri", a: "otel", c: "Antalya",
      d: "Her şey dahil konseptte öne çıkan Antalya tesisleri.",
      m: ["Maxx Royal Belek", "Regnum Carya", "Rixos Premium Belek", "Titanic Deluxe Golf Belek", "Calista Luxury Resort", "Cornelia Diamond", "Gloria Serenity Resort", "Ela Excellence Resort", "Voyage Belek", "Susesi Luxury Resort"] },
    { t: "En İyi Dağ Evi ve Bungalov Tesisleri", a: "otel",
      d: "Doğayla iç içe küçük ölçekli konaklama.",
      m: ["Ağva Bungalov Evleri", "Abant Dağ Evleri", "Kartepe Bungalov", "Uzungöl Bungalov", "Ayder Dağ Evi", "Sapanca Bungalov", "Kaz Dağları Bungalov", "Fethiye Faralya Bungalov", "Olimpos Ağaç Evler", "Camlihemsin Bungalov"] },
    { t: "İş Seyahati İçin En İyi Şehir Otelleri", a: "otel",
      d: "Toplantı, konum ve internet dengesi iyi oteller.",
      m: ["Swissôtel The Bosphorus", "Hilton İstanbul Bomonti", "Sheraton Ankara", "Wyndham Grand İzmir", "Radisson Blu Şişli", "Movenpick İstanbul", "Divan İstanbul", "JW Marriott Ankara", "Crowne Plaza İzmir", "Holiday Inn Ankara"] },
    { t: "En İyi Termal Oteller", a: "otel",
      d: "Kaplıca ve termal suyla dinlenme tesisleri.",
      m: ["Afyon Sandıklı Termal", "Kervansaray Termal Bursa", "Yalova Termal Otel", "Balçova Termal İzmir", "Gönen Kaplıcaları", "Pamukkale Termal", "Kızılcahamam Asya Termal", "Haymana Termal", "Oruçoğlu Termal Afyon", "Sivas Balıklı Kaplıca"] },

    // ---- Plaj ----
    { t: "Türkiye'nin En Güzel Plajları", a: "plaj",
      d: "Deniz, kum ve manzara üçlüsünde en iyileri.",
      m: ["Ölüdeniz", "Kaputaş Plajı", "Patara Plajı", "İztuzu Plajı", "Kabak Koyu", "Çıralı Plajı", "Altınkum Çeşme", "Kleopatra Plajı", "Akyaka Plajı", "Saklıkent Koyu"] },
    { t: "Ege'nin En İyi Koyları", a: "plaj",
      d: "Tekneyle ya da karadan ulaşılan berrak koylar.",
      m: ["Kabak Koyu", "Gebekse Koyu", "Boncuk Koyu", "Sedir Adası", "Bördübet Koyu", "Kargı Koyu", "Akbük Koyu", "Değirmenbükü", "Aquarium Koyu", "Fosforlu Mağara Koyu"] },
    { t: "Çeşme ve Alaçatı'nın En İyi Plajları", a: "plaj", c: "İzmir",
      d: "Rüzgâr sörfünden aile plajına Çeşme sahilleri.",
      m: ["Ilıca Plajı", "Altınkum Plajı", "Ayayorgi Koyu", "Alaçatı Sörf Cenneti", "Pırlanta Plajı", "Delikli Koy", "Boyalık Plajı", "Tekke Plajı", "Aya Yorgi Bay", "Şifne Plajı"] },
    { t: "Antalya'nın En İyi Plajları", a: "plaj", c: "Antalya",
      d: "Konyaaltı'ndan Kaş'a Akdeniz sahilleri.",
      m: ["Konyaaltı Plajı", "Lara Plajı", "Kaputaş Plajı", "Çıralı Plajı", "Patara Plajı", "Adrasan Koyu", "Kleopatra Plajı", "Olimpos Plajı", "Kalkan Plajı", "Side Plajı"] },
    { t: "Karadeniz'in En İyi Plajları", a: "plaj",
      d: "Serin sularıyla Karadeniz kıyısında yüzme noktaları.",
      m: ["Şile Ağlayan Kaya", "Kilyos Plajı", "Amasra Plajı", "Sinop Akliman", "Ordu Perşembe Plajı", "Giresun Çaldağ Plajı", "Kefken Kerpe Plajı", "Ünye Plajı", "Akçakoca Plajı", "Karasu Plajı"] },
    { t: "Çocuklu Aileler İçin En Uygun Plajlar", a: "plaj",
      d: "Sığ, dalgasız ve gölgelikli plajlar.",
      m: ["Akyaka Plajı", "Sarıgerme Plajı", "Side Plajı", "Ilıca Çeşme", "Fethiye Çalış Plajı", "Didim Altınkum", "Kuşadası Ladies Beach", "Avşa Adası Plajı", "Erdek Plajı", "Gümüldür Plajı"] },

    // ---- Doğa ----
    { t: "Türkiye'nin En Güzel Doğa Rotaları", a: "doga",
      d: "Yürüyüş ve kamp için en iyi doğa parkurları.",
      m: ["Likya Yolu", "Kaçkar Dağları", "Kapadokya Kızılçukur", "Karadeniz Yaylalar Rotası", "Kaz Dağları", "Aladağlar", "Küre Dağları", "Yedigöller", "Nemrut Dağı", "Ihlara Vadisi"] },
    { t: "En İyi Kamp Alanları", a: "doga",
      d: "Çadır ve karavanla konaklanabilecek doğa alanları.",
      m: ["Olimpos Kamp Alanı", "Ayder Yaylası Kampı", "Kaz Dağları Kamp", "Saklıkent Kampı", "Kabak Koyu Kamp", "Yedigöller Kamp Alanı", "Abant Kamp", "Kapuzbaşı Şelaleleri", "Datça Kamp", "Gökçeada Kamp Alanı"] },
    { t: "En Güzel Yaylalar", a: "doga",
      d: "Karadeniz'den Toroslara yayla rotaları.",
      m: ["Ayder Yaylası", "Pokut Yaylası", "Sal Yaylası", "Huser Yaylası", "Kümbet Yaylası", "Bektaş Yaylası", "Gito Yaylası", "Sultanmurat Yaylası", "Çambaşı Yaylası", "Perşembe Yaylası"] },
    { t: "Türkiye'nin En Etkileyici Şelaleleri", a: "doga",
      d: "Fotoğraf ve serinlemek için şelale rotaları.",
      m: ["Düden Şelalesi", "Manavgat Şelalesi", "Kurşunlu Şelalesi", "Tortum Şelalesi", "Kapuzbaşı Şelaleleri", "Erfelek Şelaleleri", "Muradiye Şelalesi", "Gelin Tülü Şelalesi", "Sudüşen Şelalesi", "Değirmenlik Şelalesi"] },
    { t: "En Güzel Göller", a: "doga",
      d: "Kamp, fotoğraf ve gün batımı için göl rotaları.",
      m: ["Salda Gölü", "Abant Gölü", "Van Gölü", "Uzungöl", "Eğirdir Gölü", "Beyşehir Gölü", "Sapanca Gölü", "Nemrut Krater Gölü", "Yedigöller", "Bafa Gölü"] },
    { t: "En İyi Trekking Rotaları", a: "doga",
      d: "Uzun mesafe yürüyüş sevenler için işaretli rotalar.",
      m: ["Likya Yolu", "Kral Yolu", "Karia Yolu", "Frig Vadisi Yolu", "Evliya Çelebi Yolu", "Sultanlar Yolu", "Hitit Yolu", "Aziz Paul Yolu", "Kaçkar Geçiş Rotası", "Ihlara Vadisi Yürüyüşü"] },
    { t: "Sonbaharda Gidilecek En Güzel Yerler", a: "doga",
      d: "Yaprak dökümü ve sis için sonbahar rotaları.",
      m: ["Yedigöller", "Abant", "Safranbolu", "Kaz Dağları", "Uzungöl", "Kartepe", "Bolu Gölcük", "Sapanca", "Karagöl Artvin", "Ihlara Vadisi"] },
    { t: "Kışın Gidilecek En İyi Kayak Merkezleri", a: "doga",
      d: "Pist kalitesi ve konaklamasıyla kayak merkezleri.",
      m: ["Palandöken", "Uludağ", "Kartalkaya", "Erciyes", "Kartepe", "Sarıkamış", "Davraz", "Ilgaz", "Ergan Dağı", "Bozdağ"] },

    // ---- Tarih ----
    { t: "Türkiye'nin En Etkileyici Antik Kentleri", a: "tarih",
      d: "Gezilecek en iyi korunmuş antik yerleşimler.",
      m: ["Efes", "Afrodisias", "Perge", "Hierapolis", "Aspendos", "Bergama", "Patara", "Sagalassos", "Priene", "Olimpos"] },
    { t: "İstanbul'un Mutlaka Görülmesi Gereken Tarihî Yapıları", a: "tarih", c: "İstanbul",
      d: "Şehrin siluetini oluşturan yapılar.",
      m: ["Ayasofya", "Topkapı Sarayı", "Sultanahmet Camii", "Yerebatan Sarnıcı", "Dolmabahçe Sarayı", "Süleymaniye Camii", "Galata Kulesi", "Kariye Camii", "Rumeli Hisarı", "Kapalıçarşı"] },
    { t: "Türkiye'nin UNESCO Dünya Mirası Listesindeki Yerleri", a: "tarih",
      d: "Uluslararası koruma altındaki kültürel miras alanları.",
      m: ["Göbeklitepe", "Kapadokya", "Pamukkale-Hierapolis", "Efes", "Safranbolu", "Truva Antik Kenti", "Nemrut Dağı", "Divriği Ulu Camii", "Çatalhöyük", "Bursa ve Cumalıkızık"] },
    { t: "En Güzel Osmanlı Camileri", a: "tarih",
      d: "Mimar Sinan ve sonrası dönemin başyapıtları.",
      m: ["Selimiye Camii", "Süleymaniye Camii", "Sultanahmet Camii", "Şehzade Camii", "Rüstem Paşa Camii", "Yeni Camii", "Ulu Camii Bursa", "Yeşil Camii", "Sokollu Mehmet Paşa Camii", "Mihrimah Sultan Camii"] },
    { t: "En Güzel Tarihî Kentler ve Kasabalar", a: "tarih",
      d: "Sokak dokusu korunmuş yerleşimler.",
      m: ["Safranbolu", "Amasya", "Beypazarı", "Şirince", "Cumalıkızık", "Mardin", "Odunpazarı", "Göynük", "Taraklı", "Akseki"] },
    { t: "Türkiye'nin En Güzel Kaleleri", a: "tarih",
      d: "Manzarası ve tarihiyle öne çıkan kaleler.",
      m: ["Rumeli Hisarı", "Bodrum Kalesi", "Ankara Kalesi", "Alanya Kalesi", "Mardin Kalesi", "Anadolu Hisarı", "Amasra Kalesi", "Kız Kalesi", "Van Kalesi", "Harput Kalesi"] },
    { t: "En Güzel Kervansaraylar ve Hanlar", a: "tarih",
      d: "İpek Yolu üzerindeki Selçuklu ve Osmanlı yapıları.",
      m: ["Sultanhanı Kervansarayı", "Ağzıkarahan", "Sarıhan", "Alarahan", "Zazadin Han", "Büyük Valide Han", "Koza Han", "Rüstem Paşa Kervansarayı", "Öresun Han", "İncir Han"] },
    { t: "Mardin ve Güneydoğu'da Görülmesi Gereken Yerler", a: "tarih", c: "Mardin",
      d: "Taş mimari ve mezopotamya manzarası.",
      m: ["Mardin Eski Şehir", "Deyrulzafaran Manastırı", "Dara Antik Kenti", "Zinciriye Medresesi", "Kasımiye Medresesi", "Midyat Konakları", "Hasankeyf", "Göbeklitepe", "Balıklıgöl", "Halfeti"] },

    // ---- Müze ----
    { t: "Türkiye'nin En İyi Müzeleri", a: "muze",
      d: "Koleksiyonu ve sunumuyla öne çıkan müzeler.",
      m: ["Anadolu Medeniyetleri Müzesi", "Topkapı Sarayı Müzesi", "İstanbul Arkeoloji Müzeleri", "Zeugma Mozaik Müzesi", "Göbeklitepe Ziyaretçi Merkezi", "Efes Müzesi", "Antalya Müzesi", "Mevlana Müzesi", "Troya Müzesi", "Sadberk Hanım Müzesi"] },
    { t: "İstanbul'un En İyi Sanat Galerileri ve Modern Müzeleri", a: "muze", c: "İstanbul",
      d: "Çağdaş sanat sergileri için en iyi mekanlar.",
      m: ["İstanbul Modern", "Pera Müzesi", "Sakıp Sabancı Müzesi", "Arter", "Salt Beyoğlu", "Borusan Contemporary", "SALT Galata", "Elgiz Müzesi", "Akbank Sanat", "Meşher"] },
    { t: "Çocuklarla Gezilecek En İyi Müzeler", a: "muze",
      d: "İnteraktif ve deneyimsel müzeler.",
      m: ["Rahmi M. Koç Müzesi", "İstanbul Oyuncak Müzesi", "Bilim Merkezi Konya", "Feza Gürsey Bilim Merkezi", "İTÜ Bilim Merkezi", "Bursa Enerji Müzesi", "Kocaeli Bilim Merkezi", "Miniatürk", "Panorama 1453", "Deniz Müzesi"] },
    { t: "En İyi Açık Hava Müzeleri", a: "muze",
      d: "Doğayla iç içe müze deneyimi.",
      m: ["Göreme Açık Hava Müzesi", "Zelve Açık Hava Müzesi", "Efes Antik Kenti", "Hierapolis Antik Kenti", "Aspendos Tiyatrosu", "Perge Antik Kenti", "Side Antik Kenti", "Bergama Akropolü", "Sagalassos", "Afrodisias"] },
    { t: "Ankara'da Gezilecek Müzeler", a: "muze", c: "Ankara",
      d: "Başkentin müze rotası.",
      m: ["Anadolu Medeniyetleri Müzesi", "Anıtkabir Müzesi", "Etnografya Müzesi", "Cer Modern", "Ankara Devlet Resim Heykel Müzesi", "Rahmi Koç Müzesi Ankara", "MTA Tabiat Tarihi Müzesi", "Kurtuluş Savaşı Müzesi", "Cumhuriyet Müzesi", "Feza Gürsey Bilim Merkezi"] },
    { t: "En İyi Ev Müzeleri ve Konaklar", a: "muze",
      d: "Yazar, sanatçı ve devlet adamı evleri.",
      m: ["Masumiyet Müzesi", "Atatürk Köşkü Trabzon", "Aşiyan Müzesi", "Sait Faik Müze Evi", "Yahya Kemal Müzesi", "Rahmi Koç Konağı", "Ahmet Hamdi Tanpınar Edebiyat Müzesi", "Zübeyde Hanım Evi", "Nazım Hikmet Kültür Merkezi", "Hüseyin Rahmi Gürpınar Evi"] },

    // ---- Park ----
    { t: "İstanbul'un En Güzel Parkları", a: "park", c: "İstanbul",
      d: "Yürüyüş, piknik ve nefes almak için.",
      m: ["Emirgan Korusu", "Yıldız Parkı", "Maçka Demokrasi Parkı", "Gülhane Parkı", "Fethi Paşa Korusu", "Belgrad Ormanı", "Atatürk Kent Ormanı", "Hidiv Kasrı Korusu", "Göztepe 60. Yıl Parkı", "Küçüksu Çayırı"] },
    { t: "Ankara'nın En İyi Parkları", a: "park", c: "Ankara",
      d: "Başkentte yeşil alanlar.",
      m: ["Seğmenler Parkı", "Kuğulu Park", "Gençlik Parkı", "Botanik Park", "Dikmen Vadisi", "Harikalar Diyarı", "Altınpark", "Göksu Parkı", "Kurtuluş Parkı", "ODTÜ Ormanı"] },
    { t: "İzmir'in En İyi Sahil ve Park Alanları", a: "park", c: "İzmir",
      d: "Kordon ve çevresinde yürüyüş rotaları.",
      m: ["Kordon", "Kültürpark", "Bostanlı Sahili", "İnciraltı Kent Ormanı", "Sasalı Doğal Yaşam Parkı", "Karşıyaka Sahili", "Gündoğdu Meydanı", "Bayraklı Sahil Parkı", "Çiğli Kuş Cenneti", "Homeros Vadisi"] },
    { t: "Piknik İçin En İyi Yerler", a: "park",
      d: "Şehre yakın piknik ve mangal alanları.",
      m: ["Belgrad Ormanı", "Polonezköy Tabiat Parkı", "Aydos Ormanı", "Fatih Ormanı", "Kemerburgaz Kent Ormanı", "Abant Tabiat Parkı", "Kartepe Piknik Alanı", "Sapanca Kırkpınar", "Uludağ Piknik Alanları", "Beynam Ormanı"] },
    { t: "Köpekli Gezilebilecek En İyi Yerler", a: "park", c: "İstanbul",
      d: "Dostlarıyla birlikte gezmek isteyenler için.",
      m: ["Maçka Demokrasi Parkı", "Belgrad Ormanı", "Caddebostan Sahili", "Emirgan Korusu", "Küçüksu Çayırı", "Validebağ Korusu", "Kilyos Sahili", "Yoğurtçu Parkı", "Fenerbahçe Parkı", "Cendere Vadisi"] },

    // ---- Gece hayatı ----
    { t: "İstanbul'un En İyi Kokteyl Barları", a: "gece", c: "İstanbul",
      d: "Bar programını ciddiye alan mekanlar.",
      m: ["Alexandra Cocktail Bar", "The Populist", "Under Bar", "Geyik Coffee & Cocktail", "Nu Teras", "Arkaoda", "Karabatak", "Bej Bar", "Foxy Nişantaşı", "Lucca Bar"] },
    { t: "En İyi Canlı Müzik Mekanları", a: "gece", c: "İstanbul",
      d: "Konser ve canlı performans için sahneler.",
      m: ["Babylon", "Zorlu PSM", "IF Performance Hall", "Hayal Kahvesi", "Nardis Jazz Club", "Peyote", "Dorock XL", "Bronx Pi Sahne", "Kadıköy Sahne", "Salon İKSV"] },
    { t: "En İyi Meyhaneler", a: "gece", c: "İstanbul",
      d: "Meze ve rakı geleneğini sürdüren mekanlar.",
      m: ["Asmalı Cavit", "Yakup 2", "Krependeki İmroz", "Sofyalı 9", "Cumhuriyet Meyhanesi", "Boncuk Restaurant", "Refik Restaurant", "Nevizade Meyhaneleri", "Kadıköy Çiya Meyhane", "Beyti Meyhane"] },
    { t: "En İyi Craft Bira Mekanları", a: "gece", c: "İstanbul",
      d: "Bağımsız bira üreticilerini bulabileceğiniz barlar.",
      m: ["Craft Beer Lab", "Bomonti Bira Fabrikası", "Gara Guzu Bar", "Pablo Craft Beer", "Beer Hall Kadıköy", "Hops Bar", "Malt Bar", "The Beer Shop", "Bira Atölyesi", "Fermente Bar"] },
    { t: "Rooftop Manzaralı En İyi Barlar", a: "gece", c: "İstanbul",
      d: "Şehir ve Boğaz manzaralı teraslar.",
      m: ["Mikla Terrace", "360 İstanbul", "Nu Teras", "Banyan Terrace", "Leb-i Derya", "Peninsula Rooftop", "Ulus 29", "Gaspar Rooftop", "Sky Bar Marmara", "Kubbe İstanbul"] },
    { t: "Ankara'nın En İyi Gece Mekanları", a: "gece", c: "Ankara",
      d: "Başkentte akşam programı yapanlar için.",
      m: ["Jolly Joker Ankara", "IF Performance Ankara", "Kavaklıdere Bar Sokağı", "Tunalı Bar Hattı", "Sixth Bar", "Bomonti Ankara", "Nefes Bar", "Beat Bar", "Corvus Pub", "Havana Bar"] },
    { t: "İzmir'in En İyi Barları", a: "gece", c: "İzmir",
      d: "Alsancak ve çevresinde gece hayatı.",
      m: ["Kıbrıs Şehitleri Bar Sokağı", "Sardunya Bar", "Punto Bar", "Bordo Bar", "Gizli Bahçe", "Vinyl Bar", "Cadde Bar", "Alsancak Rock Bar", "Bosca Bar", "Marina Bar İzmir"] },
    { t: "En İyi Nargile Kafeleri", a: "gece", c: "İstanbul",
      d: "Tarihî ve manzaralı nargile mekanları.",
      m: ["Tophane Nargile Kafeleri", "Erenler Çay Bahçesi", "Çorlulu Ali Paşa Medresesi", "Pierre Loti Tepesi", "Kadıköy Nargile Sokağı", "Bebek Nargile", "Sarıyer Nargile Bahçesi", "Üsküdar Sahil Nargile", "Balat Nargile", "Fatih Nargile Evi"] },

    // ---- Alışveriş ----
    { t: "İstanbul'un En İyi Alışveriş Merkezleri", a: "alisveris", c: "İstanbul",
      d: "Marka çeşitliliği ve deneyimiyle öne çıkan AVM'ler.",
      m: ["İstinye Park", "Zorlu Center", "Akasya AVM", "Kanyon", "Emaar Square Mall", "Mall of İstanbul", "Vadi İstanbul", "Cevahir AVM", "Palladium Ataşehir", "Metropol İstanbul"] },
    { t: "En İyi Tarihî Çarşılar ve Pazarlar", a: "alisveris",
      d: "Alışverişin geleneksel adresleri.",
      m: ["Kapalıçarşı", "Mısır Çarşısı", "Arasta Çarşısı", "Bursa Koza Han", "Kemeraltı Çarşısı", "Safranbolu Arasta", "Beypazarı Çarşısı", "Mardin Çarşısı", "Kayseri Kapalı Çarşı", "Gaziantep Bakırcılar Çarşısı"] },
    { t: "En İyi Semt Pazarları", a: "alisveris", c: "İstanbul",
      d: "Meyve, sebze ve tekstil için haftalık pazarlar.",
      m: ["Kadıköy Salı Pazarı", "Beşiktaş Cumartesi Pazarı", "Feriköy Organik Pazar", "Ulus Pazarı", "Bakırköy Pazarı", "Şişli Perşembe Pazarı", "Üsküdar Pazarı", "Fatih Çarşamba Pazarı", "Bostancı Pazarı", "Maltepe Pazarı"] },
    { t: "En İyi Kitapçılar ve Sahaflar", a: "alisveris", c: "İstanbul",
      d: "Uzun uzun gezilecek kitap mekanları.",
      m: ["Sahaflar Çarşısı", "Robinson Crusoe 389", "Pandora Kitabevi", "Minoa Beyoğlu", "Mephisto", "İstanbul Kitapçısı", "Kadıköy Sahaflar", "Homer Kitabevi", "D&R Zorlu", "Nezih Kitabevi"] },
    { t: "En İyi Kasap ve Şarküteriler", a: "alisveris", c: "İstanbul",
      d: "Kaliteli et ve peynir alışverişi.",
      m: ["Namlı Gurme", "Günaydın Kasap", "Kasap Osman", "Şarküteri Beyoğlu", "Antre Gourmet", "Aslan Kasap", "Zeytinburnu Kasap", "Bebek Şarküteri", "Nişantaşı Şarküteri", "Karaköy Kasabı"] },
    { t: "En İyi Antika ve İkinci El Dükkanları", a: "alisveris", c: "İstanbul",
      d: "Vintage eşya ve koleksiyon meraklıları için.",
      m: ["Çukurcuma Antikacıları", "Horhor Bit Pazarı", "Feriköy Antika Pazarı", "Balat Antikacıları", "Kadıköy Vintage", "Beyoğlu İkinci El", "Galata Antika", "Şişli Antikacılar", "Üsküdar Eskici", "Ortaköy Bit Pazarı"] },

    // ---- Çalışma ----
    { t: "En İyi Ortak Çalışma Alanları", a: "calisma", c: "İstanbul",
      d: "Serbest çalışanlar ve küçük ekipler için ofisler.",
      m: ["Kolektif House", "Impact Hub İstanbul", "Workinton", "Regus İstanbul", "Loft Coworking", "Atölye İstanbul", "Cowork İstanbul", "Nest Coworking", "Spaces Levent", "Hub Karaköy"] },
    { t: "Ankara'nın En İyi Çalışma Mekanları", a: "calisma", c: "Ankara",
      d: "Başkentte ders ve iş için sessiz mekanlar.",
      m: ["Kolektif House Ankara", "Workinton Ankara", "ODTÜ Teknokent", "Bilkent Cyberpark", "Milli Kütüphane", "Cer Modern Kafe", "Ankara Kitap Kafe", "Beytepe Kütüphane", "Regus Ankara", "Nest Ankara"] },
    { t: "En İyi Halk Kütüphaneleri", a: "calisma",
      d: "Ücretsiz ve sessiz çalışma alanları.",
      m: ["Beyazıt Devlet Kütüphanesi", "Millet Kütüphanesi", "Atatürk Kitaplığı", "Milli Kütüphane Ankara", "Rami Kütüphanesi", "İzmir Milli Kütüphane", "Nermin Tarhan Kütüphanesi", "Bursa Devlet Kütüphanesi", "Konya Yusuf Ağa Kütüphanesi", "Adana İl Halk Kütüphanesi"] },
    { t: "Uzaktan Çalışanlar İçin En İyi Şehirler", a: "calisma",
      d: "İnternet, maliyet ve yaşam kalitesi dengesi.",
      m: ["İzmir", "Antalya", "Eskişehir", "Muğla", "Ankara", "Bursa", "Çanakkale", "Trabzon", "Isparta", "Balıkesir"] },

    // ---- Spor ----
    { t: "En İyi Koşu Parkurları", a: "spor", c: "İstanbul",
      d: "Şehir içinde düzenli koşu için rotalar.",
      m: ["Caddebostan Sahili", "Belgrad Ormanı", "Maçka Parkı", "Kalamış Sahili", "Bebek Sahil Yolu", "Florya Sahili", "Ataköy Sahil Parkuru", "Yıldız Parkı", "Cendere Vadisi", "Büyükçekmece Sahili"] },
    { t: "En İyi Bisiklet Rotaları", a: "spor",
      d: "Şehir içi ve doğa bisiklet parkurları.",
      m: ["Adalar Turu", "İzmir Kordon Bisiklet Yolu", "Sapanca Gölü Turu", "Şile-Ağva Rotası", "Gökçeada Turu", "Uzungöl Rotası", "Datça Yarımadası", "Konya Bisiklet Yolu", "Bursa Uludağ Rotası", "Eskişehir Porsuk Rotası"] },
    { t: "En İyi Fitness ve Spor Salonu Zincirleri", a: "spor",
      d: "Şube sayısı ve ekipman kalitesiyle spor salonları.",
      m: ["MacFit", "Fit Lab", "Sports International", "B-Fit", "World Gym Türkiye", "Fitness Time", "Vega Fitness", "Hillside City Club", "Anytime Fitness", "Mars Athletic"] },
    { t: "En İyi Dalış Noktaları", a: "spor",
      d: "Berrak su ve batıklarıyla dalış merkezleri.",
      m: ["Kaş", "Ayvalık", "Bodrum", "Saros Körfezi", "Gökçeada", "Fethiye", "Kemer", "Datça", "Marmaris", "Antalya Kaleiçi"] },
  ],
};
