import type { KategoriIcerigi } from "./tipler";

/**
 * Ürün kategorisi — 100+ liste.
 * Alt kategoriler: telefon, bilgisayar, ses, giyilebilir, tv-goruntu,
 * foto, oyun-donanim, beyaz-esya, mutfak, ev, kisisel-bakim, kozmetik,
 * gida, icecek, bebek, evcil, otomotiv, spor-urun, ofis, hobi
 */
export const urun: KategoriIcerigi = {
  kategori: "urun",
  listeler: [
    // ---- Telefon ----
    { t: "2026'nın En İyi Amiral Gemisi Telefonları", a: "telefon",
      d: "Üst segmentte performans, kamera ve ekran dengesi.",
      m: ["iPhone 17 Pro Max", "Samsung Galaxy S26 Ultra", "Google Pixel 10 Pro", "Xiaomi 15 Ultra", "OnePlus 13", "Honor Magic 7 Pro", "Oppo Find X8 Pro", "Vivo X200 Pro", "Asus Zenfone 12 Ultra", "Nothing Phone (3)"] },
    { t: "En İyi Orta Segment Telefonlar", a: "telefon",
      d: "Fiyat-performans dengesi en iyi modeller.",
      m: ["Samsung Galaxy A56", "Xiaomi Redmi Note 14 Pro", "Google Pixel 9a", "Nothing Phone (2a)", "Poco X7 Pro", "Realme 13 Pro+", "Honor 200", "Oppo Reno 12", "Motorola Edge 50", "Tecno Camon 30"] },
    { t: "En İyi Bütçe Dostu Telefonlar", a: "telefon",
      d: "Uygun fiyatlı ama günlük kullanımda yeterli modeller.",
      m: ["Xiaomi Redmi 14C", "Samsung Galaxy A16", "Poco M6 Pro", "Realme C67", "Tecno Spark 20", "Infinix Hot 40", "Nokia G42", "Honor X7b", "Oppo A60", "Vivo Y28"] },
    { t: "En İyi Kameralı Telefonlar", a: "telefon",
      d: "Fotoğraf ve video kalitesinde öne çıkan modeller.",
      m: ["iPhone 17 Pro Max", "Google Pixel 10 Pro", "Xiaomi 15 Ultra", "Samsung Galaxy S26 Ultra", "Vivo X200 Pro", "Oppo Find X8 Pro", "Honor Magic 7 Pro", "Huawei Pura 70 Ultra", "Sony Xperia 1 VI", "OnePlus 13"] },
    { t: "En İyi Katlanabilir Telefonlar", a: "telefon",
      d: "Kitap ve kapaklı katlanabilir modeller.",
      m: ["Samsung Galaxy Z Fold 7", "Samsung Galaxy Z Flip 7", "Google Pixel Fold 2", "Honor Magic V3", "Oppo Find N5", "Huawei Mate X6", "Xiaomi Mix Fold 4", "Motorola Razr 50 Ultra", "Vivo X Fold 3", "Tecno Phantom V Fold"] },
    { t: "En Uzun Pil Ömrüne Sahip Telefonlar", a: "telefon",
      d: "Tek şarjla en uzun dayanan modeller.",
      m: ["Xiaomi Redmi Note 14 Pro", "Poco X7 Pro", "Samsung Galaxy M55", "Motorola Moto G Power", "Realme 13 Pro+", "iPhone 17 Pro Max", "Honor X9b", "Tecno Pova 6 Pro", "Infinix Note 40 Pro", "Oppo A3 Pro"] },
    { t: "En İyi Telefon Kılıfı Markaları", a: "telefon",
      d: "Koruma ve tasarım dengesi.",
      m: ["Spigen", "OtterBox", "Ringke", "ESR", "Nomad", "Caseology", "Anker", "UAG", "Baseus", "Mous"] },

    // ---- Bilgisayar ----
    { t: "En İyi Dizüstü Bilgisayarlar", a: "bilgisayar",
      d: "Genel kullanım ve iş için en iyi modeller.",
      m: ["MacBook Air M4", "MacBook Pro 14 M4", "Dell XPS 14", "Lenovo ThinkPad X1 Carbon", "Asus Zenbook 14", "HP Spectre x360", "Framework Laptop 13", "LG Gram 16", "Acer Swift Go", "Huawei MateBook X Pro"] },
    { t: "En İyi Oyun Bilgisayarları", a: "bilgisayar",
      d: "Yüksek yenileme hızlı ekran ve güçlü ekran kartı.",
      m: ["Asus ROG Zephyrus G16", "Lenovo Legion Pro 7i", "Razer Blade 16", "MSI Titan 18 HX", "Alienware m18", "Acer Predator Helios 16", "HP Omen 16", "Gigabyte Aorus 17", "Monster Abra A7", "Casper Excalibur G911"] },
    { t: "En İyi Uygun Fiyatlı Dizüstü Bilgisayarlar", a: "bilgisayar",
      d: "Öğrenci ve ofis kullanımı için bütçe modelleri.",
      m: ["Lenovo IdeaPad Slim 3", "Asus Vivobook 15", "HP 250 G10", "Acer Aspire 3", "Casper Nirvana", "Monster Huma H5", "Dell Inspiron 15", "Huawei MateBook D15", "MSI Modern 15", "Lenovo V15"] },
    { t: "En İyi Ekran Kartları", a: "bilgisayar",
      d: "Oyun ve içerik üretimi için GPU sıralaması.",
      m: ["NVIDIA RTX 5090", "NVIDIA RTX 5080", "AMD Radeon RX 8900 XT", "NVIDIA RTX 5070 Ti", "AMD Radeon RX 8800 XT", "NVIDIA RTX 4070 Super", "Intel Arc B580", "AMD Radeon RX 7800 XT", "NVIDIA RTX 4060 Ti", "Intel Arc B570"] },
    { t: "En İyi İşlemciler", a: "bilgisayar",
      d: "Masaüstü sistemler için CPU karşılaştırması.",
      m: ["AMD Ryzen 9 9950X3D", "Intel Core Ultra 9 285K", "AMD Ryzen 7 9800X3D", "Intel Core Ultra 7 265K", "AMD Ryzen 5 9600X", "Apple M4 Max", "Intel Core i5-14600K", "AMD Ryzen 9 7950X", "Apple M4 Pro", "Intel Core i7-14700K"] },
    { t: "En İyi Monitörler", a: "bilgisayar",
      d: "Ofis, oyun ve tasarım için ekran seçimi.",
      m: ["LG UltraGear 27GR93U", "Dell UltraSharp U2723QE", "Samsung Odyssey OLED G8", "Apple Studio Display", "Asus ProArt PA279CRV", "BenQ PD2725U", "Gigabyte M32U", "MSI MAG 274UPF", "AOC U27P2", "Philips Evnia 34M2C"] },
    { t: "En İyi Klavyeler", a: "bilgisayar",
      d: "Mekanik ve ofis klavyeleri.",
      m: ["Keychron K2 Pro", "Logitech MX Keys", "Razer BlackWidow V4", "Apple Magic Keyboard", "Corsair K70 RGB", "Keychron Q1", "SteelSeries Apex Pro", "HyperX Alloy Origins", "Logitech G Pro X", "Ducky One 3"] },
    { t: "En İyi Mouse Modelleri", a: "bilgisayar",
      d: "Oyun ve verimlilik için fare seçenekleri.",
      m: ["Logitech MX Master 3S", "Razer DeathAdder V3 Pro", "Logitech G Pro X Superlight 2", "Apple Magic Mouse", "SteelSeries Aerox 5", "Corsair M75 Air", "Glorious Model O 2", "Zowie EC2-CW", "Microsoft Surface Precision", "Anker Vertical Mouse"] },
    { t: "En İyi Taşınabilir SSD'ler", a: "bilgisayar",
      d: "Hız ve dayanıklılıkla harici depolama.",
      m: ["Samsung T9", "SanDisk Extreme Pro", "Crucial X10 Pro", "WD My Passport SSD", "Kingston XS2000", "Lexar SL500", "Seagate FireCuda Gaming SSD", "Adata SE920", "Transcend ESD410C", "LaCie Rugged SSD Pro"] },
    { t: "En İyi Tabletler", a: "bilgisayar",
      d: "Not alma, çizim ve içerik tüketimi için.",
      m: ["iPad Pro M4", "iPad Air M3", "Samsung Galaxy Tab S10 Ultra", "iPad 11. nesil", "Xiaomi Pad 7 Pro", "Lenovo Tab P12 Pro", "Samsung Galaxy Tab S9 FE", "Huawei MatePad Pro", "OnePlus Pad 2", "Honor Pad 9"] },

    // ---- Ses ----
    { t: "En İyi Kablosuz Kulaklıklar", a: "ses",
      d: "Gürültü engelleme ve ses kalitesiyle öne çıkanlar.",
      m: ["Sony WH-1000XM6", "Apple AirPods Max", "Bose QuietComfort Ultra", "Sennheiser Momentum 4", "Sonos Ace", "Bowers & Wilkins Px8", "Technics EAH-A800", "JBL Tour One M2", "Anker Soundcore Space One", "Beats Studio Pro"] },
    { t: "En İyi Kablosuz Kulak İçi Kulaklıklar", a: "ses",
      d: "Günlük kullanım için TWS kulaklıklar.",
      m: ["AirPods Pro 3", "Sony WF-1000XM5", "Bose QuietComfort Earbuds II", "Samsung Galaxy Buds3 Pro", "Nothing Ear (a)", "Technics EAH-AZ80", "Anker Soundcore Liberty 4 NC", "Google Pixel Buds Pro 2", "Sennheiser Momentum True Wireless 4", "JBL Live Beam 3"] },
    { t: "En İyi Bütçe Dostu Kulaklıklar", a: "ses",
      d: "Uygun fiyata iyi ses veren modeller.",
      m: ["Anker Soundcore P40i", "QCY MeloBuds Pro", "Redmi Buds 6", "JBL Tune 520BT", "Baseus Bowie MA10", "Realme Buds Air 6", "Xiaomi Buds 5", "Edifier W820NB", "SoundPEATS Air4", "Honor Choice Earbuds X5"] },
    { t: "En İyi Bluetooth Hoparlörler", a: "ses",
      d: "Taşınabilir ve ev kullanımı için hoparlörler.",
      m: ["JBL Charge 6", "Sonos Roam 2", "Bose SoundLink Flex", "Marshall Emberton III", "Ultimate Ears Boom 4", "Anker Soundcore Motion 300", "Tribit StormBox Blast", "Bang & Olufsen Beosound A1", "Sony SRS-XG300", "Harman Kardon Onyx Studio 8"] },
    { t: "En İyi Ev Sinema Ses Sistemleri", a: "ses",
      d: "Soundbar ve çok kanallı sistemler.",
      m: ["Sonos Arc Ultra", "Samsung HW-Q990D", "Sony Bravia Theatre Bar 9", "LG S95TR", "Bose Smart Ultra Soundbar", "JBL Bar 1300X", "Denon Home Sound Bar 550", "Yamaha SR-B40A", "Sennheiser Ambeo Soundbar Plus", "Polk Audio MagniFi Max AX"] },
    { t: "En İyi Plak Çalarlar", a: "ses",
      d: "Analog ses meraklıları için pikaplar.",
      m: ["Audio-Technica AT-LP120XUSB", "Pro-Ject Debut Carbon EVO", "Rega Planar 1", "Technics SL-1500C", "Fluance RT85", "Sony PS-LX310BT", "Denon DP-300F", "Victrola Stream Onyx", "Music Hall Classic", "Thorens TD 102 A"] },
    { t: "En İyi Mikrofonlar", a: "ses",
      d: "Podcast, yayın ve kayıt için mikrofonlar.",
      m: ["Shure SM7B", "Rode PodMic", "Elgato Wave:3", "Audio-Technica AT2020", "Blue Yeti X", "Rode NT-USB+", "HyperX QuadCast S", "Shure MV7+", "Sennheiser Profile USB", "Samson Q2U"] },

    // ---- Giyilebilir ----
    { t: "En İyi Akıllı Saatler", a: "giyilebilir",
      d: "Sağlık takibi ve bildirim yönetimi.",
      m: ["Apple Watch Series 11", "Samsung Galaxy Watch 8", "Garmin Fenix 8", "Google Pixel Watch 4", "Apple Watch Ultra 3", "Huawei Watch GT 5 Pro", "Amazfit T-Rex 3", "Garmin Venu 3", "Withings ScanWatch 2", "OnePlus Watch 2"] },
    { t: "En İyi Koşu Saatleri", a: "giyilebilir",
      d: "GPS doğruluğu ve pil ömrüyle koşucular için.",
      m: ["Garmin Forerunner 970", "Garmin Forerunner 265", "Polar Vantage V3", "Coros Pace 3", "Suunto Race", "Apple Watch Ultra 3", "Garmin Fenix 8", "Coros Apex 2 Pro", "Polar Pacer Pro", "Amazfit Cheetah Pro"] },
    { t: "En İyi Akıllı Bileklikler", a: "giyilebilir",
      d: "Uygun fiyatlı aktivite takipçileri.",
      m: ["Xiaomi Smart Band 9", "Huawei Band 9", "Fitbit Charge 6", "Amazfit Band 7", "Honor Band 9", "Samsung Galaxy Fit3", "Garmin Vivosmart 5", "Realme Band 2", "Oppo Band 2", "Withings Pulse HR"] },
    { t: "En İyi Akıllı Yüzükler ve Sağlık Takipçileri", a: "giyilebilir",
      d: "Uyku ve toparlanma takibi için yeni nesil cihazlar.",
      m: ["Oura Ring 4", "Samsung Galaxy Ring", "Ultrahuman Ring Air", "Circular Ring", "RingConn Gen 2", "Whoop 4.0", "Amazfit Helio Ring", "Movano Evie Ring", "Withings Body Scan", "Garmin Index BPM"] },

    // ---- TV / görüntü ----
    { t: "En İyi 4K Televizyonlar", a: "tv-goruntu",
      d: "Görüntü kalitesi ve akıllı TV deneyimi.",
      m: ["LG C5 OLED", "Samsung S95F OLED", "Sony Bravia 9", "LG G5 OLED", "TCL C855", "Hisense U8N", "Samsung QN90D", "Panasonic Z95A", "Philips OLED908", "Vestel Elite Q"] },
    { t: "En İyi Bütçe Dostu Televizyonlar", a: "tv-goruntu",
      d: "Uygun fiyata iyi görüntü veren modeller.",
      m: ["TCL P755", "Hisense A6N", "Xiaomi TV A Pro", "Vestel Satellite", "Arçelik A50 C 895 A", "Philips PUS8309", "Samsung DU7100", "LG UR78", "Beko B50 D 895 A", "Toshiba UK4D"] },
    { t: "En İyi Projeksiyon Cihazları", a: "tv-goruntu",
      d: "Ev sineması ve taşınabilir projeksiyonlar.",
      m: ["Epson EH-LS800", "XGIMI Horizon Ultra", "Anker Nebula Cosmos 4K SE", "BenQ X3100i", "Hisense PX3-Pro", "Samsung The Premiere 9", "LG CineBeam Q", "Optoma UHZ50", "ViewSonic X2-4K", "JMGO N1S Ultra"] },
    { t: "En İyi E-Kitap Okuyucular", a: "tv-goruntu",
      d: "Göz yormayan ekranlarla okuma cihazları.",
      m: ["Kindle Paperwhite 12. nesil", "Kobo Libra Colour", "Kindle Scribe", "reMarkable Paper Pro", "Kobo Clara Colour", "Onyx Boox Page", "Kindle Oasis", "PocketBook InkPad 4", "Onyx Boox Note Air 4C", "Kobo Elipsa 2E"] },

    // ---- Fotoğraf ----
    { t: "En İyi Aynasız Fotoğraf Makineleri", a: "foto",
      d: "Amatörden profesyonele aynasız modeller.",
      m: ["Sony A7 IV", "Canon EOS R6 Mark II", "Nikon Z6 III", "Fujifilm X-T5", "Sony A6700", "Canon EOS R8", "Panasonic Lumix S5 II", "Fujifilm X100VI", "Nikon Zf", "OM System OM-1 II"] },
    { t: "En İyi Aksiyon Kameraları", a: "foto",
      d: "Spor ve seyahat çekimleri için.",
      m: ["GoPro Hero 13 Black", "DJI Osmo Action 5 Pro", "Insta360 Ace Pro 2", "Insta360 X4", "GoPro Hero 12", "DJI Osmo Pocket 3", "Akaso Brave 8", "Sony FDR-X3000", "Insta360 GO 3S", "AKASO EK7000 Pro"] },
    { t: "En İyi Dronelar", a: "foto",
      d: "Havadan çekim için drone modelleri.",
      m: ["DJI Mavic 4 Pro", "DJI Air 3S", "DJI Mini 4 Pro", "Autel EVO Lite+", "DJI Neo", "Skydio 2+", "DJI Avata 2", "Autel EVO II Pro", "Parrot Anafi USA", "HoverAir X1"] },
    { t: "En İyi Objektifler", a: "foto",
      d: "Portre, manzara ve genel kullanım objektifleri.",
      m: ["Sony FE 24-70mm f/2.8 GM II", "Canon RF 50mm f/1.2L", "Sigma 24-70mm f/2.8 DG DN", "Nikon Z 70-200mm f/2.8 S", "Fujifilm XF 33mm f/1.4", "Tamron 28-75mm f/2.8 G2", "Sony FE 35mm f/1.4 GM", "Canon RF 24-105mm f/4L", "Sigma 85mm f/1.4 DG DN", "Viltrox AF 27mm f/1.2"] },
    { t: "En İyi Tripod ve Gimbal'lar", a: "foto",
      d: "Sabit çekim ve stabilizasyon ekipmanları.",
      m: ["DJI RS 4 Pro", "Manfrotto Befree Advanced", "Peak Design Travel Tripod", "Zhiyun Crane 4", "Benro Rhino", "DJI Osmo Mobile 6", "Gitzo Traveler", "Joby GorillaPod 5K", "Hohem iSteady M6", "Sirui AM-284"] },

    // ---- Oyun donanımı ----
    { t: "En İyi Oyun Konsolları", a: "oyun-donanim",
      d: "Güncel nesil konsollar ve el konsolları.",
      m: ["PlayStation 5 Pro", "Xbox Series X", "Nintendo Switch 2", "Steam Deck OLED", "PlayStation 5 Slim", "Asus ROG Ally X", "Lenovo Legion Go", "Xbox Series S", "Nintendo Switch OLED", "Ayaneo 2S"] },
    { t: "En İyi Oyun Kulaklıkları", a: "oyun-donanim",
      d: "Konumsal ses ve mikrofon kalitesi.",
      m: ["SteelSeries Arctis Nova Pro", "Astro A50 X", "HyperX Cloud III", "Razer BlackShark V2 Pro", "Logitech G Pro X 2", "Corsair Virtuoso Max", "Sony Inzone H9", "Turtle Beach Stealth Pro", "EPOS H6Pro", "Audeze Maxwell"] },
    { t: "En İyi Oyun Kolları", a: "oyun-donanim",
      d: "PC ve konsol için kontrolcüler.",
      m: ["Xbox Elite Series 2", "DualSense Edge", "8BitDo Ultimate", "Razer Wolverine V2 Pro", "Nintendo Switch Pro Controller", "SCUF Instinct Pro", "Logitech F710", "PowerA Enhanced", "Thrustmaster eSwap X2", "GameSir G7 SE"] },
    { t: "En İyi Oyun Koltukları", a: "oyun-donanim",
      d: "Uzun oturumlarda konfor sağlayan modeller.",
      m: ["Secretlab Titan Evo", "Herman Miller Embody Gaming", "Corsair TC100 Relaxed", "Razer Iskur V2", "Noblechairs Hero", "DXRacer Master", "AndaSeat Kaiser 4", "Cooler Master Caliber X2", "Vertagear PL4800", "Hbada E3"] },

    // ---- Beyaz eşya ----
    { t: "En İyi Çamaşır Makineleri", a: "beyaz-esya",
      d: "Enerji verimliliği ve yıkama performansı.",
      m: ["Bosch Serie 8", "Siemens iQ700", "Arçelik 9143 PMK", "Samsung WW90T", "LG F4WV909P2E", "Beko WTV 9736", "Vestel CMI 96101", "Miele WWD 320", "Whirlpool FreshCare+", "AEG L7FEE84S"] },
    { t: "En İyi Bulaşık Makineleri", a: "beyaz-esya",
      d: "Sessizlik ve kurutma performansı.",
      m: ["Bosch Serie 6", "Siemens iQ500", "Arçelik 6473 I", "Beko BM 6058 I", "Miele G 5210 SC", "Samsung DW60M6050", "Vestel BM 5203", "LG DFB512FP", "AEG FFB53940ZM", "Whirlpool WFC 3C26"] },
    { t: "En İyi Buzdolapları", a: "beyaz-esya",
      d: "Soğutma teknolojisi ve iç hacim.",
      m: ["Bosch KGN56XLEB", "Arçelik 270561 EB", "Samsung RB38", "LG GBB92MCBAP", "Siemens KG56NXIDP", "Beko GN163130", "Vestel NFK540", "Hitachi R-WB640", "Whirlpool W7 921O K", "Grundig GKN 26845"] },
    { t: "En İyi Ankastre Setler", a: "beyaz-esya",
      d: "Fırın, ocak ve davlumbaz üçlüsü.",
      m: ["Bosch Serie 6 Ankastre", "Siemens iQ500 Ankastre", "Arçelik Ankastre Set", "Beko Ankastre Set", "Franke Ankastre", "Silverline Ankastre", "AEG Ankastre Set", "Whirlpool Ankastre", "Electrolux Ankastre", "Miele Ankastre"] },
    { t: "En İyi Klimalar", a: "beyaz-esya",
      d: "Enerji sınıfı ve sessiz çalışma.",
      m: ["Daikin Sensira", "Mitsubishi Electric MSZ", "Arçelik Inverter", "Bosch Climate 5000", "Samsung WindFree", "LG Dual Cool", "Vestel Flora", "Toshiba Shorai Edge", "Beko Inverter", "Baymak Elegant"] },
    { t: "En İyi Robot Süpürgeler", a: "beyaz-esya",
      d: "Haritalama, emiş gücü ve paspas özelliği.",
      m: ["Roborock S8 MaxV Ultra", "Dreame X40 Ultra", "Ecovacs Deebot X5 Pro", "iRobot Roomba j9+", "Roborock Qrevo Pro", "Xiaomi Robot Vacuum X20", "Samsung Jet Bot AI+", "Eufy X10 Pro Omni", "Dyson 360 Vis Nav", "Narwal Freo X Ultra"] },
    { t: "En İyi Dikey Süpürgeler", a: "beyaz-esya",
      d: "Kablosuz şarjlı süpürge modelleri.",
      m: ["Dyson V15 Detect", "Dyson Gen5detect", "Samsung Bespoke Jet", "Tineco Pure One S15", "Roborock H5", "Xiaomi Vacuum G20", "LG CordZero A9", "Arçelik Fresh Air", "Philips 8000 Series", "Bosch Unlimited 7"] },
    { t: "En İyi Kurutma Makineleri", a: "beyaz-esya",
      d: "Isı pompalı ve kondenserli modeller.",
      m: ["Bosch Serie 8 Kurutucu", "Siemens iQ700 Kurutucu", "Arçelik 3689 KT", "Beko DS 8433", "Samsung DV90T", "LG RC90V9", "Miele TWD 360", "AEG T8DEE48S", "Vestel KM 8100", "Whirlpool FT M22"] },

    // ---- Mutfak ----
    { t: "En İyi Kahve Makineleri", a: "mutfak",
      d: "Espresso, filtre ve kapsül makineleri.",
      m: ["De'Longhi Magnifica Evo", "Breville Barista Express", "Nespresso Vertuo Next", "Philips 5400 LatteGo", "Sage Bambino Plus", "Jura E8", "Gaggia Classic Pro", "Krups Evidence", "Melitta Caffeo Solo", "Arzum Okka Türk Kahvesi"] },
    { t: "En İyi Airfryer Modelleri", a: "mutfak",
      d: "Az yağla pişirme cihazları.",
      m: ["Philips Airfryer XXL", "Ninja Foodi Dual Zone", "Cosori Pro II", "Tefal Easy Fry", "Xiaomi Smart Air Fryer", "Arçelik Airfryer", "Instant Vortex Plus", "Karaca Airfryer", "Fakir Fryer", "Tower Vortx"] },
    { t: "En İyi Blender ve Mutfak Robotları", a: "mutfak",
      d: "Doğrama, karıştırma ve hamur için.",
      m: ["Thermomix TM6", "Kenwood Chef Titanium", "KitchenAid Artisan", "Bosch MUM5", "Philips Viva Blender", "Vitamix E310", "Ninja Professional Blender", "Arzum Firro", "Tefal QuickChef", "Braun MultiQuick 9"] },
    { t: "En İyi Tencere ve Tava Setleri", a: "mutfak",
      d: "Granit, çelik ve döküm setler.",
      m: ["Karaca Biogranit", "Tefal Ingenio", "Emsan Fusion", "Schafer Grande", "Le Creuset Döküm", "Fissler Original Profi", "WMF Fusiontec", "Korkmaz Nova", "Aryıldız Granit", "Paşabahçe Borcam"] },
    { t: "En İyi Bıçak Setleri", a: "mutfak",
      d: "Mutfakta keskinlik ve denge.",
      m: ["Zwilling Pro", "Wüsthof Classic", "Global G-Serisi", "Victorinox Swiss Classic", "Shun Classic", "Karaca Mastercook", "Emsan Bıçak Seti", "Tefal Ice Force", "Fiskars Functional Form", "Solingen Sürmene"] },
    { t: "En İyi Su Isıtıcıları ve Çay Makineleri", a: "mutfak",
      d: "Türk çayı ve hızlı su ısıtma.",
      m: ["Arzum Çaycı Klasik", "Karaca Çaysever", "Fakir Çaykolik", "Vestel Sefa Çay Makinesi", "Philips Su Isıtıcı", "Tefal Express Çay", "Beko Çay Makinesi", "Sinbo Çay Seti", "Homend Çaystar", "Kiwi Çay Makinesi"] },
    { t: "En İyi Ekmek Kızartma Makineleri", a: "mutfak",
      d: "Tost ve kızartma makineleri.",
      m: ["Tefal Ultracompact", "Arzum Tostie", "Philips Daily Collection", "Karaca Tost Makinesi", "Fakir Toaster", "Bosch Styline", "Russell Hobbs Toaster", "Sinbo Tost", "Homend Toastbuster", "Beko Tost Makinesi"] },
    { t: "En İyi Kahve Değirmenleri", a: "mutfak",
      d: "Ev tipi öğütücüler.",
      m: ["Baratza Encore ESP", "Fellow Ode Gen 2", "Comandante C40", "1Zpresso JX-Pro", "Timemore Chestnut C3", "Eureka Mignon Specialita", "Wilfa Uniform", "Hario Skerton Pro", "Breville Smart Grinder Pro", "Arzum Okka Değirmen"] },

    // ---- Ev ----
    { t: "En İyi Akıllı Ev Cihazları", a: "ev",
      d: "Evi otomatikleştiren cihazlar.",
      m: ["Philips Hue Akıllı Ampul", "Xiaomi Mi Smart Plug", "Google Nest Hub", "Amazon Echo Dot", "Aqara Kapı Sensörü", "TP-Link Tapo Kamera", "Netatmo Termostat", "Sonoff Akıllı Anahtar", "Ring Video Doorbell", "SwitchBot Perde Motoru"] },
    { t: "En İyi Hava Temizleyiciler", a: "ev",
      d: "Alerji ve toz için HEPA filtreli cihazlar.",
      m: ["Dyson Purifier Cool", "Philips 3000i Series", "Xiaomi Smart Air Purifier 4", "Levoit Core 400S", "Blueair Blue Pure 411", "Coway Airmega 150", "Samsung AX40", "Sharp Plasmacluster", "Arçelik Hava Temizleyici", "IQAir HealthPro"] },
    { t: "En İyi Yatak ve Şilteler", a: "ev",
      d: "Uyku kalitesi için yatak seçenekleri.",
      m: ["Yataş Bedding", "İsbir Yatak", "Bellona Yatak", "Doqu Home", "Vivense Yatak", "Emma Uyku Yatağı", "Sleepy Yatak", "Kuka Yatak", "Boyteks Yatak", "Bedding Home Comfort"] },
    { t: "En İyi Mobilya Markaları", a: "ev",
      d: "Ev mobilyasında öne çıkan markalar.",
      m: ["IKEA", "Vivense", "Bellona", "Doğtaş", "Kelebek Mobilya", "Enza Home", "Modalife", "Alfemo", "İstikbal", "Weltew Home"] },
    { t: "En İyi Aydınlatma Ürünleri", a: "ev",
      d: "Ambiyans ve fonksiyonel aydınlatma.",
      m: ["Philips Hue Play", "Xiaomi Yeelight LED", "IKEA Trådfri", "Nanoleaf Shapes", "Govee Lyra Lamba", "Twinkly Işık Şeridi", "Osram Smart+", "TP-Link Tapo L530E", "LIFX Beam", "Ledvance Smart+"] },
    { t: "En İyi Halı ve Kilim Markaları", a: "ev",
      d: "Ev tekstilinde halı seçenekleri.",
      m: ["Merinos", "Padişah Halı", "Confetti Halı", "Karaca Home Halı", "Chilai Home", "İpek Halı", "Dinarsu", "Sanat Halı", "Royal Halı", "Kaşmir Halı"] },

    // ---- Kişisel bakım ----
    { t: "En İyi Elektrikli Tıraş Makineleri", a: "kisisel-bakim",
      d: "Cilt dostu ve uzun pilli modeller.",
      m: ["Philips Series 9000", "Braun Series 9 Pro", "Panasonic Arc5", "Philips OneBlade Pro", "Braun Series 7", "Xiaomi Electric Shaver S500", "Remington F5", "Philips Series 5000", "Wahl Aqua Blade", "Rowenta Forever Sharp"] },
    { t: "En İyi Saç Kurutma Makineleri", a: "kisisel-bakim",
      d: "Hızlı kurutma ve saç sağlığı.",
      m: ["Dyson Supersonic", "Philips BHD510", "Rowenta Signature Pro", "Remington Pro-Air", "Arzum Saç Kurutma", "BaByliss 6709", "Fakir Prima", "Panasonic Nanoe", "Revlon One-Step", "Karaca Saç Kurutma"] },
    { t: "En İyi Elektrikli Diş Fırçaları", a: "kisisel-bakim",
      d: "Diş eti sağlığı ve temizlik performansı.",
      m: ["Oral-B iO Series 9", "Philips Sonicare 9900 Prestige", "Oral-B Pro 3", "Philips Sonicare ProtectiveClean", "Xiaomi Electric Toothbrush T700", "Colgate Hum", "Oclean X Pro", "Panasonic EW-DM81", "Fairywill P11", "Sonic Chic Urban"] },
    { t: "En İyi Epilasyon ve Lazer Cihazları", a: "kisisel-bakim",
      d: "Evde tüy alma cihazları.",
      m: ["Philips Lumea IPL 9000", "Braun Silk-Expert Pro 5", "Silk'n Infinity", "Ulike Air 3", "Philips Lumea 8000", "Braun Silk-épil 9", "Remington iLight", "Panasonic ES-EL8A", "BoSidin IPL", "Beurer IPL 7500"] },

    // ---- Kozmetik ----
    { t: "En İyi Cilt Bakım Markaları", a: "kozmetik",
      d: "Serum, nemlendirici ve temizleyicilerde öne çıkanlar.",
      m: ["La Roche-Posay", "CeraVe", "The Ordinary", "Bioderma", "Avene", "Nivea", "Vichy", "Eucerin", "Neutrogena", "Paula's Choice"] },
    { t: "En İyi Güneş Kremleri", a: "kozmetik",
      d: "Yüksek koruma faktörlü ve leke bırakmayan ürünler.",
      m: ["La Roche-Posay Anthelios", "Bioderma Photoderm", "Avene Solaire", "Vichy Capital Soleil", "Nivea Sun", "Eucerin Sun", "Isdin Fotoprotector", "Sebamed Sun", "Garnier Ambre Solaire", "Beauty of Joseon Relief Sun"] },
    { t: "En İyi Parfüm Markaları", a: "kozmetik",
      d: "Kalıcılığı ve karakteriyle öne çıkan markalar.",
      m: ["Dior", "Chanel", "Tom Ford", "Yves Saint Laurent", "Jo Malone", "Creed", "Maison Margiela", "Byredo", "Nishane", "Hermès"] },
    { t: "En İyi Makyaj Markaları", a: "kozmetik",
      d: "Fondöten, ruj ve göz makyajında öne çıkanlar.",
      m: ["MAC Cosmetics", "Maybelline", "L'Oréal Paris", "NARS", "Charlotte Tilbury", "Fenty Beauty", "Estée Lauder", "Flormar", "Golden Rose", "Rare Beauty"] },
    { t: "En İyi Saç Bakım Ürünleri", a: "kozmetik",
      d: "Şampuan, maske ve bakım yağları.",
      m: ["Olaplex", "Kerastase", "L'Oréal Professionnel", "Moroccanoil", "Redken", "Schwarzkopf", "Pantene", "Elidor", "Nioxin", "Briogeo"] },
    { t: "En İyi Yerli Kozmetik Markaları", a: "kozmetik",
      d: "Türkiye'de üretilen bakım ve makyaj markaları.",
      m: ["Flormar", "Golden Rose", "Farmasi", "Pastel Cosmetics", "Note Cosmetics", "Sleepy Cosmetics", "Rossmann Isana", "Dermokil", "Nacomi Türkiye", "Procsin"] },

    // ---- Gıda ----
    { t: "En İyi Türk Kahvesi Markaları", a: "gida",
      d: "Öğütülmüş Türk kahvesinde tercih edilenler.",
      m: ["Kurukahveci Mehmet Efendi", "Kahve Dünyası", "Selamlique", "Arzum Okka", "Nuri Toplar", "Şenol Kahve", "Altıncezve", "Kahveci Hacıbaba", "Kocatepe Kahve", "Anadolu Kahvesi"] },
    { t: "En İyi Çay Markaları", a: "gida",
      d: "Siyah çayda demleme kalitesi.",
      m: ["Çaykur", "Doğadan", "Lipton", "Karali Çay", "Çaykur Rize Turist", "Ahmad Tea", "Beta Tea", "Twinings", "Ofçay", "Didi Çay"] },
    { t: "En İyi Zeytinyağı Markaları", a: "gida",
      d: "Soğuk sıkım ve natürel sızma zeytinyağları.",
      m: ["Komili", "Kırlangıç", "Tariş", "Olivos", "Ayvalık Zeytinyağı", "Madra", "Nar Gourmet", "Marmarabirlik", "Laleli Zeytinyağı", "Oleamea"] },
    { t: "En İyi Bal Markaları", a: "gida",
      d: "Çiçek, çam ve kestane balı seçenekleri.",
      m: ["Balparmak", "Anavarza Bal", "Altıparmak", "Bal Küpü", "Kervan Bal", "Anzer Balı", "Doğadan Bal", "Balım Bal", "Gürsoy Bal", "Sema Bal"] },
    { t: "En İyi Peynir Çeşitleri", a: "gida",
      d: "Türkiye'nin yöresel peynirleri.",
      m: ["Ezine peyniri", "Erzincan tulum", "Kars gravyeri", "Van otlu peynir", "Kaşar peyniri", "Çeçil peyniri", "Örgü peyniri", "Mihaliç peyniri", "Lor peyniri", "Künefelik peynir"] },
    { t: "En İyi Çikolata Markaları", a: "gida",
      d: "Tablet ve butik çikolatalar.",
      m: ["Milka", "Ülker", "Nestlé Damak", "Godiva", "Lindt", "Ferrero Rocher", "Kahve Dünyası Çikolata", "Toblerone", "Elit Çikolata", "Şölen"] },
    { t: "En İyi Kuruyemiş Markaları", a: "gida",
      d: "Antep fıstığından fındığa kuruyemiş.",
      m: ["Tadım", "Peyman", "Çerezci", "Nutshell", "Fıstıkzade", "Ozan Kuruyemiş", "Bereket Kuruyemiş", "Malatya Pazarı", "Kuruyemiş Dünyası", "Erdem Kuruyemiş"] },
    { t: "En İyi Dondurulmuş Gıda Markaları", a: "gida",
      d: "Pratik yemek çözümleri.",
      m: ["Superfresh", "Pınar Donuk", "Namet", "Banvit", "Reis Gıda", "Beşler", "Erpiliç", "Aytaç", "Kalite Gıda", "Yayla Gıda"] },
    { t: "En İyi Organik Gıda Markaları", a: "gida",
      d: "Sertifikalı organik ürünler.",
      m: ["Eldorado Organik", "Doğal Değirmen", "Orgee", "Ekoloji Market", "Yerlim Organik", "Ovadan Organik", "Bio Zone", "Anadolu Organik", "Rüzgar Organik", "Doğa Bereket"] },

    // ---- İçecek ----
    { t: "En İyi Maden Suyu Markaları", a: "icecek",
      d: "Sade ve meyveli maden suları.",
      m: ["Beypazarı", "Kızılay", "Uludağ", "Sırma", "Erikli Soda", "Niğde Gazozu", "Çamlıca Gazoz", "Freş Soda", "Damla Soda", "Hamidiye Soda"] },
    { t: "En İyi Gazlı İçecekler", a: "icecek",
      d: "Kolalı ve meyveli gazlı içecekler.",
      m: ["Coca-Cola", "Pepsi", "Fanta", "Sprite", "Çamlıca Gazoz", "Niğde Gazozu", "Uludağ Frutti", "Yedigün", "Schweppes", "Fruko"] },
    { t: "En İyi Meyve Suyu Markaları", a: "icecek",
      d: "Doğal ve nektar meyve suları.",
      m: ["Cappy", "Tropicana", "Dimes", "Meysu", "Fruko Meyve Suyu", "Pınar Meyve Suyu", "Sırma Meyve Suyu", "Aroma", "Juss", "Anadolu Meyve"] },
    { t: "En İyi Enerji İçecekleri", a: "icecek",
      d: "Kafein ve tat dengesiyle enerji içecekleri.",
      m: ["Red Bull", "Monster Energy", "Burn", "Hell Energy", "Powerade", "Rockstar", "Big Bear", "Nocco", "Reign", "XL Energy"] },
    { t: "En İyi Bira Markaları", a: "icecek",
      d: "Yerli ve ithal bira seçenekleri.",
      m: ["Efes Pilsen", "Bomonti", "Tuborg", "Carlsberg", "Gara Guzu", "Heineken", "Miller", "Corona", "Pablo Craft Beer", "Beertugal"] },
    { t: "En İyi Şarap Üreticileri", a: "icecek",
      d: "Türkiye'nin bağ ve şarap evleri.",
      m: ["Kavaklıdere", "Doluca", "Sevilen", "Kayra", "Corvus", "Suvla", "Urla Şarapçılık", "Chamlija", "Vinkara", "Pasaeli"] },

    // ---- Bebek ----
    { t: "En İyi Bebek Bezi Markaları", a: "bebek",
      d: "Emicilik ve cilt dostu olma dengesi.",
      m: ["Prima", "Molfix", "Sleepy", "Huggies", "Bebem Bez", "Canbebe", "Evy Baby", "Joonies", "Pufla", "Baby Turco"] },
    { t: "En İyi Bebek Arabaları", a: "bebek",
      d: "Katlanabilirlik ve manevra kabiliyeti.",
      m: ["Cybex Priam", "Bugaboo Fox 5", "Chicco Trio", "Joie Chrome", "Baby Jogger City Mini", "Kinderkraft Grande", "Britax Römer B-Agile", "Baby Home BH-970", "Prego Legend", "Stokke Xplory X"] },
    { t: "En İyi Bebek Oto Koltukları", a: "bebek",
      d: "Güvenlik testleri ve montaj kolaylığı.",
      m: ["Cybex Sirona", "Britax Römer Dualfix", "Maxi-Cosi Pearl", "Joie Spin 360", "Chicco Seat3Fit", "Nuna Rebl Plus", "Bebe Confort", "Kinderkraft Xpedition", "Baby Home Oto Koltuğu", "Recaro Salia"] },
    { t: "En İyi Bebek Maması Markaları", a: "bebek",
      d: "Ek gıdaya geçiş dönemi ürünleri.",
      m: ["Hipp", "Milupa", "Aptamil", "Bebelac", "Nestlé Bebe", "Humana", "Holle", "Nutricia", "Sütaş Bebek", "Organic Baby"] },

    // ---- Evcil hayvan ----
    { t: "En İyi Kedi Maması Markaları", a: "evcil",
      d: "Tahılsız ve yüksek etli mamalar.",
      m: ["Royal Canin", "Hill's Science Plan", "Purina Pro Plan", "Acana", "Orijen", "Brit Care", "Reflex Plus", "N&D Farmina", "ProChoice", "Bozita"] },
    { t: "En İyi Köpek Maması Markaları", a: "evcil",
      d: "Irk ve yaşa göre köpek mamaları.",
      m: ["Royal Canin", "Acana", "Orijen", "Hill's Science Plan", "Purina Pro Plan", "Brit Premium", "N&D Farmina", "Eukanuba", "Reflex Plus", "Belcando"] },
    { t: "En İyi Kedi Kumları", a: "evcil",
      d: "Topaklaşma ve koku kontrolü.",
      m: ["Catsan", "Ever Clean", "Cat's Best", "Sepicat", "Pretty Cat", "Golden Grey", "Van Kedi Kumu", "Kit Cat", "Tofu Kedi Kumu", "Biokat's"] },
    { t: "En İyi Evcil Hayvan Aksesuar Markaları", a: "evcil",
      d: "Tasma, yatak ve oyuncak markaları.",
      m: ["Trixie", "Kong", "Ferplast", "Petmate", "Flexi", "Julius-K9", "Pawise", "Lepus", "Hunter", "Curver"] },

    // ---- Otomotiv ----
    { t: "Türkiye'de En Çok Satan Otomobiller", a: "otomotiv",
      d: "Satış rakamlarıyla öne çıkan modeller.",
      m: ["Fiat Egea", "Renault Clio", "Togg T10X", "Volkswagen Passat", "Renault Megane", "Toyota Corolla", "Peugeot 2008", "Hyundai i20", "Dacia Duster", "Citroën C3"] },
    { t: "En İyi Elektrikli Otomobiller", a: "otomotiv",
      d: "Menzil, şarj hızı ve donanım dengesi.",
      m: ["Tesla Model Y", "Togg T10X", "BYD Seal", "Hyundai Ioniq 5", "Kia EV6", "Volkswagen ID.4", "BMW i4", "Mercedes EQE", "Volvo EX30", "MG4 Electric"] },
    { t: "En İyi SUV Modelleri", a: "otomotiv",
      d: "Aile kullanımı için SUV seçenekleri.",
      m: ["Toyota RAV4", "Volkswagen Tiguan", "Hyundai Tucson", "Kia Sportage", "Peugeot 3008", "Nissan Qashqai", "Dacia Duster", "Renault Austral", "Skoda Karoq", "Ford Kuga"] },
    { t: "En İyi Lastik Markaları", a: "otomotiv",
      d: "Yol tutuş ve ömür dengesi.",
      m: ["Michelin", "Continental", "Bridgestone", "Goodyear", "Pirelli", "Petlas", "Lassa", "Hankook", "Nokian", "Dunlop"] },
    { t: "En İyi Araç İçi Aksesuarlar", a: "otomotiv",
      d: "Konfor ve güvenlik için ekipmanlar.",
      m: ["Araç kamerası", "Telefon tutucu", "Bluetooth FM transmitter", "Koltuk kılıfı", "Araç süpürgesi", "Lastik pompası", "Araç buzdolabı", "Güneşlik", "Bagaj düzenleyici", "Akü takviye cihazı"] },
    { t: "En İyi Motosiklet Markaları", a: "otomotiv",
      d: "Şehir içi ve tur motosikletleri.",
      m: ["Honda", "Yamaha", "BMW Motorrad", "Kawasaki", "KTM", "Suzuki", "Ducati", "Triumph", "Bajaj", "Kuba Motor"] },
    { t: "En İyi Elektrikli Scooter'lar", a: "otomotiv",
      d: "Şehir içi kısa mesafe ulaşım.",
      m: ["Xiaomi Electric Scooter 4 Pro", "Segway Ninebot Max G2", "Ninebot F40", "Mi Scooter Essential", "Kugoo M4 Pro", "Dualtron Mini", "Apachie E-Scooter", "Vsett 9+", "Micro Merlin", "Okai Neon Pro"] },

    // ---- Spor ürün ----
    { t: "En İyi Koşu Ayakkabıları", a: "spor-urun",
      d: "Yol koşusu için yastıklama ve destek.",
      m: ["Nike Pegasus 41", "Adidas Ultraboost Light", "Asics Gel-Nimbus 26", "Hoka Clifton 9", "New Balance 1080v13", "Brooks Ghost 16", "Saucony Ride 17", "On Cloudmonster", "Puma Deviate Nitro 3", "Mizuno Wave Rider 28"] },
    { t: "En İyi Spor Giyim Markaları", a: "spor-urun",
      d: "Antrenman ve günlük spor giyim.",
      m: ["Nike", "Adidas", "Under Armour", "Puma", "Lululemon", "Decathlon Kalenji", "New Balance", "Reebok", "Columbia", "The North Face"] },
    { t: "En İyi Ev Egzersiz Ekipmanları", a: "spor-urun",
      d: "Küçük alanda antrenman için ekipman.",
      m: ["Dambıl seti", "Direnç bandı", "Kettlebell", "Pilates matı", "Kürek çekme makinesi", "Koşu bandı", "Egzersiz bisikleti", "Barfiks çubuğu", "TRX askı bandı", "Foam roller"] },
    { t: "En İyi Kamp ve Outdoor Markaları", a: "spor-urun",
      d: "Çadır, sırt çantası ve dış giyim.",
      m: ["The North Face", "Columbia", "Salomon", "Deuter", "Quechua", "Jack Wolfskin", "Mammut", "Osprey", "Merrell", "Forclaz"] },
    { t: "En İyi Bisiklet Markaları", a: "spor-urun",
      d: "Şehir, dağ ve yol bisikletleri.",
      m: ["Bianchi", "Trek", "Specialized", "Giant", "Scott", "Cannondale", "Merida", "Salcano", "Kron", "Carraro"] },

    // ---- Ofis / hobi ----
    { t: "En İyi Ofis Sandalyeleri", a: "ofis",
      d: "Uzun oturumlarda sırt sağlığı.",
      m: ["Herman Miller Aeron", "Steelcase Leap", "Secretlab Titan Evo", "IKEA Markus", "Nouhaus Ergo3D", "Sihoo M57", "Bürotime Ergo", "Hbada E3", "Autonomous ErgoChair Pro", "Nilkamal Ergonomic"] },
    { t: "En İyi Yükseklik Ayarlı Masalar", a: "ofis",
      d: "Ayakta çalışmayı destekleyen masalar.",
      m: ["IKEA Bekant", "Autonomous SmartDesk Core", "Flexispot E7", "Uplift V2", "Ergotron WorkFit", "Fully Jarvis", "Vari Electric Standing Desk", "Secretlab Magnus Pro", "Bürotime Adjustable", "Songmics Standing Desk"] },
    { t: "En İyi Kalem ve Defter Markaları", a: "ofis",
      d: "Not tutma alışkanlığı olanlar için.",
      m: ["Moleskine", "Leuchtturm1917", "Rhodia", "Lamy", "Pilot", "Muji", "Faber-Castell", "Stabilo", "Uni-ball", "Rotring"] },
    { t: "En İyi Yazıcılar", a: "ofis",
      d: "Ev ve küçük ofis için yazıcılar.",
      m: ["HP LaserJet Pro", "Epson EcoTank L3250", "Canon PIXMA G3411", "Brother HL-L2350DW", "HP DeskJet 4120", "Epson WorkForce", "Canon i-SENSYS", "Samsung Xpress", "Xerox B210", "Ricoh SP 230"] },
    { t: "En İyi Müzik Enstrümanı Markaları", a: "hobi",
      d: "Başlangıç ve ileri seviye enstrümanlar.",
      m: ["Yamaha", "Fender", "Gibson", "Roland", "Casio", "Ibanez", "Korg", "Squier", "Cort", "Nord"] },
    { t: "En İyi Kutu Oyunları", a: "hobi",
      d: "Arkadaş ve aile grupları için oyunlar.",
      m: ["Catan", "Ticket to Ride", "Carcassonne", "Azul", "7 Wonders", "Dixit", "Codenames", "Wingspan", "Pandemic", "Splendor"] },
    { t: "En İyi LEGO Setleri", a: "hobi",
      d: "Koleksiyon ve yapım keyfi.",
      m: ["LEGO Technic Ferrari", "LEGO Star Wars Millennium Falcon", "LEGO Architecture İstanbul", "LEGO Icons Botanical", "LEGO Creator Expert", "LEGO Harry Potter Hogwarts", "LEGO City Uzay", "LEGO Ideas NASA", "LEGO Marvel Hulkbuster", "LEGO Speed Champions"] },
    { t: "En İyi Hobi ve El Sanatları Ürünleri", a: "hobi",
      d: "Boyama, örgü ve modelcilik malzemeleri.",
      m: ["Akrilik boya seti", "Suluboya defteri", "Örgü şiş seti", "Model uçak kiti", "Seramik hamuru", "Ahşap yakma kalemi", "Diamond painting seti", "Makrome ipi", "Resin kalıp seti", "Kaligrafi kalem seti"] },
  ],
};
