import type { KategoriIcerigi } from "./tipler";

/**
 * Website kategorisi — 100+ liste.
 * Alt kategoriler: e-ticaret, haber-site, yapay-zeka, tasarim, gelistirici,
 * verimlilik, egitim-site, sosyal, video, finans-site, saglik-site,
 * eglence, arac, ilan, forum
 */
export const website: KategoriIcerigi = {
  kategori: "website",
  listeler: [
    // ---- E-ticaret ----
    { t: "Türkiye'nin En İyi E-Ticaret Siteleri", a: "e-ticaret",
      d: "Ürün çeşitliliği, teslimat ve iade süreçleri.",
      m: ["Trendyol", "Hepsiburada", "Amazon Türkiye", "n11", "Çiçeksepeti", "Getir", "Migros", "Vatan Bilgisayar", "MediaMarkt", "Teknosa"] },
    { t: "En İyi İkinci El Alışveriş Siteleri", a: "e-ticaret",
      d: "Kullanılmış eşya alım satımı.",
      m: ["Sahibinden.com", "Letgo", "Dolap", "Gardrops", "Trendyol Dolap", "İkinci Yeni", "Vinted", "eBay", "Craigslist", "Facebook Marketplace"] },
    { t: "En İyi Moda ve Giyim Siteleri", a: "e-ticaret",
      d: "Kıyafet ve aksesuar alışverişi.",
      m: ["Trendyol", "Zara", "H&M", "LC Waikiki", "Koton", "Boyner", "Defacto", "Mavi", "Beymen", "Asos"] },
    { t: "En İyi Teknoloji Alışveriş Siteleri", a: "e-ticaret",
      d: "Elektronik ürünlerde fiyat ve garanti.",
      m: ["Vatan Bilgisayar", "Teknosa", "MediaMarkt", "İncehesap", "Hepsiburada", "Amazon Türkiye", "Trendyol", "Gaming.gen.tr", "Itopya", "Sinerji"] },
    { t: "En İyi Fiyat Karşılaştırma Siteleri", a: "e-ticaret",
      d: "En ucuzu bulmak için kullanılan araçlar.",
      m: ["Cimri", "Akakçe", "Epey", "Fiyat Bul", "Nesine Fiyat", "Ucuzu.com", "Google Shopping", "İdealo", "PriceRunner", "Fiyatı Ne"] },
    { t: "En İyi İndirim ve Kupon Siteleri", a: "e-ticaret",
      d: "Kampanya ve indirim kodu takibi.",
      m: ["İndirim Kuponları", "Kuponkodu", "Picodi", "Hangi Kredi Kampanya", "Kampanya Takip", "İndirimce", "Kuponia", "İndirim Avcısı", "Fırsat Bu Fırsat", "Honey"] },
    { t: "En İyi El Yapımı ve Tasarım Ürün Siteleri", a: "e-ticaret",
      d: "Butik ve el emeği ürünler.",
      m: ["Etsy", "Zet.com", "Dükkan", "Hobim Sanat", "Elyapimi", "Butigo", "Karaca Tasarım", "İşyeri Tasarım", "Handmade Türkiye", "Craftinart"] },
    { t: "En İyi Kitap Satış Siteleri", a: "e-ticaret",
      d: "Basılı ve dijital kitap alışverişi.",
      m: ["D&R", "Kitapyurdu", "İdefix", "BKM Kitap", "Amazon Türkiye Kitap", "Kitapsever", "Nadir Kitap", "Babil.com", "Hepsiburada Kitap", "Trendyol Kitap"] },

    // ---- Haber siteleri ----
    { t: "Türkiye'nin En Çok Okunan Haber Siteleri", a: "haber-site",
      d: "Trafik ve gündem takibiyle öne çıkanlar.",
      m: ["Hürriyet", "Sözcü", "Milliyet", "Sabah", "NTV", "Habertürk", "CNN Türk", "T24", "BBC News Türkçe", "Anadolu Ajansı"] },
    { t: "En İyi Bağımsız Haber Kaynakları", a: "haber-site",
      d: "Alternatif ve bağımsız yayın yapan siteler.",
      m: ["T24", "Diken", "Gazete Duvar", "Medyascope", "BirGün", "Bianet", "Serbestiyet", "P24", "Teyit.org", "Doğruluk Payı"] },
    { t: "En İyi Teknoloji Haber Siteleri", a: "haber-site",
      d: "Ürün, yazılım ve sektör haberleri.",
      m: ["Webrazzi", "ShiftDelete.Net", "Donanım Haber", "Chip Online", "Technopat", "The Verge", "TechCrunch", "Ars Technica", "Engadget", "Wired"] },
    { t: "En İyi Ekonomi Haber Siteleri", a: "haber-site",
      d: "Piyasa ve makroekonomi takibi.",
      m: ["Bloomberg HT", "Ekonomim", "Dünya Gazetesi", "Fortune Türkiye", "Patronlar Dünyası", "Financial Times", "Reuters", "The Economist", "BigPara", "Ekonomi Gazetesi"] },
    { t: "En İyi Spor Haber Siteleri", a: "haber-site",
      d: "Skor, transfer ve analiz.",
      m: ["Fanatik", "Fotomaç", "Sporx", "NTV Spor", "beIN SPORTS Haber", "Mackolik", "Transfermarkt", "ESPN", "Goal.com", "Sky Sports"] },
    { t: "En İyi Bilim Haber Siteleri", a: "haber-site",
      d: "Güvenilir bilim iletişimi yapan kaynaklar.",
      m: ["Evrim Ağacı", "Bilim Teknik", "Popular Science Türkiye", "Nature", "Science", "Scientific American", "New Scientist", "Bilim Fili", "Herkese Bilim Teknoloji", "Açık Bilim"] },
    { t: "En İyi Doğrulama ve Teyit Platformları", a: "haber-site",
      d: "Yanlış bilgiyle mücadele eden siteler.",
      m: ["Teyit.org", "Doğruluk Payı", "Malumatfuruş", "Snopes", "FactCheck.org", "AFP Fact Check", "Reuters Fact Check", "Yalansavar", "Gerçek Payı", "Full Fact"] },

    // ---- Yapay zekâ ----
    { t: "En İyi Yapay Zekâ Sohbet Araçları", a: "yapay-zeka",
      d: "Metin üretimi ve soru cevaplama.",
      m: ["Claude", "ChatGPT", "Google Gemini", "Perplexity", "Microsoft Copilot", "Mistral Le Chat", "DeepSeek", "Grok", "Poe", "You.com"] },
    { t: "En İyi Yapay Zekâ Görsel Üretme Araçları", a: "yapay-zeka",
      d: "Metinden görsel üreten servisler.",
      m: ["Midjourney", "DALL·E", "Stable Diffusion", "Adobe Firefly", "Leonardo.ai", "Ideogram", "Flux", "Canva Magic Media", "Playground AI", "NightCafe"] },
    { t: "En İyi Yapay Zekâ Kod Asistanları", a: "yapay-zeka",
      d: "Yazılım geliştirmede kullanılan araçlar.",
      m: ["Claude Code", "GitHub Copilot", "Cursor", "Codeium", "Tabnine", "Amazon Q Developer", "Replit AI", "Sourcegraph Cody", "JetBrains AI", "Continue"] },
    { t: "En İyi Yapay Zekâ Video Araçları", a: "yapay-zeka",
      d: "Video üretme ve düzenleme.",
      m: ["Runway", "Sora", "Pika", "Kling AI", "Luma Dream Machine", "HeyGen", "Synthesia", "Descript", "Veed.io", "Opus Clip"] },
    { t: "En İyi Yapay Zekâ Ses ve Müzik Araçları", a: "yapay-zeka",
      d: "Seslendirme ve müzik üretimi.",
      m: ["ElevenLabs", "Suno", "Udio", "Murf.ai", "Play.ht", "Adobe Podcast", "LALAL.AI", "Voicemod", "Resemble AI", "Speechify"] },
    { t: "En İyi Yapay Zekâ Yazı Araçları", a: "yapay-zeka",
      d: "İçerik yazımı ve düzenleme.",
      m: ["Claude", "ChatGPT", "Jasper", "Copy.ai", "Grammarly", "Notion AI", "Writesonic", "QuillBot", "Rytr", "Sudowrite"] },
    { t: "En İyi Yapay Zekâ Araştırma Araçları", a: "yapay-zeka",
      d: "Kaynak taraması ve özetleme.",
      m: ["Perplexity", "Elicit", "Consensus", "Semantic Scholar", "SciSpace", "NotebookLM", "Connected Papers", "Research Rabbit", "Scite.ai", "Litmaps"] },
    { t: "En İyi Ücretsiz Yapay Zekâ Araçları", a: "yapay-zeka",
      d: "Ücretsiz katmanı işe yarayan servisler.",
      m: ["Claude", "ChatGPT", "Google Gemini", "Perplexity", "Canva Magic Studio", "Microsoft Copilot", "Leonardo.ai", "Hugging Face", "Ideogram", "Kling AI"] },

    // ---- Tasarım ----
    { t: "En İyi Tasarım Araçları", a: "tasarim",
      d: "Arayüz ve grafik tasarım yazılımları.",
      m: ["Figma", "Adobe Photoshop", "Adobe Illustrator", "Canva", "Sketch", "Affinity Designer", "Framer", "Penpot", "Adobe XD", "Procreate"] },
    { t: "En İyi Ücretsiz Görsel Kaynakları", a: "tasarim",
      d: "Telifsiz fotoğraf ve illüstrasyon.",
      m: ["Unsplash", "Pexels", "Pixabay", "Freepik", "unDraw", "Storyset", "Flaticon", "Openverse", "Burst", "Reshot"] },
    { t: "En İyi İkon ve İllüstrasyon Kaynakları", a: "tasarim",
      d: "Arayüz ve sunum için ikon setleri.",
      m: ["Lucide", "Heroicons", "Font Awesome", "Feather Icons", "Phosphor Icons", "Flaticon", "Noun Project", "Iconify", "Streamline", "Tabler Icons"] },
    { t: "En İyi Font Kaynakları", a: "tasarim",
      d: "Ücretsiz ve ticari yazı tipleri.",
      m: ["Google Fonts", "Adobe Fonts", "Fontshare", "Font Squirrel", "MyFonts", "Fontsource", "DaFont", "Type Network", "Klim Type Foundry", "Velvetyne"] },
    { t: "En İyi Renk Paleti Araçları", a: "tasarim",
      d: "Uyumlu renk seçimi için siteler.",
      m: ["Coolors", "Adobe Color", "Colorhunt", "Realtime Colors", "Paletton", "Happy Hues", "Khroma", "Color Designer", "ColorSpace", "Tailwind Colors"] },
    { t: "En İyi Tasarım İlham Kaynakları", a: "tasarim",
      d: "Portfolyo ve tasarım galerileri.",
      m: ["Dribbble", "Behance", "Awwwards", "Mobbin", "Land-book", "SiteInspire", "Godly", "Pinterest", "Muzli", "Refero"] },
    { t: "En İyi Sunum Araçları", a: "tasarim",
      d: "Slayt hazırlama uygulamaları.",
      m: ["Canva", "Google Slides", "Microsoft PowerPoint", "Pitch", "Prezi", "Beautiful.ai", "Gamma", "Keynote", "Tome", "Slides.com"] },

    // ---- Geliştirici ----
    { t: "Yazılımcılar İçin En İyi Siteler", a: "gelistirici",
      d: "Günlük kullanılan kaynaklar.",
      m: ["GitHub", "Stack Overflow", "MDN Web Docs", "DevDocs", "CodePen", "Dev.to", "Hacker News", "freeCodeCamp", "LeetCode", "Can I Use"] },
    { t: "En İyi Kod Editörleri ve IDE'ler", a: "gelistirici",
      d: "Geliştirme ortamları.",
      m: ["Visual Studio Code", "Cursor", "JetBrains IntelliJ IDEA", "Neovim", "Zed", "Sublime Text", "WebStorm", "PyCharm", "Xcode", "Android Studio"] },
    { t: "En İyi Hosting ve Dağıtım Platformları", a: "gelistirici",
      d: "Web uygulaması yayınlama.",
      m: ["Vercel", "Netlify", "Cloudflare Pages", "Railway", "Render", "Fly.io", "AWS Amplify", "DigitalOcean", "Heroku", "Hetzner"] },
    { t: "En İyi Veritabanı Servisleri", a: "gelistirici",
      d: "Yönetilen veritabanı sağlayıcıları.",
      m: ["Supabase", "PlanetScale", "Neon", "MongoDB Atlas", "Firebase", "AWS RDS", "Turso", "Upstash", "CockroachDB", "Xata"] },
    { t: "En İyi API Test Araçları", a: "gelistirici",
      d: "İstek gönderme ve dokümantasyon.",
      m: ["Postman", "Insomnia", "Bruno", "Hoppscotch", "Thunder Client", "Paw", "HTTPie", "Swagger UI", "Apidog", "REST Client"] },
    { t: "En İyi Kod Öğrenme Platformları", a: "gelistirici",
      d: "Sıfırdan programlama öğrenmek için.",
      m: ["freeCodeCamp", "Codecademy", "The Odin Project", "Patika.dev", "Frontend Masters", "Exercism", "Scrimba", "BTK Akademi", "Coursera", "Boot.dev"] },
    { t: "En İyi Açık Kaynak Projeler", a: "gelistirici",
      d: "GitHub'da en çok kullanılan projeler.",
      m: ["Linux", "React", "Kubernetes", "PostgreSQL", "VS Code", "TensorFlow", "Node.js", "Blender", "Home Assistant", "Nextcloud"] },
    { t: "En İyi Web Çatıları (Framework)", a: "gelistirici",
      d: "Modern web geliştirme çatıları.",
      m: ["Next.js", "React", "Vue.js", "Svelte", "Astro", "Nuxt", "Remix", "Angular", "SolidJS", "Qwik"] },
    { t: "En İyi Geliştirici Blogları", a: "gelistirici",
      d: "Derinlemesine teknik yazılar.",
      m: ["Josh W Comeau", "Overreacted (Dan Abramov)", "Kent C. Dodds", "CSS-Tricks", "Smashing Magazine", "Julia Evans", "Martin Fowler", "High Scalability", "Lee Robinson", "Anthropic Engineering"] },

    // ---- Verimlilik ----
    { t: "En İyi Not Tutma Uygulamaları", a: "verimlilik",
      d: "Fikir ve bilgi yönetimi.",
      m: ["Notion", "Obsidian", "Apple Notes", "Evernote", "Microsoft OneNote", "Bear", "Logseq", "Craft", "Google Keep", "Roam Research"] },
    { t: "En İyi Görev ve Proje Yönetim Araçları", a: "verimlilik",
      d: "Ekip ve bireysel görev takibi.",
      m: ["Notion", "Trello", "Asana", "Jira", "Linear", "ClickUp", "Monday.com", "Todoist", "Basecamp", "Height"] },
    { t: "En İyi Takvim ve Zaman Yönetimi Araçları", a: "verimlilik",
      d: "Toplantı ve zaman planlama.",
      m: ["Google Calendar", "Fantastical", "Cron (Notion Calendar)", "Calendly", "Motion", "Reclaim.ai", "Outlook Calendar", "Cal.com", "Sunsama", "Amie"] },
    { t: "En İyi Parola Yöneticileri", a: "verimlilik",
      d: "Güvenli parola saklama.",
      m: ["1Password", "Bitwarden", "Proton Pass", "Dashlane", "KeePassXC", "NordPass", "Keeper", "Apple Passwords", "Enpass", "RoboForm"] },
    { t: "En İyi Ekran Kaydı ve Görüntü Araçları", a: "verimlilik",
      d: "Ekran görüntüsü ve video kaydı.",
      m: ["Loom", "OBS Studio", "CleanShot X", "ShareX", "Snagit", "Screen Studio", "Camtasia", "Shottr", "Kap", "Bandicam"] },
    { t: "En İyi PDF Araçları", a: "verimlilik",
      d: "PDF birleştirme, sıkıştırma ve düzenleme.",
      m: ["Adobe Acrobat", "Smallpdf", "iLovePDF", "PDF24", "Sejda", "PDFgear", "Foxit PDF", "Stirling PDF", "PDF Candy", "Nitro PDF"] },
    { t: "En İyi Ekip İletişim Araçları", a: "verimlilik",
      d: "Mesajlaşma ve görüntülü toplantı.",
      m: ["Slack", "Microsoft Teams", "Discord", "Zoom", "Google Meet", "Mattermost", "Rocket.Chat", "Webex", "Around", "Twist"] },
    { t: "En İyi Otomasyon Araçları", a: "verimlilik",
      d: "Uygulamalar arası iş akışı kurma.",
      m: ["Zapier", "Make (Integromat)", "n8n", "IFTTT", "Power Automate", "Pipedream", "Activepieces", "Workato", "Apple Shortcuts", "Tasker"] },

    // ---- Eğitim siteleri ----
    { t: "En İyi Ücretsiz Eğitim Siteleri", a: "egitim-site",
      d: "Ücretsiz kurs ve ders içeriği.",
      m: ["Khan Academy", "freeCodeCamp", "BTK Akademi", "Coursera (denetleme modu)", "edX", "MIT OpenCourseWare", "Türkiye Açık Ders", "YouTube Eğitim", "Duolingo", "Udacity Free"] },
    { t: "En İyi Akademik Kaynak Siteleri", a: "egitim-site",
      d: "Makale ve tez arama.",
      m: ["Google Scholar", "YÖK Tez Merkezi", "DergiPark", "arXiv", "PubMed", "JSTOR", "Semantic Scholar", "ResearchGate", "Sci-Hub alternatifleri", "Zenodo"] },
    { t: "En İyi Sözlük ve Çeviri Siteleri", a: "egitim-site",
      d: "Kelime anlamı ve çeviri.",
      m: ["DeepL", "Google Çeviri", "Tureng", "TDK Sözlük", "Cambridge Dictionary", "Linguee", "WordReference", "Sesli Sözlük", "Reverso Context", "Zargan"] },
    { t: "En İyi Ders Notu ve Özet Siteleri", a: "egitim-site",
      d: "Öğrenciler için paylaşımlı kaynaklar.",
      m: ["Tonguç Akademi", "Hocalara Geldik", "Rehber Matematik", "Benim Hocam", "Kunduz", "Studocu", "Quizlet", "Anki", "Chegg", "Course Hero"] },

    // ---- Sosyal / video ----
    { t: "En Çok Kullanılan Sosyal Medya Platformları", a: "sosyal",
      d: "Aylık aktif kullanıcı ve etkileşim.",
      m: ["Instagram", "YouTube", "WhatsApp", "TikTok", "X (Twitter)", "Facebook", "LinkedIn", "Telegram", "Snapchat", "Reddit"] },
    { t: "En İyi Mesajlaşma Uygulamaları", a: "sosyal",
      d: "Gizlilik ve özellik dengesi.",
      m: ["WhatsApp", "Telegram", "Signal", "BiP", "Messenger", "Discord", "iMessage", "Threema", "Session", "Element"] },
    { t: "En İyi Video Platformları", a: "video",
      d: "İçerik üretici ve izleyici için.",
      m: ["YouTube", "TikTok", "Instagram Reels", "Twitch", "Vimeo", "Dailymotion", "Rumble", "Kick", "Nebula", "Odysee"] },
    { t: "En İyi Türk YouTube Kanalları", a: "video",
      d: "Abone sayısı ve içerik kalitesi.",
      m: ["Ruhi Çenet", "Barış Özcan", "Evrim Ağacı", "Orkun Işıtmak", "Enes Batur", "Gökhan Kabak", "Mesut Süre", "Datçalı", "Cem Seymen", "Sarkaç"] },
    { t: "En İyi Canlı Yayın Platformları", a: "video",
      d: "Oyun ve sohbet yayınları.",
      m: ["Twitch", "YouTube Live", "Kick", "TikTok Live", "Instagram Live", "Facebook Gaming", "Trovo", "DLive", "Rumble", "Discord Stage"] },
    { t: "En İyi Podcast Platformları", a: "video",
      d: "Dinleme ve yayınlama araçları.",
      m: ["Spotify", "Apple Podcasts", "YouTube Music", "Google Podcasts", "Pocket Casts", "Overcast", "Castbox", "Podbean", "Anchor", "Fizy Podcast"] },

    // ---- Finans siteleri ----
    { t: "En İyi Borsa ve Piyasa Takip Siteleri", a: "finans-site",
      d: "Grafik, veri ve analiz.",
      m: ["TradingView", "Investing.com", "Fintables", "Matriks", "Foreks", "BigPara", "Bloomberg HT", "Yahoo Finance", "Midas", "Bloomberg Terminal"] },
    { t: "En İyi Kripto Takip Siteleri", a: "finans-site",
      d: "Fiyat, hacim ve portföy takibi.",
      m: ["CoinMarketCap", "CoinGecko", "TradingView", "DefiLlama", "Glassnode", "Messari", "Dune Analytics", "CryptoQuant", "Nansen", "Arkham"] },
    { t: "En İyi Fatura ve Abonelik Takip Araçları", a: "finans-site",
      d: "Düzenli ödemeleri kontrol altında tutmak için.",
      m: ["Paraşüt", "Fintables", "Rocket Money", "Bobby", "Subby", "Wallet by BudgetBakers", "Money Manager", "Spendee", "Abonelik Takip", "Emma"] },

    // ---- Sağlık / araç / ilan / eğlence ----
    { t: "En İyi Sağlık Bilgi Siteleri", a: "saglik-site",
      d: "Güvenilir sağlık içeriği sunan kaynaklar.",
      m: ["e-Nabız", "Sağlık Bakanlığı", "Acıbadem Sağlık Rehberi", "Memorial Sağlık Rehberi", "WebMD", "Mayo Clinic", "NHS", "Medikal Akademi", "Doktorsitesi", "Sağlık Aktüel"] },
    { t: "En İyi Fitness ve Beslenme Uygulamaları", a: "saglik-site",
      d: "Antrenman ve kalori takibi.",
      m: ["MyFitnessPal", "Diyetkolik", "Strava", "Nike Training Club", "Fitbit", "Yazio", "Freeletics", "Hevy", "Zwift", "Adidas Running"] },
    { t: "En İyi Meditasyon ve Uyku Uygulamaları", a: "saglik-site",
      d: "Zihin sağlığı ve uyku desteği.",
      m: ["Meditopia", "Headspace", "Calm", "Insight Timer", "Wellbees", "Sleep Cycle", "Breethe", "Waking Up", "Endel", "Portal"] },
    { t: "En İyi Araç Alım Satım Siteleri", a: "arac",
      d: "İkinci el ve sıfır araç ilanları.",
      m: ["Sahibinden.com", "Arabam.com", "Otokoç İkinci El", "Garenta İkinci El", "Vavacars", "Doğuş Oto", "Borusan Next", "Autoscout24", "Otoplus", "İkinci El Araba"] },
    { t: "En İyi Seri İlan Siteleri", a: "ilan",
      d: "Alım satım ve hizmet ilanları.",
      m: ["Sahibinden.com", "Letgo", "Dolap", "Hepsiemlak", "Arabam.com", "İkinci El Pazarı", "Emlakjet", "Gittigidiyor", "Zingat", "İlan.com.tr"] },
    { t: "En İyi Etkinlik ve Bilet Siteleri", a: "eglence",
      d: "Konser, tiyatro ve etkinlik biletleri.",
      m: ["Biletix", "Passo", "Bubilet", "Biletinial", "Mobilet", "Etkinlik.io", "Bugece", "İKSV Bilet", "Ticketmaster", "Eventbrite"] },
    { t: "En İyi Oyun Satış Platformları", a: "eglence",
      d: "Dijital oyun mağazaları.",
      m: ["Steam", "Epic Games Store", "GOG", "PlayStation Store", "Xbox Store", "Nintendo eShop", "itch.io", "Humble Bundle", "Battle.net", "EA App"] },
    { t: "En İyi Yemek Tarifi Siteleri", a: "eglence",
      d: "Denenmiş tarifler ve mutfak içerikleri.",
      m: ["Nefis Yemek Tarifleri", "Yemek.com", "Refika'nın Mutfağı", "Arda'nın Mutfağı", "Lezzet.com.tr", "Onedio Yemek", "Serious Eats", "BBC Good Food", "Allrecipes", "NYT Cooking"] },
    { t: "En İyi Türkçe Forum ve Topluluklar", a: "forum",
      d: "Soru sorma ve tartışma platformları.",
      m: ["Ekşi Sözlük", "Technopat Sosyal", "Donanım Haber Forum", "Reddit r/Turkey", "İnci Sözlük", "Kızlar Soruyor", "Uludağ Sözlük", "Webtekno Forum", "Frmtr", "Şikayetvar"] },
    { t: "En İyi Global Forum ve Topluluklar", a: "forum",
      d: "Uluslararası tartışma platformları.",
      m: ["Reddit", "Hacker News", "Stack Overflow", "Quora", "Discord Toplulukları", "Product Hunt", "Indie Hackers", "Lobste.rs", "XDA Developers", "Slashdot"] },
    { t: "En İyi Tüketici Şikâyet Platformları", a: "forum",
      d: "Marka ve hizmet şikâyetleri.",
      m: ["Şikayetvar", "Tüketici Şikayet", "Trustpilot", "Google Yorumları", "Ekşi Sözlük", "Şikayet Bildir", "Tüketici Hakem Heyeti", "E-Şikayet", "Yorumla", "Marka Şikayet"] },

    // ---- E-ticaret (devam) ----
    { t: "En İyi Kozmetik ve Bakım Siteleri", a: "e-ticaret",
      d: "Makyaj ve cilt bakımı alışverişi.",
      m: ["Gratis", "Watsons", "Rossmann", "Sephora Türkiye", "Flormar", "Golden Rose", "Farmasi", "Trendyol Beauty", "Notino", "Hepsiburada Kozmetik"] },
    { t: "En İyi Mobilya ve Dekorasyon Siteleri", a: "e-ticaret",
      d: "Ev eşyası ve dekor alışverişi.",
      m: ["IKEA", "Vivense", "Bellona", "Doğtaş", "Enza Home", "Modalife", "Karaca Home", "Madame Coco", "English Home", "Koçtaş"] },
    { t: "En İyi Spor Ürünleri Siteleri", a: "e-ticaret",
      d: "Spor giyim ve ekipman.",
      m: ["Decathlon", "Nike Türkiye", "Adidas Türkiye", "Sportive", "Hepsiburada Spor", "Trendyol Spor", "Puma Türkiye", "Intersport", "Under Armour", "Salomon Türkiye"] },
    { t: "En İyi Evcil Hayvan Ürünleri Siteleri", a: "e-ticaret",
      d: "Mama ve aksesuar alışverişi.",
      m: ["Petlebi", "Petshop.com.tr", "Zoetis Pet", "Petzzshop", "Miyav", "Pati Market", "Kedimo", "Trendyol Pet", "Hepsiburada Pet", "Petburada"] },
    { t: "En İyi Hediye ve Çiçek Siteleri", a: "e-ticaret",
      d: "Özel günler için sipariş.",
      m: ["Çiçeksepeti", "Bonnyfood", "Hediyesepeti", "Nar Gourmet", "Çikolata Sepeti", "Butigo Hediye", "Hediye Kutusu", "Sürpriz Hediye", "Flowerland", "Buketim"] },
    { t: "En İyi Anne Bebek Ürünleri Siteleri", a: "e-ticaret",
      d: "Bebek bakım ve giyim.",
      m: ["Ebebek", "Joker Bebek", "Prenatal", "Mothercare Türkiye", "Trendyol Bebek", "Hepsiburada Bebek", "Bebekmarketi", "Civil Baby", "Panço", "Zeyland"] },

    // ---- Verimlilik / geliştirici (devam) ----
    { t: "En İyi E-posta Servisleri", a: "verimlilik",
      d: "Gizlilik ve kullanım kolaylığı.",
      m: ["Gmail", "Proton Mail", "Outlook", "Fastmail", "Zoho Mail", "Tutanota", "Yandex Mail", "iCloud Mail", "HEY", "Mail.com"] },
    { t: "En İyi Tarayıcılar", a: "verimlilik",
      d: "Hız, gizlilik ve eklenti desteği.",
      m: ["Google Chrome", "Firefox", "Safari", "Microsoft Edge", "Brave", "Arc", "Vivaldi", "Opera", "DuckDuckGo Browser", "Zen Browser"] },
    { t: "En İyi Tarayıcı Eklentileri", a: "verimlilik",
      d: "Günlük kullanımı kolaylaştıran eklentiler.",
      m: ["uBlock Origin", "Bitwarden", "Grammarly", "Dark Reader", "SponsorBlock", "Raindrop.io", "Wappalyzer", "JSON Viewer", "Momentum", "Video Speed Controller"] },
    { t: "En İyi Dosya Paylaşım Servisleri", a: "verimlilik",
      d: "Büyük dosya gönderme.",
      m: ["WeTransfer", "Google Drive", "Dropbox Transfer", "Send Anywhere", "Filemail", "pCloud Transfer", "Smash", "Firefox Send alternatifleri", "TransferNow", "MASV"] },
    { t: "En İyi Web Analiz Araçları", a: "gelistirici",
      d: "Site trafiği ve kullanıcı davranışı.",
      m: ["Google Analytics", "Plausible", "Umami", "Fathom Analytics", "Matomo", "Vercel Analytics", "Cloudflare Web Analytics", "Mixpanel", "PostHog", "Hotjar"] },
    { t: "En İyi Hata İzleme Araçları", a: "gelistirici",
      d: "Üretimdeki hataları yakalamak için.",
      m: ["Sentry", "Datadog", "New Relic", "LogRocket", "Bugsnag", "Rollbar", "Better Stack", "Highlight.io", "Honeybadger", "Raygun"] },
    { t: "En İyi CI/CD Araçları", a: "gelistirici",
      d: "Otomatik test ve dağıtım.",
      m: ["GitHub Actions", "GitLab CI", "CircleCI", "Jenkins", "Vercel", "Netlify", "Buildkite", "Drone CI", "Travis CI", "Argo CD"] },
    { t: "En İyi Tasarım Sistemleri ve UI Kütüphaneleri", a: "gelistirici",
      d: "Hazır bileşen setleri.",
      m: ["shadcn/ui", "Material UI", "Tailwind CSS", "Chakra UI", "Ant Design", "Radix UI", "Mantine", "Bootstrap", "Headless UI", "DaisyUI"] },
    { t: "En İyi Yazılım Dokümantasyon Siteleri", a: "gelistirici",
      d: "İyi yazılmış resmî dokümanlar.",
      m: ["MDN Web Docs", "React Docs", "Next.js Docs", "Stripe Docs", "Tailwind CSS Docs", "Rust Book", "Django Docs", "Vue Docs", "PostgreSQL Docs", "Anthropic Docs"] },

    // ---- Yeni alt kategoriler ----
    { t: "En İyi Harita ve Navigasyon Servisleri", a: "arac",
      d: "Yol tarifi ve trafik bilgisi.",
      m: ["Google Haritalar", "Yandex Navigasyon", "Apple Haritalar", "Waze", "OpenStreetMap", "Organic Maps", "Sygic", "Here WeGo", "Maps.me", "TomTom Go"] },
    { t: "En İyi Hava Durumu Siteleri ve Uygulamaları", a: "arac",
      d: "Tahmin doğruluğu ve arayüz.",
      m: ["Meteoroloji Genel Müdürlüğü", "Windy", "AccuWeather", "Weather.com", "Yandex Hava", "Havadurumu15gunluk", "Apple Hava Durumu", "Carrot Weather", "Ventusky", "Foreca"] },
    { t: "En İyi Çeviri ve Yazım Denetimi Araçları", a: "arac",
      d: "Metin çevirisi ve dil kontrolü.",
      m: ["DeepL", "Google Çeviri", "Grammarly", "LanguageTool", "QuillBot", "Yazım Denetimi TDK", "Reverso", "Linguee", "Microsoft Translator", "Papago"] },
    { t: "En İyi Dosya Dönüştürme Araçları", a: "arac",
      d: "Format değiştirme siteleri.",
      m: ["CloudConvert", "iLovePDF", "Smallpdf", "Convertio", "Zamzar", "Online-Convert", "FreeConvert", "TinyPNG", "Squoosh", "HandBrake"] },
    { t: "En İyi Ekran Görüntüsü ve Kod Paylaşım Araçları", a: "arac",
      d: "Kod ve görsel paylaşımı.",
      m: ["Carbon", "Ray.so", "CodePen", "GitHub Gist", "Pastebin", "CodeSandbox", "StackBlitz", "Replit", "JSFiddle", "Snappify"] },
    { t: "En İyi Kısa Link ve QR Servisleri", a: "arac",
      d: "Bağlantı kısaltma ve QR üretimi.",
      m: ["Bitly", "TinyURL", "Rebrandly", "Short.io", "QR Code Generator", "Linktree", "Dub.co", "Cuttly", "T.LY", "Beacons"] },
    { t: "En İyi Ücretsiz Müzik ve Ses Efekti Kaynakları", a: "tasarim",
      d: "Video ve içerik üretimi için telifsiz ses.",
      m: ["YouTube Audio Library", "Pixabay Music", "Free Music Archive", "Freesound", "Epidemic Sound", "Artlist", "Bensound", "Uppbeat", "Mixkit", "Zapsplat"] },
    { t: "En İyi Video Düzenleme Yazılımları", a: "tasarim",
      d: "Kurgu ve efekt araçları.",
      m: ["DaVinci Resolve", "Adobe Premiere Pro", "Final Cut Pro", "CapCut", "Filmora", "Adobe After Effects", "Shotcut", "Kdenlive", "Descript", "Canva Video"] },
    { t: "En İyi 3D ve Modelleme Yazılımları", a: "tasarim",
      d: "Modelleme, animasyon ve render.",
      m: ["Blender", "Cinema 4D", "Autodesk Maya", "3ds Max", "SketchUp", "Rhino", "Houdini", "ZBrush", "Fusion 360", "Spline"] },
    { t: "En İyi Arama Motorları", a: "arac",
      d: "Sonuç kalitesi ve gizlilik dengesi.",
      m: ["Google", "Bing", "DuckDuckGo", "Perplexity", "Brave Search", "Yandex", "Ecosia", "Startpage", "Kagi", "Mojeek"] },
    { t: "En İyi Yer İmi ve Okuma Listesi Araçları", a: "verimlilik",
      d: "Sonra okumak için içerik biriktirme.",
      m: ["Raindrop.io", "Pocket", "Instapaper", "Readwise Reader", "Notion Web Clipper", "Matter", "Omnivore", "Wallabag", "Anybox", "GoodLinks"] },
    { t: "En İyi Anket ve Form Araçları", a: "verimlilik",
      d: "Veri toplama ve geri bildirim.",
      m: ["Google Forms", "Typeform", "Tally", "Microsoft Forms", "SurveyMonkey", "Jotform", "Fillout", "Formspree", "Airtable Forms", "Paperform"] },
    { t: "En İyi Elektronik Tablo ve Veri Araçları", a: "verimlilik",
      d: "Hesaplama ve veri düzenleme.",
      m: ["Google Sheets", "Microsoft Excel", "Airtable", "Notion Databases", "Coda", "Rows", "Smartsheet", "Baserow", "NocoDB", "Grist"] },
    { t: "En İyi Site Kurma ve İçerik Yönetim Sistemleri", a: "gelistirici",
      d: "Kod yazmadan ya da az kodla site kurma.",
      m: ["WordPress", "Webflow", "Framer", "Shopify", "Wix", "Ghost", "Squarespace", "Sanity", "Strapi", "Payload CMS"] },
  ],
};
